### ISSUE TITLE
[feature] Integrate travis+ unit test on github for community PRs

### ISSUE THREAD

**Issue by cesco69** [W3EDGE/w3-total-cache#1]
On [w3-total-cache-fixed](https://github.com/szepeviktor/w3-total-cache-fixed) (aka community version) there are a set of [unit-test](https://github.com/szepeviktor/w3-total-cache-fixed/tree/v0.9.6.x_wip/tests) with a [Travis CI](https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.6.x_wip/.travis.yml).

My suggesion is copy the existent unit tests and add new tests for check the community PRs.

PS. Welcome on GitHub!

**Comment by maxicus** [comment]
W3TC has much wider test coverage which is not integrated yet with public repository, but will be available in a future.

**Comment by maxicus** [comment]
we've finally published the CD system we use for testing and functionality checks across all supported environments.
It use AWS for nightly builds and allows to use Vagrant+VirtualBox for local testing.
There's no plans to integrate it to Travis at the moment.
