### ISSUE TITLE
Can't disable New Relic integration

### ISSUE THREAD

**Issue by dbackeus** [W3EDGE/w3-total-cache#10]
After assigning an API key for New Relic I'm unable to remove the API key again (an empty field will generate a validation error) and I can't find any way of disabling the integration from the "monitoring" settings page either.

Am I missing something?

**Comment by maxicus** [comment]
"Extensions" page, click "Deactivate" for "New Relic" extension.

**Comment by MarcinDudekDev** [comment]
Deactivating the extension doesn't work, it still loads the JS file. I'm running 2.2.1, was it fixed in newer versions?
