### ISSUE TITLE
Wordpresss Multisite - “The link you followed has expired”

### ISSUE THREAD

**Issue by andcha** [W3EDGE/w3-total-cache#103]
_Reference links:_
https://wordpress.org/support/topic/the-link-you-followed-has-expired-in-network-site/
https://wordpress.org/support/topic/cache-preload-on-multisite-2/

This issue has been around for a **YEAR** now, is there any resolution for this?

**Comment by mavas84** [comment]
Hello @andcha 
As these are two separate issues I've created the tickets on your behalf.
Thank you!
https://github.com/W3EDGE/w3-total-cache/issues/105
https://github.com/W3EDGE/w3-total-cache/issues/106
