### ISSUE TITLE
Can I cache my site for all but the main page?

### ISSUE THREAD

**Issue by jmcd040** [W3EDGE/w3-total-cache#110]

**Comment by jmcd040** [comment]
My main page has a widget that shows a different random quote each time the user loads it (providing their browser cache doesn't ignore the new page). Can I somehow disable your plug-in from caching the front page of my site? Or is there another way to handle this?

**Comment by mavas84** [comment]
Hello @jmcd040 
Thank you for your inquiry and I am happy to assist you with this.
In Performance>Page Cache you can disable the option: "Cache front page". You can also exclude a specific page from the cache by adding that page to the Performance>Page Cache>Advanced, "Never cache following pages" text area.
If you want your pages to be cached but just want to exclude specific dynamic parts of the page from the cache you can also use Page Fragment Cache. You can find more details about Page Fragment Cache in our [FAQ](https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-Developers#what-is-page-fragment-cache).
Please note that as the readme of this repository states:
This repository is not suitable for support. Please don't use our issue tracker for support requests. Support can take place through the appropriate channels like wp.org or via the plugin in Performance>Support.
Thank you.
