### ISSUE TITLE
Determine why the page cache was flushed

### ISSUE THREAD

**Issue by sweber83** [W3EDGE/w3-total-cache#118]
We are currently working on a multisite, which relies on w3tc for caching.
One issue which is really causing us headaches is how to find out why the page cache was flushed.
The logs don't contain this information.
The problem is on this site, the page cache is always flushed after something like 45min, although we set all expiration times to a whole day.
The issue is not that the cache gets flushed manually, we already checked that.

**Comment by bwmarkle** [comment]
Hi @sweber83,

We're actually working on a new "purge cache log" that users can enable to view what is triggering cache to be cleared. It should be released within a week or two. I'll keep you updated.

Thanks,
\- Brad

**Comment by sweber83** [comment]
@bwmarkle 
That's great news.
I'll have an eye on the releases :)

Regards
Simon

**Comment by bwmarkle** [comment]
Hi @sweber83,

I just wanted to chime in and mention that we did release this new feature last week. You can find a bit of information about it here: https://www.boldgrid.com/support/w3-total-cache/purge-cache-log/

Thanks,
\- Brad
