### ISSUE TITLE
cache control for json

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [W3EDGE/w3-total-cache#119]
Wordpress has json/oembed link in the head, for example:

```html
<link rel="alternate" type="application/json+oembed" href="https://yoast.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fyoast.com%2Fultimate-guide-blogging%2F" />
```
The link is a json file. 

But W3 Total Cache puts a "cache-control: max-age" of media not html or xml.

**Comment by maxicus** [comment]
Right. ".json" belongs to "other" sectiion.

**Comment by vijayaraghavanramanan** [comment]
Sorry why was this closed? The cache-control shouldn't have the max-age of that long, and should have the same max-age as html.

**Comment by maxicus** [comment]
You see, there is no right or wrong answer to that problem exists and everything depends on what do you store in such files in your applications.
Some may require yaml,json,pdf,docx,(hundrends of other content file extensions) to be short, some to be long. Plugin tries to take cover some common cases but it will never make everyone happy.

If you need non-default headers in that area you may always switch off "other" section and copy-paste htaccess rules with own modifications.
