### ISSUE TITLE
Add blog=.. parameter for WP-CLI multi-site cache flushing

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#120]
Reference topic:
https://wordpress.org/support/topic/wp-cli-w3-commands-on-multisite-not-working/

**Comment by jacobd91** [comment]
This issue is over 2 years old and under current version the CLI commands appear to be functioning properly on both standalone and multi-site installations. As such the reported issue cannot be replicated and appears to have already possibly been resolved by a previous update
