### ISSUE TITLE
Fix nginx warning when flushing all cache (or minify cache) on any sub-site

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#123]
When using WP multisite and trying to flush all cache (or minify cache) on any sub-site, “_nginx.conf rules have been updated. Please restart the nginx server to provide a consistent user experience_.” that warning always occurs whether you reload nginx or not. So, it might be a small bug. Also, that warning cannot be hidden unless you go to W3TC settings on any sub-site.
```
ReferenceError: w3tc_beforeupload_unbind is not defined
 /wp-admin/?w3tc_note=flush_minify:235
```
Reference topic: https://wordpress.org/support/topic/about-nginx/

**Comment by maxicus** [comment]
was fixed by previous commits.

"rules have been updated" comes from initial rules changes and shown on all subblogs.
doesn't reappear on purge.
