### ISSUE TITLE
need separate configs for multisite domain mapping and separate CDNs when network-enabled

### ISSUE THREAD

**Issue by tamw-wnet** [W3EDGE/w3-total-cache#127]
We run a multisite WP install that uses domain mapping, like so:
"site" a = www.siteA.com
"blog" 2 = www.siteA.com/blog2
"site" b = www.siteB.com
"blog" 3 = www.siteB.com/blog3

and we want different CDNs for the different domains, for SSL and pathing issues -- eg site a has "cdn.siteA.com" and site b has "cdn.siteB.com".   In W3TC this configuration isn't supported natively.   The config for a network install only allows for a single CDN.

**Comment by mavas84** [comment]
Hello @tamw-wnet 
Thank you for your inquiry and I am happy to assist you with this. In Performance>General>Miscellaneous settings there is an option "Use single network configuration file for all sites". If that option is checked, please un-check it and save all settings.
This will allow you to have different configs for each site.
Also, this repository is not suitable for support. Please don't use our issue tracker for support requests. Support can take place through the appropriate channels:

The support form can be found in the Performance -> Support page of your wp-admin.
Our community forum on wp.org.
Thank you!

**Comment by tamw-wnet** [comment]
@mavas84 This setting does not work for the situation where we have multiple "networks" -- I should've been more clear, but the WordPress naming conventions of "site", "blog", and "network" are confusing and often misunderstood.    The "wp_sites" table, in the context of 'multi-site', refers to networks of blogs.   In a typical multi-site configuration, all blogs have the same 'site id' (usually '1') but unique 'blog id' values.   In a multi-network multi-site installation, each 'network' has a separate 'site id' indicating the site/network that the blog is a member of.  

The setting you're describing **does** work if there's a single network (where all "blogs" have the same "site id"), but when there are multiple networks (multiple entries in the wp_sites table) only one network-wide setting will be used.

What I want to be able to do is network-enable W3TC for site(network) 1 and site(network) 2, and have the settings for site 1 apply to all of the blogs belonging to the site 1 network and have the setting for site 2 apply to all the blogs in the site 2 network. 

The problem is in Line 81 of Config.php -- 
https://github.com/W3EDGE/w3-total-cache/blob/9312f823ada3030766d4a3a9b9d98a6bb654a429/Config.php#L81 -- it only allows for one 'master' config.
  
This is an issue.  I'm working out a backwards-compatible code fix so I can submit a pull request to address the issue, actually.    We've been manually applying a hack for the last several years to make W3TC function in our multi-site multi-network install and I'd rather just get it into the code.

**Comment by maxicus** [comment]
@tamw-wnet I see now.

"network of multisites" is not supported by W3TC plugin and there are no plans now so there are issues possible in many areas.
Also behavior may be specific to a plugin you used for "network of multisites" instantiation.

In any case you are welcome to try and share your experience, but be prepared.
As a hint i may suggest to look at `Util_WpmuBlogmap`, `Config` and `Dispatcher` classes for the start.

**Comment by tamw-wnet** [comment]
We've been using W3TC in 'network of multisites' configuration for a few years without any problems, the only workaround we had to do was to make it possible for each network to have it's own 'master' config file.  The method I've been using is to save each 'master' file with the hostname of the network.  That isn't very backwards compatible to non-multi-network installs, however -- I ignore the actual 'master' file.  Anyway, thanks very much for the suggestions on which classes to look at!

**Comment by maxicus** [comment]
if only there - I may offer a hook, something like:
```
if ( $blog_id <= 0 )
	return W3TC_CONFIG_DIR . '/master' . $postfix;
```
=>
```
if ( $blog_id <= 0 ) {
	return w3tc_apply_filters( 'config_filename', W3TC_CONFIG_DIR . '/master' . $postfix );
}
```

In that case you will have to write your own logic, potentially in wp-config.php by something like
```
require_once 'pathtoplugin/w3-total-cache-api.php';

function my_filename($old_filename) {
	return 'your-version-of-config-filename';
}

w3tc_add_action( 'config_filename', 'my_filename' );
```

Let me know if it works for you.

**Comment by tamw-wnet** [comment]
@maxicus this looks like an excellent solution.  Will w3tc_apply_filters() work now if I change that line of Config.php to match, so I can test out?

Another approach I'd been thinking about was to test the value of SITE_ID_CURRENT_SITE -- if it is non-empty and != 1, append that value to "master" eg "master_2".  like so

```
if ( $blog_id <= 0 )
	$sitesuffix = (!empty(SITE_ID_CURRENT_SITE) && (SITE_ID_CURRENT_SITE > 1)) ? '_' . SITE_ID_CURRENT_SITE : '';
	return W3TC_CONFIG_DIR . '/master' . $sitesuffix . $postfix;
```

I haven't checked to see whether SITE_ID_CURRENT_SITE gets assigned early enough before wp_core gets loaded for this to work, however.   And it doesn't have quite the flexibility of your suggestion, because mine _forces_ each network to have separate configurations.

**Comment by maxicus** [comment]
> Will w3tc_apply_filters() work now if I change that line of Config.php to match, so I can test out?

@tamw-wnet Yes, it will work.
Regarding constant - W3TC may act and require it's config e.g. before database connection is made and since usually database stores information about all IDs...

**Comment by tamw-wnet** [comment]
@maxicus that worked nicely.  For the record, here's what I did.

near the end of wp-config.php , on the line after ABSPATH is defined I added:

```
$w3tcapifile = ABSPATH . 'wp-content/plugins/w3-total-cache/w3-total-cache-api.php';
if ((include_once $w3tcapifile) == TRUE) {
  function w3tc_multi_network_config_filename($old_filename) {
    $new_filename = ABSPATH . 'wp-content/w3tc-config/master-' . $_SERVER['HTTP_HOST'] . '.php';
    return $new_filename;
  }
  w3tc_add_action( 'config_filename', 'w3tc_multi_network_config_filename' );
}
```
And in Config.php in the plugin I implemented your offered filter on lines 81-83

```
if ( $blog_id <= 0 ) {
	return w3tc_apply_filters( 'config_filename', W3TC_CONFIG_DIR . '/master' . $postfix );
}
```

The end result is that each network has it's own "master" config file; and that's a configuration we've been running successfully for several years.

The only suggestion I might make here is to enable the "preview" mode files, but I wasn't sure how to do that in the context of w3tc_apply_filters().

**Comment by tamw-wnet** [comment]
Noting also one assumption -- in our version of 'network of networks' configuration, each set of multisites has a single root domain, and that's how we're defining the 'master' file names.  In networks that are set to do either 'sub-domain' or 'domain mapping' , I'm not 100% sure this approach will work; I suspect it will, but I've not tested it.

**Comment by tamw-wnet** [comment]
@maxicus let me know if/when you incorporate the offered hook from https://github.com/W3EDGE/w3-total-cache/issues/127#issuecomment-580805583  , that would resolve this issue.
