### ISSUE TITLE
Support Feature Policy Security Header

### ISSUE THREAD

**Issue by Haribu** [W3EDGE/w3-total-cache#13]
Hi Team, 
Love the product, and thank you for supporting it!

It would be great if 'Feature Policy' options could be added at some point to the Security Headers options. 

Reference: https://developers.google.com/web/updates/2018/06/feature-policy
Similar Add-on: https://wordpress.org/plugins/feature-policy/, https://felix-arntz.me/blog/introducing-feature-policy-reporting-api-for-wordpress/

**Comment by mavas84** [comment]
Hello @Haribu 
Thank you for your patience. Please make sure to update the plugin to the latest 2.1.7 release as the Feature Policy has been added under Performance>Browser cache that allows you to control which origins can use which features.
Thanks!
