### ISSUE TITLE
PHP Notices flooding the error log

### ISSUE THREAD

**Issue by jotazzu** [W3EDGE/w3-total-cache#134]
Unfortunately some variables are not properly checked for existence in new version v0.13.0:

[31-Jan-2020 16:40:33 UTC] PHP Notice:  Undefined variable: page_key_extension in /usr/www/users/xxxx/wp-content/plugins/w3-total-cache/PgCache_ContentGrabber.php on line 771
[31-Jan-2020 16:40:33 UTC] PHP Notice:  Undefined index: host in /usr/www/users/xxxx/wp-content/plugins/w3-total-cache/PgCache_ContentGrabber.php on line 1442

**Comment by bwmarkle** [comment]
Hi @jotazzu!

We're very sorry to hear about your logs getting filled with these notices. We're working on a patch release to resolve this, and should have it out by the end of the week. We'll keep you updated.

Thanks,
\- Brad

**Comment by maxicus** [comment]
@jotazzu it's fixed. Can you please check if the commit above solved it for you?

**Comment by jotazzu** [comment]
I've checked it with the changes and the PHP notices do not occur any more when calling URLs which result in status 301.

**Comment by steve-vancouver** [comment]
Is this still a problem? I'm getting a similar error on my local environment: 
"preg_match(): Compilation failed: nothing to repeat at offset 0 in /Applications/MAMP/htdocs/mywebsite.local/wp-content/plugins/w3-total-cache/PgCache_ContentGrabber.php on line 946"

**Comment by mavas84** [comment]
Hello @steve-vancouver 
The error message that you are getting is not related to the original issue. This means that you have invalid regexp when excluding a page from being cached in Peformance>Page Cache>"Never cache the following pages"
Please check the [FAQ](https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-Usage#which-textareas-for-file-entries-support-regular-expressions) page for detailed instructions and this [article](https://www.dropbox.com/s/kv1qi3rzi13wef7/How%20to%20exclude%20page_pages%20from%20cache_.docx?dl=0) may help you also.
Thank you!

**Comment by steve-vancouver** [comment]
Thanks! @mavas84 
That solved the problem! 
I had `*ajax_checkfav\.php*` in the "Never cache the following" field and that's what was causing the errors.

**Comment by mavas84** [comment]
Hello @steve-vancouver 
You are most welcome. Glad to know your issue is resolved!
Thanks!

**Comment by dacosta-rafael** [comment]
This is still an issue. was this tested before release?
