### ISSUE TITLE
Add ability to remove emojis

### ISSUE THREAD

**Issue by martijn19811** [W3EDGE/w3-total-cache#135]
Since [WordPress 4.2](https://wordpress.org/support/wordpress-version/version-4-2/#emoji), an emoji-plugin has been added to the core of WordPress. While this plugin is relatively small, only 11kb or so, it **does** add another HTTP request in the progress.

Please provide an ability to prevent this emoji script from loading.

**Comment by maxicus** [comment]
Oh yeah, it's redundant for 90% of websites I think.
Thanks for idea.
