### ISSUE TITLE
W3TC doesn’t clear cache of custom post types archives

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#139]
Reference topic:
https://wordpress.org/support/topic/custom-posts-type-page-not-purged-when-new-content-published/
https://wordpress.org/support/topic/doesnt-clear-cache-for-custom-post-types-archives/

**Comment by AbrahamBrookes** [comment]
This says closed, but I believe it is not resolved.

I am running 2.1.9:
![image](https://user-images.githubusercontent.com/8340776/138387054-b9731a1f-ad62-4df9-afd4-584baa671c8c.png)


I have created a new custom post type:

```
	register_post_type( 'event', [
		'label'         =>   __( 'Events', 'uep' ),
		'labels'        =>   [
			'name'                  =>   __( 'Events', 'uep' ),
			'singular_name'         =>   __( 'Event', 'uep' ),
			'add_new_item'          =>   __( 'Add New Event', 'uep' ),
			'all_items'             =>   __( 'All Events', 'uep' ),
			'edit_item'             =>   __( 'Edit Event', 'uep' ),
			'new_item'              =>   __( 'New Event', 'uep' ),
			'view_item'             =>   __( 'View Event', 'uep' ),
			'not_found'             =>   __( 'No Events Found', 'uep' ),
			'not_found_in_trash'    =>   __( 'No Events Found in Trash', 'uep' )
		],
		'description'   =>   __( 'A list of upcoming events', 'uep' ),
		'public'        =>   true,
		'show_in_menu'  =>   true,
		'menu_icon'     =>   IMAGES . 'event.svg',
		'has_archive'   =>   true,
		'rewrite'       =>   true,
		'supports'      =>   [
			'title',
			'editor',
			'excerpt',
			'thumbnail',
			'revisions'
		],
		'taxonomies' 	=> 	 [ 
			"category", 
			"post_tag" 
		]
	]);
```

And I have a list of these events on my front page. 

I think I have my settings set up correctly:
![image](https://user-images.githubusercontent.com/8340776/138387128-c64a58ff-e224-4d15-a714-8ece8927cef1.png)

![image](https://user-images.githubusercontent.com/8340776/138387174-69a73321-29ff-496f-b539-fe5ff278599d.png)

![image](https://user-images.githubusercontent.com/8340776/138387245-2f322c3b-9933-4cee-96b1-baa13ea77234.png)

When I create a new Event and publish it, I can see it on the front page as an admin user (uncached) but when I look at the front page in firefox incognito, I don't see the new event.

Am I missing something?
