### ISSUE TITLE
Support page produces PHP warnings

### ISSUE THREAD

**Issue by timelsass** [W3EDGE/w3-total-cache#14]
Steps to reproduce:
1. Install and activate W3TC.
2. Go to _Performance > Support_ page in WP dashboard.

Tested in PHP 7.1, and PHP 7.2 - received 4 warnings on each.

Can [use this link to reproduce](https://boldgrid.com/central/cloud-wordpress/try?theme=https:%2F%2Fwordpress.org%2Fthemes%2Fdownload%2Fcrio.2.2.1.zip&plugins=query-monitor,w3-total-cache) in test environment.

PHP warnings:
![image](https://user-images.githubusercontent.com/11907254/58903422-6b6c6c80-86d3-11e9-94ba-47f698065fab.png)

Warning | Cannot assign an empty string to a string offset | 4 | -do_action('admin_print_scripts-performance_page_w3tc_support')wp-admin/admin-header.php:125W3TC\Support_Page::admin_print_scripts_w3tc_support()wp-includes/class-wp-hook.php:286wp_localize_script()wp-content/plugins/w3-total-cache/Support_Page.php:27WP_Scripts->localize()wp-includes/functions.wp-scripts.php:200wp-includes/class.wp-scripts.php:454 | Plugin: w3-total-cache
-- | -- | -- | -- | --

**Comment by maxicus** [comment]
fixed by https://github.com/W3EDGE/w3-total-cache/commit/a2c24a406b472d1d91f78e6aa6f4ef016f9e53fd
