### ISSUE TITLE
Lazy Loading Bug? Messing up Swiperjs Slide Height

### ISSUE THREAD

**Issue by andcha** [W3EDGE/w3-total-cache#143]
Hello team,

Does class lazy adds this as src to background images?

`<img class="swiper-slide-image lazy" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%20768%20525'%3E%3C/svg%3E" data-src="path/to/imag/blah-blah-768x525.jpg" alt="some alt text for seo best practice">`

If yes, the height and width of image is correctly specified in the viewbox, but the space reserved by this element is 1643 x 1123.14. An additional 600 pixel space between sections ruins the UI.

Disabling lazy load adds actual image path to img src, this normalizes section space.

Just for your information, I am on latest version of W3TC & Elementor.

**Comment by bwmarkle** [comment]
Hi @andcha, thanks for taking the time to let us know about this. We'll review and get back to you soon.

**Comment by andcha** [comment]
Thank you for your reply @bwmarkle. Please let me know in case you need further clarification.

**Comment by bwmarkle** [comment]
Hi @andcha we had one of our developers try and replicate the issue, but they weren't able to with Elementor. Can you share what other plugins you're running? It could be one of them conflicting.
