### ISSUE TITLE
Add Filter supporting Shortpixel to replace the image URL and then send back the adjusted CSS

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#146]
Add filter inside the plugin code for the following scenario:
- a user who is using W3TC plugin and also uses ShortPixel Adaptive Images plugin
- the site of this user is also using the CSS combine & minify options from W3TC plugin
- inside the CSS of the site, there are various calls to background images which are processed by ShortPixel Adaptive Images

In this scenario, Shortpixel will extract the CSS containing images and will serve it separately, making some additional requests which could be avoided. In order to avoid this situation which is not optimal for the user (from a performance point of view),  a filter is needed in your W3TC, which would allow Shortpixel to replace the image URL and then send back the adjusted CSS so that W3TC can do its job with the combine and minify modules. The filter needs to have the following:
- the CSS that will be combined/minified
- the source path of the original CSS, before combining/minifying (if available)
- the target path (on disk) where the combined CSS is written on disk

**Comment by pdobrescu** [comment]
thanks for adding the issue @mavas84! In case you need further details, please leave a comment here.

**Comment by pdobrescu** [comment]
We have just submitted pull request https://github.com/W3EDGE/w3-total-cache/pull/191 for this issue, please check it and review it. Thanks!

**Comment by cssjoe** [comment]
Thank you @pdobrescu and @short-pixel-optimizer for the contribution, which was released in version 0.14.0 on May 27th.
