### ISSUE TITLE
Syntax with curly braces is deprecated {}

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#157]
Add support for PHP 7.4
`Array and string offset access syntax with curly braces is deprecated`
/plugins/w3-total-cache/lib/OAuth/W3tcOAuth.php(102)
$result |= ord($built{$i}) ^ ord($signature{$i});
$result |= ord($built[$i]) ^ ord($signature[$i]);
Reference topic: https://wordpress.org/support/topic/php-7-4-support-9/

**Comment by dingman** [comment]
+1 support from me. We run exclusively php 7.4 right now

**Comment by maciejmackowiak** [comment]
any ETA on this one? the fix is super simple

thx in advance

**Comment by bwmarkle** [comment]
Hi @dingman and @maciejmackowiak - thanks for the heads up. We're taking a look at this one now and will get back soon.
