### ISSUE TITLE
Problem with a header - I cannot solve it!

### ISSUE THREAD

**Issue by Hahankaap** [W3EDGE/w3-total-cache#158]
After setting up the plugin, this happened to my main page. (see attached)
I am not an expert and I am trying to gas much as I can but I am not able to find a way to set it up correctly.
I would be really grateful if anyone could give me any advice!

Thank you.

<img width="1440" alt="Screenshot 2020-03-21 at 12 59 52" src="https://user-images.githubusercontent.com/62468232/77225969-87fb6780-6b74-11ea-8bdf-55dfae18c1e4.png">
<img width="1434" alt="Screenshot 2020-03-21 at 13 00 28" src="https://user-images.githubusercontent.com/62468232/77225974-934e9300-6b74-11ea-9524-39d7b3ed6296.png">

**Comment by Hahankaap** [comment]
This is how it should be but when I click PUBLISH it comes back to the wrong position

<img width="1437" alt="Screenshot 2020-03-21 at 13 21 56" src="https://user-images.githubusercontent.com/62468232/77226228-f9d4b080-6b76-11ea-9277-e0b5040fa9fe.png">

**Comment by dingman** [comment]
@Hahankaap try the support forum, this platform is for bug tracking

https://wordpress.org/support/plugin/w3-total-cache/

**Comment by mavas84** [comment]
Hello @Hahankaap 
This repository is not suitable for support. Please don't use our issue tracker for support requests. Support can take place through the appropriate channels: https://wordpress.org/support/plugin/w3-total-cache/ or via the plugin in Performance>Support.
This might be an issue when minify is enabled for logged in users. Go to Performance>Minify and enable the "Disable minify for logged in users" option, save all settings and purge the cache.
Thank you!

**Comment by Hahankaap** [comment]
Thank you and I am really sorry for posting it here!

**Comment by Hahankaap** [comment]
Thank you! It worked! But I had to disable Manify totally - otherwise, it worked only when I was logged in ;)
