### ISSUE TITLE
Never minify doesn't work with auto mode

### ISSUE THREAD

**Issue by jsodeman** [W3EDGE/w3-total-cache#16]
It seems like the Minify>Advanced>"Never minify the following JS files:" doesn't work when the Minify mode is set to Auto. Is this correct?

**Comment by maxicus** [comment]
https://github.com/W3EDGE/w3-total-cache#support

This repository is not suitable for support. Please don't use our issue tracker for support requests. Support can take place through the appropriate channels:

The support form can be found in Performance -> Support page of your wp-admin.
Our community forum on wp.org.
Support requests in issues on this repository will be closed on sight.
