### ISSUE TITLE
CSSTidy & PHP7.3 or greater warning

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#161]
Error when using W3TC w/CSSTidy enabled on PHP7.4:
`Got error 'PHP message: PHP Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/website/wp-content/plugins/w3-total-cache/lib/CSSTidy/class.csstidy.php on line 886'`

Manually applied the fix to line 886 of wp-content/plugins/w3-total-cache/lib/CSSTidy/class.csstidy.php as per: https://github.com/Cerdic/CSSTidy/commit/6342bdce367bd0b6b66ab715f749e18dae93eaf4
Reference topic: https://wordpress.org/support/topic/csstidy-php7-3-or-greater-warning/

**Comment by cssjoe** [comment]
CSSTIdy was updated and deployed on Jan 20 with the 2.1.0 release.
