### ISSUE TITLE
Some images not loading with Lazy load enabled after upgrading WP to 5.4

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#164]
On Chrome, some images do not load WHen Lazy load is enabled on the first load.
On firefox and Edge, all images load. When the Chrome window is resized then also all images load but not on the first load or reload when on full screen.
Reference topic: https://wordpress.org/support/topic/images-not-loading-after-wp-5-4-update/

**Comment by bwmarkle** [comment]
@mavas84 We cannot replicate. Can you help by getting us environment info, steps to replicate? One user did share their URL, but they did have JS errors on the page, and that could have caused the issue.

**Comment by WPLibrary** [comment]
@bwmarkle Hi,

@disturbed-pixel's issue related to the lazy load:
https://wordpress.org/support/topic/lazy-loading-display-issue/

This issue might also be similar to mine.

Although I cleared all the browser cache and plugin cache, I was facing the same issue on my website.
https://wordpress.org/support/topic/lazy-load-bug/

Screen record: https://yadi.sk/i/zN6jra8rTyXE2Q
(The record might be a bit long, sorry about that. I just wanted to wait until all the images and videos were fully loaded.)

I couldn't get any JS error while facing the issue and disabled it.

However, I also use W3TC's lazy load feature on my other website. And it is working smoothly on Chrome (Iph7)!

Hope this helps.

**Comment by bwmarkle** [comment]
Hi @WPLibrary I just tested on Chrome and Firefox (Windows 10), and the lazy loading of the image under _Feel just like a mobile app_ looks to be working as expected on https://serdarwork.com/discourse-installation/

I'll try to do some testing on a Mac / Safari and get back to you soon.

Thanks!

**Comment by bwmarkle** [comment]
@WPLibrary what version of Safari are you on?

**Comment by bwmarkle** [comment]
Hi @WPLibrary I don't have a Mac, but I had a video call with someone who was on a Mac and we tested https://serdarwork.com/discourse-installation/

They shared their screen while the developer console was open, and I was able to see lazy loading working successfully. They were running **macOS Mojave** _10.14.6_ and **Safari** _13.1_

![image](https://user-images.githubusercontent.com/5925563/79012491-6a4a6e00-7b34-11ea-9008-cb85b967b054.png)

![image](https://user-images.githubusercontent.com/5925563/79012502-70404f00-7b34-11ea-9cbb-fd2492e5a0c8.png)


Can you let us know which version of Safari you're testing with?

**Comment by WPLibrary** [comment]
Hi @bwmarkle Sorry for delay. Safari version is 13.1. It's the latest version I guess. 
Macbook Air 2017 - MacOS Catalina

Also, I can provide a remote connection (i.e Anydesk) if you need to check it.

Thanks again.

**Comment by bwmarkle** [comment]
Hi @WPLibrary sorry for the delay in getting back to you. I was out of the office for a while, but I'm back, and I'm looking into this ticket again.

I'm trying to get in touch with a team member on Catalina to test further, and if I can't, I'll reach out to you.

**Comment by bwmarkle** [comment]
Hi again @WPLibrary - on a quick note, someone on the team just pointed out to me that in your screenshot here - https://imgbu.com/i/lazy-load-test.MEpCn - the src attribute was actually replaced successfully, IE it's not blank, so that part of the lazy loading seems to be working.

---

Other feedback I've received too is:

> also tooltip says it's 1x1px size
> so like image was set correctly, but browser didnt resize it to actual size...

---

> I also use W3TC's lazy load feature on my other website too and this time the lazy load is working smoothly on Chrome.

To confirm, it the same browser, one of your sites has lazy loading working correctly with w3tc and the other does not?

**Comment by WPLibrary** [comment]
Hi @bwmarkle 

> also tooltip says it's 1x1px size
> so like image was set correctly, but browser didnt resize it to actual size...

I agree with that because the image appears when I enable or disable any style line from the devtool. Example: https://imgbu.com/i/apr-22-2020-18-56-42.McpCt

![Apr-22-2020-18-56-428536b9c072a8b3d5.gif](https://s.imgbu.com/file/imgbucom/2020/04/22/Apr-22-2020-18-56-428536b9c072a8b3d5.gif)

Also, I don't use a browser extension on Safari. **The plugins which I installed:**

Atomic Blocks - Gutenberg Blocks Collection
The SEO Framework
W3 Total Cache
WPForms Lite
Multisite Language Switcher

> To confirm, it the same browser, one of your sites has lazy loading working correctly with w3tc and the other does not?

Yes, I have tested the lazy load on my other website which has 15+ images on the same post, it was working smoothly on all browsers.

Thank you for your help, I appreciate that. Hope this helps.
Regards.

**Comment by mavas84** [comment]
Hello @WPLibrary 
I've tested this on Macbook Air latest Catalina OS and Safari 13.1 (also latest version)
when I opened https://serdarwork.com/discourse-installation/  the image was fully loaded:
![Screenshot 2020-04-24 at 18 05 30](https://user-images.githubusercontent.com/40050744/80236943-2be89f00-865c-11ea-98de-899f24687559.png)

I've refreshed the page a couple of times and I've also closed Safari and tried again with the same result.
The page when inspected:
![Screenshot 2020-04-24 at 18 07 35](https://user-images.githubusercontent.com/40050744/80236900-1e331980-865c-11ea-94e3-0d84d41da034.png)
Try excluding the image from lazy loading in Performance>User Experience>Exclude Words:
Simply add the URL of the image.
Thanks!

**Comment by WPLibrary** [comment]
Hi @mavas84 ,

Although I know how to fix the issue by excluding the images or disabling the feature, I just wanted to notify you if the above issue is similar to mine. Again, thank you very much for your kind help 👍 

Another similar issue that I saw today: https://wordpress.org/support/topic/image-lazy-loading-on-enfold/ 

I think all these issues are related to the themes' style. (especially width and height attributes of images).

Best regards.

**Comment by mavas84** [comment]
Hello @WPLibrary 

Yes, I've responded to that topic and we are waiting for more details so we can determine what might be causing this. And the difference is that the issue on the mentioned topic is on Chrome and in your case is Safari.
Thank you for taking the time and posting all the details. We'll let you know if there is any progress on this.
Thank you!

**Comment by WPLibrary** [comment]
@mavas84 When the issue has occurred it was on Chrome.
https://wordpress.org/support/topic/lazy-load-bug/

Thanks!

**Comment by mavas84** [comment]
Hello @WPLibrary 
Sorry for the late reply. I've tested this again and I was using MAC and PC, tested on Chrome, Firefox, Edge, IE, Safari and I am not seeing any issue.
Can you please drop us a note via the plugin in Performance>Support so we can try to replicate this.
Thank you!

**Comment by WPLibrary** [comment]
@mavas84 Thank you again, Marko. I will. 👍

**Comment by mavas84** [comment]
Hello @WPLibrary 

We haven't received an email from you regarding this.
Please drop us a note when convenient.
Thanks!
