### ISSUE TITLE
Usage Tracking is not GDPR compliant

### ISSUE THREAD

**Issue by romainmenke** [W3EDGE/w3-total-cache#169]
https://github.com/W3EDGE/w3-total-cache/blob/fe8b3c5f8a25c23e4773c3bbc135272eb1e2073c/Generic_Plugin_Admin.php#L293

Tracking usage this way is not ok and should be removed.
If you insist on tracking usage you should consult your legal department to make this GDPR compliant.

**Comment by bwmarkle** [comment]
Hi @romainmenke thanks for creating this issue and bringing this to our attention. We're going to get this removed in our next release. I took just a moment this morning to create a video to say thanks!

https://youtu.be/0kqIr46SfbA
[![Video](https://img.youtube.com/vi/0kqIr46SfbA/0.jpg)](https://www.youtube.com/watch?v=0kqIr46SfbA)

**Comment by romainmenke** [comment]
Thank you for the quick and positive response! Looking forward to the next update :)
