### ISSUE TITLE
edit link

### ISSUE THREAD

**Issue by sajjad-021** [W3EDGE/w3-total-cache#17]
in wiki and memcached position,
https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-Installation:-Memcached-Server#install-libevent

the download link has been change to:
https://github.com/libevent/libevent/releases/download/release-2.1.10-stable/libevent-2.1.10-stable.tar.gz

**Comment by maxicus** [comment]
Thanks for update.
Changed.
