### ISSUE TITLE
Disable jquery-migrate

### ISSUE THREAD

**Issue by WPLibrary** [W3EDGE/w3-total-cache#172]
**Reasons**
- Most up-to-date frontend code and plugins don’t require **jquery-migrate.min.js** anymore.
- Removing jquery-migrate from the frontend, it will make the mobile speed faster.

I always use the below snippet to remove the jquery-migrate from my websites:

```
function remove_jquery_migrate($scripts)
{
    if (!is_admin() && isset($scripts->registered['jquery'])) {
        $script = $scripts->registered['jquery'];
        
        if ($script->deps) { // Check whether the script has any dependencies
            $script->deps = array_diff($script->deps, array(
                'jquery-migrate'
            ));
        }
    }
}
add_action('wp_default_scripts', 'remove_jquery_migrate');
```

Please consider adding an option to disable loading jquery-migrate (like wp-emoji, wp-embed) :)

Regards.

**Comment by martijn19811** [comment]
That's a very good suggestion. I was about to recommend the same.
