### ISSUE TITLE
Trying to access array offset on value of type null multisite issue

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#177]
PHP notice Trying to access array offset on the value of type null
on line 187 in
wp-content/plugins/w3-total-cache/Util_Environment.php
Possible typo in the code.
After blogs.php is deleted the issue goes away until it's created again.
Reference topic: https://wordpress.org/support/topic/trying-to-access-array-offset-on-value-of-type-null-2-2/

**Comment by maxicus** [comment]
fuxed by https://github.com/W3EDGE/w3-total-cache/commit/ff85efb5e841505ee16582993d8b74bae456de14
