### ISSUE TITLE
USing WP-CLI on multisite: Warning: Some code is trying to do a URL redirect

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#182]
Executing wp-cli code is throwing the following error:
```Warning: Some code is trying to do a URL redirect. Backtrace:
#0  WP_CLI\Utils\wp_redirect_handler(/?repeat=w3tc) called at [/wordpress/wp-includes/class-wp-hook.php:290]
#1  WP_Hook->apply_filters(/?repeat=w3tc, Array ([0] => /?repeat=w3tc,[1] => 302)) called at [/wordpress/wp-includes/plugin.php:206]
#2  apply_filters(wp_redirect, /?repeat=w3tc, 302) called at [/wordpress/wp-includes/pluggable.php:1230]
#3  wp_redirect(/?repeat=w3tc, 302, WordPress) called at [/wordpress/wp-includes/pluggable.php:1373]
#4  wp_safe_redirect(/?repeat=w3tc, 302) called at [/wordpress/wp-content/plugins/w3-total-cache/Util_Environment.php:1021]
#5  W3TC\Util_Environment::safe_redirect_temp(/?repeat=w3tc) called at [/wordpress/wp-content/plugins/w3-total-cache/Generic_Plugin.php:208]
#6  W3TC\Generic_Plugin->init() called at [/wordpress/wp-includes/class-wp-hook.php:288]
#7  WP_Hook->apply_filters(, Array ([0] => )) called at [/wordpress/wp-includes/class-wp-hook.php:312]
#8  WP_Hook->do_action(Array ([0] => )) called at [/wordpress/wp-includes/plugin.php:478]
#9  do_action(init) called at [/wordpress/wp-settings.php:523]
#10 require(/wordpress/wp-settings.php) called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1237]
#11 WP_CLI\Runner->load_wordpress() called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1158]
#12 WP_CLI\Runner->start() called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:23]
#13 WP_CLI\Bootstrap\LaunchRunner->process(WP_CLI\Bootstrap\BootstrapState Object ([WP_CLI\Bootstrap\BootstrapStatestate] => Array ())) called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:74]
#14 WP_CLI\bootstrap() called at [phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27]
#15 include(phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php) called at [phar:///usr/local/bin/wp/php/boot-phar.php:11]
#16 include(phar:///usr/local/bin/wp/php/boot-phar.php) called at [/usr/local/bin/wp:4]```

Reference topic: https://wordpress.org/support/topic/wp-cli-some-code-is-trying-to-do-a-url-redirect/

**Comment by GermanKrutov** [comment]
Do you have any information for us?

**Comment by bwmarkle** [comment]
Hi @GermanKrutov I meet with the developers today. I'll bring this ticket up and we'll get back to you soon. Thanks!

**Comment by GermanKrutov** [comment]
Any updates?

**Comment by Orrison** [comment]
Hey folks,

My company also uses W3TC in our multi-site and gets this error every now and then when making a call with WP-CLI. Just as the poster talked about in this original post: https://wordpress.org/support/topic/wp-cli-some-code-is-trying-to-do-a-url-redirect/

Is this a bug that is planned to be fixed soon? It is very annoying and hacky to have to run a command twice to get past this bug and sometimes it comes up at random times again causing my code to fail if I didn't expect it to happen at that time requiring a double command run.

Would really appreciate a fix on this one.

**Comment by GermanKrutov** [comment]
Hey @Orrison I have opened this ticket.

Hey people, do you have any updates for us? There are already 2 cases.

**Comment by bwmarkle** [comment]
Hi @GermanKrutov and @Orrison,

I'm sorry we didn't handle this issue as well as we should have. It looks like I dropped the ball on it quite some time ago.

I reached out to the team, and after some review, it looks like we can begin working on this one now. More info coming soon...

Thanks,
- Brad

**Comment by Orrison** [comment]
@bwmarkle awesome, thank you so much!

**Comment by cssjoe** [comment]
We just published a release candidate including a fix for this issue.  Please test version 0.14.2-rc.1 https://downloads.wordpress.org/plugin/w3-total-cache.0.14.2-rc.1.zip and let us know if it solves the issue.  Thank you!

**Comment by Orrison** [comment]
Hey @cssjoe with some testing as far as I can tell this has resolved the issue! Thank you very much!

**Comment by GermanKrutov** [comment]
Thanks!
