### ISSUE TITLE
Incorrect CSS minification for inline SVGs

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#183]
when minifying CSS and using inline SVGs as data images if any hash(#) symbol exists, it will be prepended with theme path,
`url(#linearGradient-1`) converts to `url(/wp-content/themes/levelup/#linearGradient-1)`
Reference topic: https://wordpress.org/support/topic/incorrect-css-minification-for-inline-svgs/

**Comment by cssjoe** [comment]
Waiting in QA testing.
```--- a/lib/Minify/Minify/CSS/UriRewriter.php
+++ b/lib/Minify/Minify/CSS/UriRewriter.php
@@ -380,11 +380,11 @@ class Minify_CSS_UriRewriter {
             && '/' !== substr($uri, 0, 1)    // root-relative
             && false === strpos($uri, '//')  // protocol (non-data)
             && 0 !== strpos($uri, 'data:')   // data protocol
+            && 0 !== strpos( $uri, '%' )     // URL-encoded entity.
```
