### ISSUE TITLE
Minify cache not correctly cleared with cli

### ISSUE THREAD

**Issue by Respheal** [W3EDGE/w3-total-cache#188]
WordPress and W3 Total Cache were freshly installed via Ansible with the default twentytwenty theme. After installing, the following commands were run to configure W3TC:

```
wp w3-total-cache option set minify.auto "true" --type="boolean"
wp w3-total-cache option set minify.css.enable "true" --type="boolean"
wp w3-total-cache option set minify.css.engine "css" --type="string"
wp w3-total-cache option set minify.css.strip.comments "true" --type="boolean"
wp w3-total-cache option set minify.css.strip.crlf "true" --type="boolean"
wp w3-total-cache option set minify.enabled "true" --type="boolean"
wp w3-total-cache option set minify.error.notification "admin" --type="string"
wp w3-total-cache option set minify.html.enable "true" --type="boolean"
wp w3-total-cache option set minify.html.engine "html" --type="string"
wp w3-total-cache option set minify.html.strip.crlf "true" --type="boolean"
wp w3-total-cache option set settminify.js.enable "true" --type="boolean"
wp w3-total-cache option set minify.js.engine "js" --type="string"
```
Resulting master.php: [https://pastebin.com/y0nuMygS](https://pastebin.com/y0nuMygS)

On load, the site has no CSS and throws these errors:
```
[domain]/wp-content/cache/minify/37929.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
[domain]/wp-content/cache/minify/01330.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
[domain]/wp-content/cache/minify/a3f7d.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
[domain]/wp-content/cache/minify/0e457.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
[domain]/wp-content/cache/minify/a3f7d.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
[domain]/wp-content/cache/minify/37929.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
[domain]/wp-content/cache/minify/01330.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Expected behavior is that one of these should have fixed the issue but they do not:
```
[wordpress@server doc_root]$ wp w3-total-cache flush minify
Success: The minify cache is flushed successfully.
[wordpress@server doc_root]$ wp w3-total-cache flush all
Success: Everything flushed successfully.
```

The errors clear upon loading the W3TC dashboard. However, this should be something that the flush tool can handle.

**Comment by mavas84** [comment]
Hello @Respheal 
Thank you for taking the time to post the issue and I am sorry about the issue you are experiencing.
What's missing here is the fix_environment command so you should run:
`wp w3-total-cache fix_environment apache`
or
`wp w3-total-cache fix_environment nginx`
Also, if Nginx is used, newly generated nginx.conf should be included in the root config, and Nginx restarted.
Thank you!

**Comment by Respheal** [comment]
Thanks for the help! Unfortunately `fix_environment apache` didn't resolve the issue. The issue happens with both Nginx and Apache but I'm currently running Apache alone to remove variables.

**Comment by maxicus** [comment]
@Respheal minify rewrites just don't work in your environment.
fix_environment may help as @mavas84 suggested, but if it doesn't - rules are not respected by apache. You should check.

Not related to purge, it may not help in misconfigured environment.

**Comment by Respheal** [comment]
@maxicus Sorry, I guess the way I phrased the issue wasn't clear. The minify rewrites do work. The problem is the cli tool does not flush the minify cache. Loading the dashboard flushes the cache successfully; the cli tool does not.

**Comment by maxicus** [comment]
@Respheal In that case please describe what the problem you have.

Right now you complain only on "Failed to load resource: the server responded with a status of 404" for minify assets, what means rewrites doesn't work.
