### ISSUE TITLE
HTML Minifier blank output (PREG_JIT_STACKLIMIT_ERROR)

### ISSUE THREAD

**Issue by ericek111** [W3EDGE/w3-total-cache#190]
We've noticed that on some rare occasions, the page rendering process fails and the server returns a blank page. After some debugging, I found the culprit.

When a (malformed?) HTML document goes through the minification process, it crashes the PCRE engine at one point and `PREG_JIT_STACKLIMIT_ERROR` (6) is set as the error code. Looks like the regular expression used to "remove trailing slash from void elements" is inefficient.

https://github.com/W3EDGE/w3-total-cache/blob/0013107b3d1c8fffe2c570ffec754960849832cf/lib/Minify/Minify/HTML.php#L159-L163

**Suggested workaround:**
If `preg_last_error() !== PREG_NO_ERROR`, simply skip the misbehaving regex and continue.
```php
<?php
$oldHtml = $this->_html;
$this->_html = preg_replace( ... );

if (preg_last_error() !== PREG_NO_ERROR) {
    $this->_html = $oldHtml;
}
```

I'm also attaching a test case. I tried to make it as minimal as possible, but even a seemingly small change to the original source code (such as removing one HTML argument from a tag) will cause the process to succeed.
[w3tc_minify_error_pcre_jit_test.txt](https://github.com/W3EDGE/w3-total-cache/files/4653839/w3tc_minify_error_pcre_jit_test.txt) _(GitHub doesn't allow PHP files.)_

Note, that the `<head>` tag contains one overflown `<meta>` tag (this happened due to insufficient escaping):
```html
    <meta name="twitter:image:alt" content="Macbook 12" a nabíječka na MacBook
    " />
```

**Comment by cssjoe** [comment]
We just published a release candidate including a fix for this issue.  Please test version 0.14.2-rc.1 https://downloads.wordpress.org/plugin/w3-total-cache.0.14.2-rc.1.zip and let us know if it solves the issue.  Thank you!

**Comment by ericek111** [comment]
The issue seems to have been resolved. We have since fixed the improper output, but the test case was failing on 0.13.2 on two separate servers and now it works fine with 0.14.2 with the applied workaround.

Thank you for the great work!
