### ISSUE TITLE
Google Page Speed dashboard widget not fetching results

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#192]
Google Page speed widget is not showing results with the notification:
`Unable to fetch Page Speed results.`
Google Page speed insights are using V5
![Annotation 2020-05-22 165340](https://user-images.githubusercontent.com/40050744/82680845-28d9d200-9c4d-11ea-853f-1d8a9292aebe.png)

**Comment by jordanhatesassassins** [comment]
Bump. Same here

**Comment by jack-blackson** [comment]
I unfortunately have the same issue

**Comment by bwmarkle** [comment]
Hi @jordanhatesassassins and @jack-blackson,

Thanks for letting us know you both are experiencing this same issue. We're going to prioritize this one, and we'll touch base soon with more info.

Thanks,
\- Brad

**Comment by cssjoe** [comment]
Deployed just now.
