### ISSUE TITLE
Media Library Import breaks all outgoing links (by importing external URLs from links even if their content-type is text/html)

### ISSUE THREAD

**Issue by caugner** [W3EDGE/w3-total-cache#209]
The Media Library Import is very useful.

However I noticed that it not only imports `<a href="...">` links, but it even imports them if the link refers to an external URL that returns `text/html`.

What is the rational behind this?

**Update**: The bug is so severe that it broke all outgoing links.

**Update 2**: Not only did it break all outgoing links, it also caused several pages to no longer work (due to custom code being removed, as if the pages were edited using the visual editor).

**Comment by mavas84** [comment]
Hello @caugner 
Thank you for taking the time to report this issue. 
When you are importing attachments into the Media Library is the checkbox "Import external media library attachments" enabled? If so Please disable that checkbox and see if the issue persists.
Thanks!

**Comment by caugner** [comment]
@mavas84 Thank you for your answer.

Wouldn't disabling that checkbox also prevent external images from being imported?

**Comment by mavas84** [comment]
Hello @caugner 
Just to confirm, you are using the media library to link URLs and not just images? Can you please share an example of the URL you are using and some screenshots, also the CDN provider you are using.
Have you tried adding those types of files to Rejected files:?
Thanks!

**Comment by caugner** [comment]
> Have you tried adding those types of files to Rejected files:?

If I understand this correctly, I should add `text/html` to the `Rejected files` setting?

**Comment by mavas84** [comment]
Hello @caugner 
Thank you for the information. Let me check this and I'll get back to you as soon as I have more info.
Thanks!

**Comment by mavas84** [comment]
Hello @caugner 
Thank you for your patience. You can use the File types to import: filed in Performance>CDN>Advanced. That option controls which URLs will be imported.  So you have to adjust it to match only assets you want to import.
I hope this helps.
Thank you!
