### ISSUE TITLE
PHP Notice: Undefined variable in LAxy Load Mutator module

### ISSUE THREAD

**Issue by RT-PDX** [W3EDGE/w3-total-cache#217]
Hi there,

This seems an easy fix for a -what is seems type - but causing an annoying PHP notice " Undefined variable: m2 " in wp-content/plugins/w3-total-cache/UserExperience_LazyLoad_Mutator.php line 135

$m2 is not defined and should should be $m[2]

Thanks

**Comment by mavas84** [comment]
Hello @RT-PDX 
Thank you for taking the time to report the issue.
We are checking this and we'll get back to you as soon as we investigate.
Thanks!
