### ISSUE TITLE
v0.9.7.5 Uses S3 URL instead of CloudFront URL when requesting static files from CDN

### ISSUE THREAD

**Issue by vlence** [W3EDGE/w3-total-cache#22]
We are running multiple WordPress websites and offload static assets to S3.

We do not allow public read/write access to S3 and allow only CloudFront to request objects from the S3 bucket using an OAI.

In v0.9.7.5 W3TC requests objects from S3 directly instead of using the CloudFront URL.

For example if the website has a stylesheet at `wp-content/themes/my-theme/css/styles.css` it will be loaded as `https://s3.amazonaws.com/my-bucket/wp-content/themes/my-theme/css/styles.css` instead of `https://abcd1234.cloudfront.net/wp-content/themes/my-theme/css/styles.css`.

I believe this is incorrect behavior.

v0.9.7.4 behaves correctly however, and uses the CloudFront URL to request static assets.

**Comment by maxicus** [comment]
Was reported similar issue, when CloudFront+S3 CDN is used but S3 urls were placed instead when CNAME is not used.

please check if https://github.com/W3EDGE/w3-total-cache/commit/c5aeabd74ff9899139bb16cbb314377b1a040229 fixes that.
