### ISSUE TITLE
Disable static asset requests logging

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#220]
Add the ability to disable static asset requests logging.
All requests of image, CSS, and JS are logged in the web server logs which is not necessary sometimes. For nginx, adding “access_log off;” would prevent that.
Reference topic: https://wordpress.org/support/topic/disable-static-asset-requests-logging/

**Comment by WPLibrary** [comment]
Hi @mavas84 

I have already requested that thanks to you: https://github.com/W3EDGE/w3-total-cache/issues/126

**Comment by mavas84** [comment]
Hello @WPLibrary 
Thank you very much for this.
Closing this issue as a duplicate: https://github.com/W3EDGE/w3-total-cache/issues/126
