### ISSUE TITLE
AVIF image headers

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [W3EDGE/w3-total-cache#229]
Chrome Beta has [shipped ](https://blog.chromium.org/2020/07/chrome-85-upload-streaming-human.html)support for AVIF files. 

However in htaccess, W3TC needs to add headers for avif, just like for webp files.

**Comment by mavas84** [comment]
Hello @vijayaraghavanramanan 
First of all, thank you for taking the time to make this suggestion. 
We are already researching this and we'll make sure to implement this in future releases.
Thank you once again!
