### ISSUE TITLE
Upgrading to PRO and cache method in cluster

### ISSUE THREAD

**Issue by Mecanik** [W3EDGE/w3-total-cache#23]
Hello, I have 2 questions for you guys if it's ok.

1. Why would someone "upgrade" to "pro" when the whole source code is on github ?

2. I have a cluster setup, where all the wordpress installs are syncronised across each server and database too. Which cache method do you recommend to use ? I was thinking about memcached/redis - but I'm not sure if I should specify all servers ? I tested APCU/disk and it's not working correctly or at least how I expect it.

Thank you

**Comment by maxicus** [comment]
See
https://github.com/W3EDGE/w3-total-cache/blob/master/README.md#support

> This repository is not suitable for support. Please don't use our issue tracker for support requests.Support can take place through the appropriate channels:
> 
> The support form can be found in Performance -> Support page of your wp-admin.
> Our community forum on wp.org.
> 
> Support requests in issues on this repository will be closed on sight.
