### ISSUE TITLE
Call to undefined function W3TC\\request_filesystem_credentials()

### ISSUE THREAD

**Issue by 8ctopus** [W3EDGE/w3-total-cache#231]
W3 total cache 0.14.2
Operating System: Ubuntu 18.04.4 LTS
Apache: 2.4.29
php: 7.2.24-0ubuntu0.18.04.6 FPM/FastCGI

```
Uncaught Error: Call to undefined function W3TC\\request_filesystem_credentials() in /plugins/w3-total-cache/Util_WpFile.php:246 Stack trace:
#0 /plugins/w3-total-cache/Util_WpFile.php(21): W3TC\\Util_WpFile::request_filesystem_credentials()
#1 /plugins/w3-total-cache/Util_Rule.php(306): W3TC\\Util_WpFile::write_to_file('/srv/jp/wordpre...', '# secure wordpr...')
#2 /plugins/w3-total-cache/PgCache_Environment.php(416): W3TC\\Util_Rule::add_rules(Object(W3TC\\Util_Environment_Exceptions), '/srv/jp/wordpre...', '# BEGIN W3TC Pa...', '# BEGIN W3TC Pa...', '# END W3TC Page...', Array, true) 
#3 /plugins/w3-total-cache/PgCache_Environment.php(31): W3TC\\PgCache_Environment->rules_core_add(Object(W3TC\\Config), Object(W3TC\\Util_Environment_Exceptions)) 
#4 /plugins/w3-total-cache/PgCache_ContentGrabber.php(1157): W3TC\\PgCache_Environment->fix...

```
The problem occurs in Util_WpFile.php when the .htaccess file is not writable (in my case because it is not owned by www-data)

	static public function write_to_file( $filename, $content ) {
		if ( @file_put_contents( $filename, $content ) )
			return;

		try {
			self::request_filesystem_credentials();
		} catch ( Util_WpFile_FilesystemOperationException $ex ) {
			throw new Util_WpFile_FilesystemWriteException( $ex->getMessage(),
				$ex->credentials_form(), $filename, $content );
   		}

If file_put_contents fails, then execution goes to self::request_filesystem_credentials():

	static private function request_filesystem_credentials( $method = '', $url = '', $context = false ) {
		if ( strlen( $url ) <= 0 )
			$url = $_SERVER['REQUEST_URI'];
		$url = preg_replace( "/&w3tc_note=([^&]+)/", '', $url );

		$success = true;
		ob_start();
		if ( false === ( $creds = request_filesystem_credentials( $url, $method, false, $context, array() ) ) ) {
			$success =  false;
		}

Then on line 246, the call to request_filesystem_credentials() fails. I tried changing the namespace like this but I can't figure out why it won't work.

		if ( false === ( $creds = \request_filesystem_credentials( $url, $method, false, $context, array() ) ) ) {

**Comment by mavas84** [comment]
Hello @8ctopus 
Thank you for taking the time to report this.
We've been trying to replicate the issue but with no success.

> The problem occurs in Util_WpFile.php when the .htaccess file is not writable (in my case because it is not owned by www-data)

Can you please confirm that you are not experiencing the issue if the .htaccess is writable? Do you see the notification: `FTP credentials don't allow to write to file /home/yourwebsite/public_html/.htaccess`?
So, there is a possibility that the issue is environment specific and you should share more details fur us to try and replicate the issue. Sharing the URL or the page you are experiencing the issue with may also help.
Thanks!

**Comment by 8ctopus** [comment]
> Can you please confirm that you are not experiencing the issue if the .htaccess is writable? 

Yes, I always see this issue in my apache server logs when the file is not writable. It never comes back when the file is writable.

> Do you see the notification: FTP credentials don't allow to write to file /home/yourwebsite/public_html/.htaccess?

No, I never see anything myself, but find out about it in the apache error log.

> So, there is a possibility that the issue is environment specific and you should share more details fur us to try and replicate the issue. 

It definitely is as I imagine most people have all website content owned by the same user apache is running on which is not the case for me.

> Sharing the URL or the page you are experiencing the issue with may also help.

It's not related to any page I visit.

**Comment by 8ctopus** [comment]
Where's how it looks further up the call stack:

```
#0 /srv/fr/wordpress/web/app/plugins/w3-total-cache/Util_Rule.php(306): W3TC\Util_WpFile::write_to_file('/srv/fr/wordpre...', '# secure wordpr...')
#1 /srv/fr/wordpress/web/app/plugins/w3-total-cache/PgCache_Environment.php(416): W3TC\Util_Rule::add_rules(Object(W3TC\Util_Environment_Exceptions), '/srv/fr/wordpre...', '# BEGIN W3TC Pa...', '# BEGIN W3TC Pa...', '# END W3TC Page...', Array, true)
#2 /srv/fr/wordpress/web/app/plugins/w3-total-cache/PgCache_Environment.php(31): W3TC\PgCache_Environment->rules_core_add(Object(W3TC\Config), Object(W3TC\Util_Environment_Exceptions))
#3 /srv/fr/wordpress/web/app/plugins/w3-total-cache/PgCache_ContentGrabber.php(1157): W3TC\PgCache_Environment->fix_on_wpadmin_request(Object(W3TC\Config), true)
#4 [internal function]: W3TC\PgCache_ContentGrabber->_check_rules_present()
#5 {main}
```

_check_rules_present() is called in PgCache_ContentGrabber.php:

		if ( $this->_enhanced_mode && !$this->_late_init ) {
			register_shutdown_function( array(
					$this,
					'_check_rules_present'
				) );

			if ( isset( $response_headers['kv']['Content-Type'] ) ) {
				$content_type = $response_headers['kv']['Content-Type'];
			}
		}

If I comment register_shutdown_function, it removes the error.

**Comment by mavas84** [comment]
Hello @8ctopus 

Thank you for the information.
You can try adding this `require_once ABSPATH . 'wp-admin/includes/file.php';` in wp-content/plugins/w3-total-cache/Util_WpFile.php#L243 and see if the issue persists.
There must be some point in a page-load that did not include that required file but again we were not able to replicate this.
Thanks!

**Comment by 8ctopus** [comment]
@mavas84 

I tried your solution but it fails:

```
PHP Fatal error:  Uncaught Error: Call to undefined function submit_button() in /srv/es/wordpress/web/wp/wp-admin/includes/file.php:2232

Stack trace:
#0 /srv/es/wordpress/web/app/plugins/w3-total-cache/Util_WpFile.php(247): request_filesystem_credentials('/collansmanag...', 'ftpext', false, false, Array)
#1 /srv/es/wordpress/web/app/plugins/w3-total-cache/Util_WpFile.php(21): W3TC\\Util_WpFile::request_filesystem_credentials()
#2 /srv/es/wordpress/web/app/plugins/w3-total-cache/Util_Rule.php(306): W3TC\\Util_WpFile::write_to_file('/srv/es/wordpre...', '# secure wordpr...')
#3 /srv/es/wordpress/web/app/plugins/w3-total-cache/PgCache_Environment.php(416): W3TC\\Util_Rule::add_rules(Object(W3TC\\Util_Environment_Exceptions), '/srv/es/wordpre...', '# BEGIN W3TC Pa...', '# BEGIN W3TC Pa...', '# END W3TC Page...', Array, true)
#4 /srv/es/wordpress/web/app/plugins/w3-total-cache/PgCache_Environment.php(31): W3TC\\PgCache_Environment->rules_core_add(Object(W3TC\\Config), Object(W3TC\\Util_Environment_Exce...
'
```

**Comment by mavas84** [comment]
Hello @cssjoe 

You  tried including the file, but it appears another is needed: `wp-admin/includes/template.php`
Please check the following https://developer.wordpress.org/reference/functions/request_filesystem_credentials/#related
There are a bunch of files that need to be available.  Most of them should already be loaded, but if not, the user may see an error.
I hope this helps!

**Comment by mavas84** [comment]
@8ctopus Please check the reply.
Thanks!

**Comment by 8ctopus** [comment]
@mavas84 Thank you for your help, adding both includes did the trick.

**Comment by mavas84** [comment]
Hello @8ctopus 
You are most welcome. Glad to know the issue is resolved.
We would really appreciate it if you could take a minute and post a review <a href="https://wordpress.org/support/plugin/w3-total-cache/reviews/" rel="noopener" target="_blank">here</a>. This will help us to continue offering a top-notch product to users.
Thanks!

**Comment by 8ctopus** [comment]
@mavas84 are you planning on adding a fix for this issue to w3tc?

**Comment by mavas84** [comment]
Hello @8ctopus 
Yes, as you can see we've added the commit for this issue and it will be fixed in future releases.
Thanks!
