### ISSUE TITLE
Insert new line before injecting to Apache Config

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#24]
When custom .htaccess  is used with no trailing line, the configuration injected by W3TC will produce a corrupt .htaccess.
Reference topic => https://wordpress.org/support/topic/insert-new-line-before-injecting-to-apache-config/

**Comment by bwmarkle** [comment]
As discussed, moving out of 0.11.0 release.

**Comment by maxicus** [comment]
handed by https://github.com/W3EDGE/w3-total-cache/commit/20429ed7883fe58c76d21773c3d03e3d5b049856
