### ISSUE TITLE
Caching of sitemap in Wordpress 5.5

### ISSUE THREAD

**Issue by superpoincare** [W3EDGE/w3-total-cache#241]
Wordpress 5.5 has native sitemaps. 

However, the sitemap page isn't getting cached. 

I am using disk-enhance and in the directory, I see other pages, but not this page.

**Comment by mavas84** [comment]
Hello @vijayaraghavanramanan 

Thank you for taking the time to post this issue. This is a new feature introduced in WP 5.5. We need to test this and we'll get back to you once the testing is done.
Thanks!

**Comment by vijayaraghavanramanan** [comment]
Worth keeping in mind that Wordpress redirects `/sitemap.xml `to `/wp-sitemap.xml `so the former shouldn't be cached.

**Comment by archon810** [comment]
Any updates?

**Comment by superpoincare** [comment]
Hi @mavas84,

I think it's not fixed for Apache. It does the caching but headers need to be added. 

Have commented in this thread too: https://github.com/W3EDGE/w3-total-cache/pull/416
