### ISSUE TITLE
Fatal Error: Check for AWS Library before Loading

### ISSUE THREAD

**Issue by jessecowens** [W3EDGE/w3-total-cache#247]
**Describe the issue**
In [certain use-cases](https://github.com/humanmade/S3-Uploads/issues/328) with [other plugins](https://www.boldgrid.com/support/question/php-fatal-error-with-aws-sdk/) that use the AWS Libraries, a fatal error is caused by W3 including the AWS library without checking if it has already been loaded
```
PHP Fatal error: Cannot redeclare Aws\parse_ini_file() (previously declared in /var/www/[redacted]/wordpress/wp-content/plugins/backwpup/vendor/aws/aws-sdk-php/src/functions.php:401) in /var/www/[redacted]/wordpress/wp-content/plugins/w3-total-cache/lib/Aws/Aws/functions.php on line 401
```
**Describe the solution you'd like**
If possible, W3TC should only load libraries if they haven't already been loaded by checking `if ( !class_exists() )` or another method of detecting if the libraries have already been loaded.

**Describe alternatives you've considered**
The constant W3TC_SKIPLIB_AWS can be defined as true in wp-config, but the plugin should be able to prevent this fatal error from occurring without asking users to modify wp-config.php.

**Comment by cssjoe** [comment]
Since users can add a definition `W3TC_SKIPLIB_AWS` to `wp-config.php` to skip loading the AWS files, we'll skip this fix for now.  If other reports come in then we can reexamine the issue.
