### ISSUE TITLE
Debug mode testing

### ISSUE THREAD

**Issue by superian** [W3EDGE/w3-total-cache#249]
Possibly related to using php-fpm rather than mod_php...

If I set debug mode on for minify, I get an error message (and no obvious info in the source of pages on the site when looked at in another browser)

```
.htaccess file contains rules to rewrite url https://example.com/wp-content/cache/minify/1185555218w3tc_rewrite_test.css. If handled by plugin, it returns "Minify OK" message.
The plugin made a request to https://example.com/wp-content/cache/minify/1185555218w3tc_rewrite_test.css but received:
stream_socket_client(): unable to connect to ssl://example.com:443 (Connection timed out)
instead of "Minify OK" response. 
```

However, If I load that URL in a browser, I get "Minify OK".

Also interestingly, /.htaccess has the 'W3TC Browser Cache' and 'W3TC Page Cache core' sections, but the latter doesn't have anything obvious to do this redirect, and neither does /wp-content/cache/minify/.htaccess - where should it be?

**Comment by mavas84** [comment]
Hello @superian 
I am sorry about the issue you are experiencing and I am happy to assist you with this.
Can you please share the screenshot of the mentioned debug orshare the debug?
Also, Can you please verify if you have some console errors related to the minified files like 404 and confirm if the files are created in wp-content/cache/minify/?
Thanks!
