### ISSUE TITLE
Caching with different cookie states

### ISSUE THREAD

**Issue by markusdittrich** [W3EDGE/w3-total-cache#25]
Suppose the following scenario:

A GDPR-Cookie Plugin uses a cookie to determine whether the user gave consent to the use of cookies AND to which degree he or she did so. The state of the cookie may vary between

`{"strict":"1","thirdparty":"0","advanced":"0"}`
`{"strict":"1","thirdparty":"1","advanced":"0"}`
`{"strict":"1","thirdparty":"1","advanced":"1"}`

or not being set at all.

Depending on that state, the plugin allows for the use of hooks in a given Wordpress-template to conditionally load content that uses cookies (e.g. a google-maps iframe). For example:
```
if ( gdpr_cookie_is_accepted( 'thirdparty' ) ) {
    // Here goes the code that echoes the google maps iframe
}
```

I know that it's possible with W3 Total Cache to create a unique cache of a page depending on whether a cookie is set or not by using cookie groups. While this works fine and as expected I fail to set it up in a way that creates a unique cache of a page for each state that cookie may have (so one version of a page where strict cookies are allowed, one where strict cookies _and_ 3rd-party cookies are allowed and so on)

Is it possible to do something like that?

**Comment by gidomanders** [comment]
See
https://github.com/W3EDGE/w3-total-cache/blob/master/README.md#support

> This repository is not suitable for support. Please don't use our issue tracker for support requests.Support can take place through the appropriate channels:
> 
> The support form can be found in Performance -> Support page of your wp-admin.
> Our community forum on wp.org.
> 
> Support requests in issues on this repository will be closed on sight.
