### ISSUE TITLE
object-cache.php not created when activating plugin via wp-cli

### ISSUE THREAD

**Issue by sebcode** [W3EDGE/w3-total-cache#251]
Tested with a vanilla wordpress (5.5) installation with w3-total-cache (0.14.4) installed as only plugin.

Steps to reproduce:
- Activate w3-total-cache plugin and activate object cache via wp-admin/w3tc-settings
- Check if object-cache.php exists

        $ ls -l wp-content/object-cache.php
        -rw-r--r-- 1 www-data www-data 4517 Aug 25 10:19 wp-content/object-cache.php

- Deactivate plugin

        $ wp plugin deactivate w3-total-cache
        Plugin 'w3-total-cache' deactivated.
        Success: Deactivated 1 of 1 plugins.

- Check if object-cache.php exists

        $ ls -l wp-content/object-cache.php
        ls: cannot access 'wp-content/object-cache.php': No such file or directory

- Activate plugin

        $ wp plugin activate w3-total-cache
        Plugin 'w3-total-cache' activated.
        Success: Activated 1 of 1 plugins.

- Check if object-cache.php exists

        $ ls -l wp-content/object-cache.php
        ls: cannot access 'wp-content/object-cache.php': No such file or directory

Actual behavior: after activating the plugin via wp-cli the object cache is not working because `object-cache.php` is missing. To create the file, I have to manually click "Save settings" in wp-admin/w3tc-settings.
Expected: `object-cache.php` should be created after re-activating the plugin.

**Comment by mavas84** [comment]
Hello @sebcode 

Thank you for taking the time to post this.
We'll investigate this and try to replicate and we'll get back to you on this.
Thanks!

**Comment by mavas84** [comment]
Hello @sebcode 
activation was supposed to be wp-admin-only operation and didn't call full
environment update since the wp-admin request was doing it right after UI
plugin activation.

but its possible to activate via wp-cli now too. This will be added in the next release.
Thanks!
