### ISSUE TITLE
Inconsistent object caching behaviour in console mode (breaks woocommerce db update)

### ISSUE THREAD

**Issue by sebcode** [W3EDGE/w3-total-cache#252]
Tested with a vanilla wordpress (5.5) installation with w3-total-cache (0.14.4) installed as the only plugin.
w3-total-cache is configured with "Object Cache: enabled" and "Object Cache method: Disk". Every other w3tc option disabled.

The issue is that after an option has been deleted via `delete_option` it is still accessible via `get_option`. This is only an issue on the command line (PHP_SAPI=cli), not in the context of the webserver. Example:

I have the following Test-script in my htdocs-root:
```
<?php require_once(__DIR__.'/wp-load.php');
echo "add:" . var_export(update_option('testkey', '123'), 1);
echo " del:" . var_export(delete_option('testkey'), 1);
echo " get:" . var_export(get_option('testkey'), 1)."\n";
```

In the context of the webserver, everything's fine:
```
$ curl http://localhost/test.php
add:true del:true get:false
```

However when I run this script via the command line, the last call to `get_option` doesn't return `false`:
```
$ php test.php
add:true del:true get:'123'
```

If I disable w3tc, the output of the script matches the expected output (i.e. `get false`).

This is what currently breaks `wp wc update` which is used to upgrade the woocommerce database. Calling this command multiple times runs the old db upgrades every time.
```
$ wp wc update
Found 81 updates (wc_update_200_file_paths, wc_update_200_permalinks, ...)
Updating database  100% Success: 81 update functions completed. Database version is
$ wp wc update
Found 81 updates (wc_update_200_file_paths, wc_update_200_permalinks, ...)
Updating database  100% Success: 81 update functions completed. Database version is
$ wp wc update
Found 81 updates (wc_update_200_file_paths, wc_update_200_permalinks, ...)
Updating database  100% Success: 81 update functions completed. Database version is 3.9.0
```

So w3tc needs to be deactivated, then it works:

```
$ wp plugin deactivate w3-total-cache
Plugin 'w3-total-cache' deactivated.
Success: Deactivated 1 of 1 plugins.
$ wp wc update
Found 81 updates (wc_update_200_file_paths, wc_update_200_permalinks, ...)
Updating database  100% Success: 81 update functions completed. Database version is 4.4.0
$ wp wc update
Success: No updates required. Database version is 4.4.1
```

Workaround: Modify `object-cache.php` and wrap everything in a `if (PHP_SAPI !== 'cli') { ... }` statement.

**Comment by mavas84** [comment]
Hello @sebcode 

Thank you for taking the time to post this.
We'll investigate this and try to replicate and we'll get back to you on this.
Thanks!

**Comment by mavas84** [comment]
Hello @sebcode 
Thank you for your patience. We are still checking and testing this to make sure everything works and we are trying different possibilities.
Once again, thank you for your patience.

**Comment by metiseducation** [comment]
The reason the values are not equal in console mode is because the value of $_SERVER['HTTP_HOST'] is empty.
This causes the object keys to be different between web and console-mode, thus the values are cached in separate keys.

I have sent a pull-request that will resolve this issue here: #324 
I propose to not use the value of $_SERVER['HTTP_HOST'] as part of the cache key, instead we use the wordpress option value 'siteurl', this way they will always be equal between web and console.

**Comment by mavas84** [comment]
Control via config Cacheability in console mode should be optional for OC:
` if ( PHP_SAPI === 'cli' ) {
        $this->cache_reject_reason = 'Console mode';

        return false;
    }`
  
Reference topic: https://wordpress.org/support/topic/wp-cli-transient-set-doesnt-work-with-w3-total-cache-enabled/
