### ISSUE TITLE
HSTS headers

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [W3EDGE/w3-total-cache#257]
HSTS headers needs an "always set" for Strict-Transport-Policy instead of "set" in htaccess rules, so that it's not missed on redirect from http to https. 

Also, hstspreload.org which is the official site, complains about enabling it on non-https connections.

**Comment by mavas84** [comment]
Hello @vijayaraghavanramanan 

Thank you for taking the time to suggest this.
The developers will look into this and we'll get back to you as soon as we investigate.
Thanks!
