### ISSUE TITLE
Minified filenames

### ISSUE THREAD

**Issue by emaia** [W3EDGE/w3-total-cache#26]
I'm using W3TC 0.9.7.5 with WP 5.2.2 and the minified filenames always are created with the same filename even after purge all caches. The button "update media query string" is always disabled. This happen in Apache and Nginx. How can I fix this? I need to purge browser cache for css files...

**Comment by mavas84** [comment]
Please see
https://github.com/W3EDGE/w3-total-cache/blob/master/README.md#support
