### ISSUE TITLE
AMP Validation Error

### ISSUE THREAD

**Issue by ThatStevensGuy** [W3EDGE/w3-total-cache#260]
W3TC leaves javascript from the admin bar menu on AMP pages. This triggers a validation error when you publish your post.

**WordPress 5.5**
**AMP 2.0.0**
**W3 Total Cache 0.14.4**

**Core**
wp-includes
wp_print_head_scripts()
amp_post_template_head (priority 10)
script-loader.php:1947

**Plugin**
W3 Total Cache (w3-total-cache)
W3TC\Generic_Plugin::popup_script()
wp_print_scripts (priority 10)
Generic_Plugin.php:641

**Comment by mavas84** [comment]
Hello @ThatStevensGuy 

I am sorry about the issue you are experiencing with the AMP validation and I am happy to assist you with this.
Can you please confirm if you enabled the AMP extension in **Performance>Extensions** and if so make sure that propper `AMP URL Type:` is selected.
Thanks!

**Comment by ThatStevensGuy** [comment]
@mavas84 Yes I have the AMP extension installed for W3 Total Cache and have selected 'tag', because the frontend of the site uses /amp/.

It appears that when AMP plugin verifies if a page is valid, it uses the query string version ?amp. There is no setting in the AMP plugin to change this preference, that I can find.

The latest AMP version enables the admin bar on AMP pages so you can preview a post and then head back to the admin. W3 Total Cache is adding javascript along with its menu. Which AMP is then automatically removing and flagging as an error.

**Comment by mavas84** [comment]
Hello @ThatStevensGuy 

Thank you for your patience and your explanation. Can you please share the link of the AMP plugin you are using so we can try and replicate the issue.
Thanks!

**Comment by ThatStevensGuy** [comment]
@mavas84 The official AMP plugin https://wordpress.org/plugins/amp/

I am using Reader template mode, but I doubt that makes a difference.

**Information**
AMP does not allow the use of JS <script> tags unless they are for loading AMP components, which are added automatically by the AMP plugin. For any page to be served as AMP, all invalid script tags must be removed from the page. Instead of custom or third-party JS, please consider using AMP components and functionality such as amp-bind and actions and events (as opposed to JS event handler attributes like onclick). Some custom JS can be added if encapsulated in the amp-script. Learn more about how AMP works.If all invalid markup is “removed” the page will be served as AMP. However, the impact that the removal has on the page must be assessed to determine if the result is acceptable.

If any invalid markup is “kept” then the page will not be served as AMP.

**Error code**
DISALLOWED_TAG

**Invalid markup**
<script … >

**Element attributes**
type: text/javascript

**Element name**
script

**Parent element**
head

**Text content**
151 bytes

**Sources** 

**Core**
wp-includes
wp_print_head_scripts()
amp_post_template_head (priority 10)
script-loader.php:1947

**Plugin**
W3 Total Cache (w3-total-cache)
W3TC\Generic_Plugin::popup_script()
wp_print_scripts (priority 10)
Generic_Plugin.php:641

**Comment by mavas84** [comment]
Hello @ThatStevensGuy 

Thank you for the additional information. I've spoken with the devs and I can confirm that this is a bug. 
I'll label this issue as a bug and it will be in our backlog so please make sure to track the progress of the issue.
Thanks!

**Comment by finejoeyoung** [comment]
I'm also having validation issues with amp on W3 Total Cache.

According to Google:
1. Only amp-boilerplate and amp-custom 'style' tags are allowed, and only in the document head.
2. Custom JavaScript is not allowed.
3. Disallowed attribute or attribute value present in HTML tag.

**Comment by mavas84** [comment]
Hello @ThatStevensGuy and @finejoeyoung 

Sorry for the late information about this. Just letting you know that this problem was fixed in the 2.1.9 release.
Thank you for your patience and understanding.
