### ISSUE TITLE
Add data-cfasync to javascript for cloudflare rocket loader

### ISSUE THREAD

**Issue by Mte90** [W3EDGE/w3-total-cache#261]
As written on https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-specific-JavaScripts- add that support for this attribute can help with optimizing the performance under cloudflare

**Comment by Mte90** [comment]
Looking at this function https://github.com/W3EDGE/w3-total-cache/blob/c9b6873abe334b4a5935deca4d4015a397616880/Minify_Plugin.php#L1091 rewrite the script html tag so if I am adding with wordpress hooks they are ignored.

Maybe with this filter parsing I can reinsert that attribute https://github.com/W3EDGE/w3-total-cache/blob/c9b6873abe334b4a5935deca4d4015a397616880/Minify_AutoJs.php#L316

**Comment by Mte90** [comment]
```
add_filter( 'w3tc_minify_js_step_script_to_embed', 'add_w3tc_cfsync', 9999, 1 );

function add_w3tc_cfsync( $data ) {
		$data['script_to_embed_body'] = str_replace( ' src', ' data-cfasync="false" src', $data['script_to_embed_body'] );

		return $data;
	}
```

**Comment by mavas84** [comment]
Hello @Mte90 

Thank you for taking the time to suggest this. The dev team will review this and get back to you as soon as we investigate.
In the meantime, please feel free to create a pull request and share it with us. We would appreciate your contribution.
Thanks!
