### ISSUE TITLE
Required action on activation failure

### ISSUE THREAD

**Issue by cssjoe** [W3EDGE/w3-total-cache#272]
Related to the fix for #251 and PR #255.
When there is `wp-content/advanced-cache.php` file that exists and is not from W3TC, it prevents plugin activation.
![image](https://user-images.githubusercontent.com/11447263/94190009-82f7d780-fe79-11ea-8c80-bd27c2c604a0.png)

The admin message was fixed in https://github.com/W3EDGE/w3-total-cache/commit/521a2f8318b956e09188c561223287c112e63981

The issue here is that the button link (`wp-admin/admin.php?page=w3tc_dashboard&w3tc_default_remove_add_in=pgcache&_wpnonce=<redacted>`) is for the plugin dashboard page that is not active until the plugin is activated, so the request gets a `403 Forbidden`.

There are most likely other button actions for other scenarios.  I didn't want to make a quick fix script only for activation since it would have to cover all scenarios.  There may be a simpler fix, such as changing the message to instruct the user to perform required actions.

**Comment by maxicus** [comment]
env exceptions should be silenced during activation, since shown afterwards at backend pages.
