### ISSUE TITLE
Testing CloudFront over S3

### ISSUE THREAD

**Issue by jpb10** [W3EDGE/w3-total-cache#28]
Testing CloudFront over S3 only checks the first distribution (index 0):

[CdnEngine_CloudFront.php](https://github.com/W3EDGE/w3-total-cache/blob/c5aeabd74ff9899139bb16cbb314377b1a040229/CdnEngine_CloudFront.php) (line 333)
```
private function _get_distribution( $dists = null ) {
	[...]
	$dist = false;
	$origin = $this->_get_origin();
	$items = $dists['DistributionList']['Items'];
	foreach ( $items as $dist ) {
		if ( isset( $dist['Origins']['Items'][0]['DomainName'] ) &&
			 $dist['Origins']['Items'][0]['DomainName'] == $origin ) {
			return $dist;
		}
	}
	throw new \Exception( sprintf( 'Distribution for origin "%s" not found.', $origin ) );
```

If the first distribution is not S3, then it throws the exception. 

It should check for each distribution.

**Comment by maxicus** [comment]
Fixed by https://github.com/W3EDGE/w3-total-cache/commit/1c51b710c56217c269fa1141f3e562d33a8531d3
