### ISSUE TITLE
HTML minify removes query string set in BC options

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#284]
When HTML minify is enabled (HTML minify (default)) it removes the query string added when the option “Prevent caching of objects after settings change ” enabled in Performance>Browser Cache.
/wp-content/cache/minify/1615d.js?x55666
when the minify is active:
/wp-content/cache/minify/1615d.js
If HTML tidy is selected as an HTML minifier: the query strings are not removed.
Reference topic: https://wordpress.org/support/topic/html-minify-strips-css-js-image-resources-of-querystring/

**Comment by timocouckuyt** [comment]
Thanks for adding this to GitHub, @mavas84 !

**Comment by maxicus** [comment]
duplicate of #60  which is fixed now
