### ISSUE TITLE
w3tc_minify_js_content like w3tc_minify_css_content?

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [W3EDGE/w3-total-cache#291]
There's a filter hook w3tc_minify_css_content already. 

https://github.com/W3EDGE/w3-total-cache/blob/a3abdfc1f0af56d8fa5d943bbe2c1ea9a028c63f/lib/Minify/Minify.php#L617

A feature-request to have the same for JS: can we have that too?

I discussed this here: https://wordpress.org/support/topic/modify-minify-file-contents/

**Comment by mavas84** [comment]
Hello @vijayaraghavanramanan 

Thank you for taking the time to open this ticket. As always developers will investigate this and we'll get back to you.
Thanks!
