### ISSUE TITLE
404 Not Found - Conflict with Echo KB Multiple Knowledge Base plugin

### ISSUE THREAD

**Issue by annawisniewska** [W3EDGE/w3-total-cache#306]
We are using Echo KB Multiple Knowledge Base plugin - and we currently use two KBs; one is available openly and on our main domain. The second is only available internally, and the link is maindomain.com/wiki.

After activating the W3 Total Cache plugin, the main KB is still available, but the wiki one is not; we are getting a 404 not found an error.
Internally, all is working correctly on the backend, we can still create new posts, but no way to access it from the frontend. 
Switched off W3 plugin - all is back to the norm.
Tried excluding /wiki in Browser Cache settings - no go
Tried excluding wiki in Page Cache settings - no go
Tried exception lists - no go

Nothing works besides switching off the plugin, which we would still like to use. 
Echo support says it's nothing on their side.
WordPress 5.5.3
W3 Total Plugin v0.15.2 (issue was also on v0.15.1)
PHP Version: 7.4.10;
Web Server: Apache

In compatibility Check only Network Mode: No is red.

**Comment by mavas84** [comment]
Hello @annawisniewska 

Thank you for your question and I am happy to assist you with this.
As GitHub is for reporting bugs or suggesting new features and enhancements, and this, as you stated, is a conflict with another plugin I  suggest that you use our support channel for this. Please drop us a note directly via the plugin in Performance>Support, or via our website  https://www.w3-edge.com/contact/
This way you can share more information about the issue so we can check what might be causing this and find a proper solution.
Thanks!
