### ISSUE TITLE
Redis Socket Support

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#319]
Add support to use a Redis server socket for more speed compared to the IP layer.
Reference topic:  https://wordpress.org/support/topic/redis-socket-support-3/
https://wordpress.org/support/topic/redis-socket-support-2/

**Comment by serdarwork** [comment]
Please let me know if I'm wrong but W3TC already supports Redix unix socket. I use both Redis unix socket & Memcached unix socket with W3TC on my LEMP server.

[![memcached-unix-socket7a7c584eae4f41ba.png](https://s3.imgbu.com/file/imgbucom-s/2021/02/19/memcached-unix-socket7a7c584eae4f41ba.png)](https://imgbu.com/i/SS48W)

All you need to replace the default hostname with **/var/run/redis/redis.sock** or **/var/run/redis/redis.sock:0**

Regards.

**Comment by maxicus** [comment]
@serdarwork You are right. Thanks for a note.

It's actually is a documentation-related issue.
