### ISSUE TITLE
Undefined Error message

### ISSUE THREAD

**Issue by anhducbkhn** [W3EDGE/w3-total-cache#320]
My env:

    WP: 5.5.3
    WC: 4.4.1
    PHP: 7.4.13
    W3 Total Cache: 2.0.1
    Amazon Redis: xxx.xxx.cache.amazonaws.com

wp-config.php

    define('WP_CACHE', true); // Added by W3 Total Cache
    define('W3TC_CONFIG_CACHE_ENGINE', 'redis');
    define('W3TC_CONFIG_CACHE_REDIS_SERVERS', WP_REDIS_HOST . ':6379');

Redis worked well with other caching plugin. But, when I actived plugin, this is what I got:

    Connection refusedPHP message: Connection refusedPHP message: Connection refusedPHP message: Connection refusedPHP message: Connection refusedPHP message: Connection refusedPHP message: Connection refusedPHP message: Connection refusedPHP message: Connection refusedPHP message: Connection refusedPHP

Pls help!

**Comment by mavas84** [comment]
Hello @anhducbkhn 
I am sorry for the issue you are experiencing. Since you already opened a wp.org topic for this issue, please continue the correspondence there as GitHub is not intended for the support as we have a forum and the support channel via the plugin in Performance>Support.
Thanks!
