### ISSUE TITLE
page-fragment-cache - PgCache_ContentGrabber.php(1883) : eval()'d code on line 1

### ISSUE THREAD

**Issue by tonyclemmey** [W3EDGE/w3-total-cache#322]
Hello, when following the guides below to stop menu items being cached.

https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-Developers#what-is-page-fragment-cache
https://wordpress.org/support/topic/exclude-navigation-menu/

inside wp-config.php
```
define( 'W3TC_DYNAMIC_SECURITY', 'mysecurestring' );
```

inside header.php template
```
<!-- mfunc mysecurestring -->
     // place a main menu here
 <!-- /mfunc mysecurestring -->
```

I get the following error. If I remove "mfunc mysecurestring" tag error is gone.

w3-total-cache/PgCache_ContentGrabber.php(1883) : eval()'d code on line 1
Fatal error: Exception thrown without a stack frame in Unknown on line 0

**Comment by cssjoe** [comment]
@tonyclemmey I just updated our Wiki FAQ page with more information on the feature -- https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-Developers#what-is-page-fragment-cache

I tested the feature and it does work as expected.  It sounds like you included some code that may have thrown an exception for an unregistered handler.  If you are still having an issue, then please reopen this issue and let us know what code was being added.  Please do not post anything sensitive in this public forum.

I will also post information in https://wordpress.org/support/topic/exclude-navigation-menu/
