### ISSUE TITLE
Regex for CSS and JS management.

### ISSUE THREAD

**Issue by ryanlabelle** [W3EDGE/w3-total-cache#327]
W3 is a great plugin thank you. We would like to recommend it to all our customers but we are running into a small issue. 

Elementor + W3 Total Cache

Elementor generates external css files dynamically, so post ID 1234 would generate a css file wp-content/uploads/elementor/css/post-1234.css 

How can I include this in the CSS file management area automatically or programmatically in our theme?

Thank you very much for helping.

**Comment by maxicus** [comment]
@ryanlabelle can you please describe the problem in a more detail?

As by default W3TC in Minify Auto mode just takes everything it sees in HTML so that file will by taken for minification too.
So, what and how things works other that what you expect?
Thanks.

**Comment by ryanlabelle** [comment]
Thanks for responding. Not exactly. I'm fine tuning the css and js so I can't use Auto mode. Manually entry is the only way that I've found success.

I need a way to add a css or js using regex or some sort of wild card eg: wp-content/plugins/elementor/css/* to include all css generated on a page load. Perhaps adding css files programmatically?

What's possible?

Thank you.

**Comment by mavas84** [comment]
Hello @ryanlabelle 

Thank you for your inquiry and your patience. When Manual minify is enabled, you can use the help wizard and add the suggested files one by one and in order, or you can specify the file yourself by clicking on `add a stylesheet` button in Performance>Minify>CSS in the CSS file management:
Unfortunately, using regex as you suggested in your example is not possible as that would create a bunch of issues.
thanks!
