### ISSUE TITLE
Minify help wizard empty modal

### ISSUE THREAD

**Issue by ryanlabelle** [W3EDGE/w3-total-cache#328]
Has any experienced an empty help wizard modal? 

When I go to admin.php?page=w3tc_minify and click on "Help" inside the Get minify hints using the wizard line, I get an empty modal window. 

https://share.getcloudapp.com/geu4jgzg

It says:

JavaScript:

No files found.

Cascading Style Sheets:

No files found.

**Comment by mavas84** [comment]
Hello @ryanlabelle 

I am sorry about the issue you are experiencing and I am happy to assist you with this.
I've tried to replicate the issue, however, the help wizard button activates a popup with suggested scripts to minify. So I was not able to replicate the issue.
Please make sure that the correct theme is selected in the help wizard.
When have you started to experience the issue?
Also, please in the future make sure to ask support questions via the support channel in Performance>Support or in the support forum: https://wordpress.org/support/plugin/w3-total-cache/
Thanks!

**Comment by ryanlabelle** [comment]
Thank you. 

It is on a multisite / network. Will that make a difference?

**Comment by mavas84** [comment]
Hello @

Thank you for the information. Yes, in case you enabled the "Use single configuration" option for all websites in Performance>General settings>Miscellaneous. You should disable that option and make sure to use specific settings in the General settings of the feature you want to use as in this screenshot:
[https://i.imgur.com/4bTCwnY.png](url)
Thanks!
