### ISSUE TITLE
REDIS Cache Key Salt?

### ISSUE THREAD

**Issue by chrisspiegl** [W3EDGE/w3-total-cache#331]
Hello W3 Total Cache People and Developers,

I am trying to move toward W3 Total Cache with Redis integration. However, we are running multiple sites on one Server and also just one Redis instance.

Now the problem is that the keys don't seem to be prefixed with anything and thus they conflict across the sites in the Redis instance.

Now, I have read that a few years ago apparently that the Cache Key should have been implemented but it has no effect when using the `WP_CACHE_KEY_SALT` in the `wp-config.php`.

Is there something I am missing? Or is this simply not possible with W3 Total Cache at the moment?

I hope to hear feedback and help soon. Thank you,
Chris

**Comment by mavas84** [comment]
Hello @chrisspiegl 

Thank you for your inquiry and I am happy to answer.
The use of `WP_CACHE_KEY_SALT` is for the WP Redis plugin or Digital Ocean's article https://www.digitalocean.com/community/tutorials/how-to-configure-redis-caching-to-speed-up-wordpress-on-ubuntu-14-04
The W3TC does prefix the cache keys, for example:
```
w3tc_2102698950_
w3tc_1503104363_
w3tc_589200301_
```
(edited)
6:23
When Redis-cli  is used to monitor to see the keys are being created and retrieved when using 3 different sites.
`WP_CACHE_KEY_SALT` is used in other plugins, not W3TC.
Thank you!

**Comment by chrisspiegl** [comment]
Hello @mavas84 , thank you for the clarification about `WP_CACHE_KEY_SALT` and that it's used in WP Redis.

You mention that the W3TC is using some kind of prefix but what is it? What is the prefix based on?

In my testing, the prefix was not obvious enough so I ended up using databases.
Would there be an option to introduce something like the `$table_prefix` (or similar called) variable?

Thanks again and I am looking forward to knowing a bit more about this so I can use it with confidence.

**Comment by maxicus** [comment]
@chrisspiegl To use multiple websites against single cache storage you need to assign unique instance_id's on each website. You can do it by 
```define( 'W3TC_INSTANCE_ID', number); ```
in `wp-config.php`

set `common.instance_id` key in `wp-content/w3tc-config/master.php` or via `wp-cli`

**Comment by chrisspiegl** [comment]
@maxicus Wow, thank you. That is exactly what I was looking for and could not find.
I appreciate the help and hope this thread may be found by others trying to do something similar 🌸.

**Comment by GiuseppeIuculano** [comment]
> @chrisspiegl To use multiple websites against single cache storage you need to assign unique instance_id's on each website. You can do it by
> `define( 'W3TC_INSTANCE_ID', number); `
> in `wp-config.php`
> 
> set `common.instance_id` key in `wp-content/w3tc-config/master.php` or via `wp-cli`

Thank you! Is this used also for memcached ?

**Comment by maxicus** [comment]
@GiuseppeIuculano yeah, for any cache engine.
