### ISSUE TITLE
Store Redis connection creds in the sites wp-config.php not in the master.php file

### ISSUE THREAD

**Issue by lukecav** [W3EDGE/w3-total-cache#337]
Currently, Redis connection creds will be stored in the `master.php` file inside of `/html/wp-content/w3tc-config` folder.

If Redis connection creds are being defined in the `db-config.php` file will Redis connection creds still be written into the master.php file or is that set by default?
https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-Installation:-Redis-Server

Would it be possible to support setting Redis connection creds in the site `wp-config.php` to have W3 Total Cache pull from there?

**Comment by mavas84** [comment]
Hello @lukecav 

Thank you for your inquiry and I am happy to assist you with this.
You can do this by adding it to wp-config.php for example:

```
define( 'W3TC_CONFIG_CACHE_ENGINE', 'redis');
define( 'W3TC_CONFIG_CACHE_REDIS_SERVERS', 'localhost:6379' );
define( 'W3TC_CONFIG_CACHE_REDIS_PERSISTENT', true );
define( 'W3TC_CONFIG_CACHE_REDIS_DBID', 0 );
define( 'W3TC_CONFIG_CACHE_REDIS_PASSWORD', '' );
```

Thanks!

**Comment by lukecav** [comment]
If the Redis connection creds are stored in the sites `wp-config.php` file would they still be written into the `master.php` file?

**Comment by mavas84** [comment]
Hello @lukecav 

master.php file is updated with settings saved in the admin pages, such as wp-admin/admin.php?page=w3tc_pgcache#advanced
5:50
when storing in wp-config it's the same as storing in a database. It will not be stored in master.php

**Comment by lukecav** [comment]
@mavas84 

Thanks for the info.
