### ISSUE TITLE
AMP page cache does not get cleared

### ISSUE THREAD

**Issue by archon810** [W3EDGE/w3-total-cache#34]
Hi,

We recently rolled out AMP to our site but are now running into issues with AMP pages not getting their W3TC cache cleared.

The regular non-AMP pages get their cached cleared properly upon pressing Update in a post. However, AMP pages (with `?amp` appended), do not, whether the W3TC AMP extension is activated or not.

I've looked at all the settings I can find and even tried 0.10 released today, but still AMP does not get updated. This is bad for obvious reasons.

Here's an example of a post I updated many minutes ago.

Regular page:
![image](https://user-images.githubusercontent.com/469543/64380570-20ba0380-cfe6-11e9-8fde-cc4442919622.png)

AMP page (same url with `?amp` appended):
![image](https://user-images.githubusercontent.com/469543/64380597-2e6f8900-cfe6-11e9-81f5-7c8a9765956b.png)

@maxicus Any ideas?

Thanks!

This was also cross-posted to https://wordpress.org/support/topic/amp-page-cache-does-not-get-cleared/.

**Comment by archon810** [comment]
In fact, now that I think about it, it's not just `?amp`, it's also the same page with any GET parameter appended that doesn't get its cache cleared. For example, when updating https://example.com/post, https://example.com/post?amp doesn't get cleared, but also https://example.com/post?1 or https://example.com/post?a=b, etc.

What should ideally happen is anything matching https://example.com/post* would get its cache cleared, which would include any variations of the url - otherwise they'll all get stale cache.

**Comment by maxicus** [comment]
Purging arbitrary query strings when "Cache with querystrings" enabled can't be supported by plugin.

Small amount of alternatives may be handled by hooks, but for general coverage you may use services like Varnish for that functionality.

**Comment by archon810** [comment]
So what's the solution to at least support ?amp purging @maxicus?

AMP is getting more and more popular, and right now W3TC straight up breaks cache busting for AMP sites.

Please re-open the ticket, or if you have a solution, please provide it here. I'm sure I won't be the last person to run into this issue.

**Comment by archon810** [comment]
@maxicus Related to the above, I noticed in the W3TC AMP plugin, you actually do seem to attempt to flush AMP urls, except they're hardcoded to `/amp`, which may or may not be the scheme used at any given site. As mentioned above, `/amp` is deprecated, and `?amp` should be flushed for sites that use `?amp`. Perhaps the plugin should add the ability to specify the AMP url structure to fix it?

**Comment by bwmarkle** [comment]
Hi @archon810,

We've been chatted about this issue internally, and I think we have a solution. It should be in one of our next releases.

I wrote a _mock_ blog post to kind of summarize the idea we're going with. I'll paste the image below so you can see the idea we're going with:

![image](https://user-images.githubusercontent.com/5925563/66128870-bf715a00-e5bc-11e9-96ae-c5948222912e.png)

Again, hopefully this will be out soon. Let us know what you think!

Thanks,
- Brad

**Comment by bwmarkle** [comment]
Hi @archon810,

We're getting close to releasing a minor version that resolves this issue:

> The regular non-AMP pages get their cached cleared properly upon pressing Update in a post. However, AMP pages (with ?amp appended), do not, whether the W3TC AMP extension is activated or not.

Can you share with us what WordPress plugin you're using that is using `?amp` so we can do some final testing?

Thanks
\- Brad

**Comment by archon810** [comment]
@bwmarkle As I mentioned above here https://github.com/W3EDGE/w3-total-cache/issues/34#issuecomment-530893966, we're using the official AMP WP plugin. 

https://wordpress.org/plugins/amp/
https://github.com/ampproject/amp-wp

**Comment by bwmarkle** [comment]
Hi @archon810,

W3 Total Cache 0.12.0 has been released, which includes amp purge settings. If you have have some time to test, this should resolve the issue at hand.

![image](https://user-images.githubusercontent.com/5925563/71097346-db2cdb00-217d-11ea-88a5-b0e853607d41.png)

Thanks
\- Brad

**Comment by archon810** [comment]
@bwmarkle Thanks for this. There's one small issue that is described here: https://github.com/ampproject/amphtml/issues/24326#issuecomment-528567568.

Basically, sometimes Google makes urls with `?amp` and sometimes with `?amp=` and treats those as different cache keys, so in our solution, we end up invalidating both with something like this:

```
foreach (array($amp_permalink, $amp_permalink . '=') as $link) {
            // flush w3tc cached amp pages
            if(function_exists('w3tc_flush_url')){
                w3tc_flush_url($link);
             }
```

Can W3 perhaps account for this unfortunate issue?

**Comment by archon810** [comment]
@maxicus In addition to that, we will stick with our solution, which only dumps 2 AMP urls per story, since AMP is only enabled on individual posts and not categories/tags/etc, because W3TC's AMP plugin ends up flushing cache for potentially additional 50+ pages that don't even have AMP versions, and this flushing process takes quite a bit of time and slows down post updates.

The issue is described here: https://github.com/W3EDGE/w3-total-cache/issues/44.

**Comment by maxicus** [comment]
@archon810 

https://github.com/W3EDGE/w3-total-cache/commit/df81570b96326d35f2f3c6b56f90e485173196f3 commit normalizes all ?amp=, ?amp=1 pages to a single cache key so purging of only one entry is enough.

But based on your description you have a problem at CDN level where you will have to purge all possible variants unless CDN itself supports masked purge. Not something what plugin may support unless CDN does.

You may also note that the root of the problem is querystring-based url structure which allows much more url variants to be made...

As a workaround you may consider to canonicalize urls with 301 redirects, like wp core does for some irregular urls. That may help to solve upcoming issues you will potentially have later with ?amp=2, ?amp=3 and ?amp=archon810 urls in your CDN cache :) Drawback is the redirect loop possible if CDN really creates own redirects like you describe in a ticket, but it's not how CDN's usually work (bug in cdn? bug in origin responding redirect sometimes which is later cached?).
