### ISSUE TITLE
Microsoft Azure Storage error

### ISSUE THREAD

**Issue by skip405** [W3EDGE/w3-total-cache#343]
It seems that it is no longer possible to use Microsoft Azure Storage as a CDN option using PHP7.

When adding the needed credentials the `Test Microsoft Azure Storage upload` test fails with an error 500, saying `Uncaught Error: Undefined class constant 'SDK_VERSION'`. The plugin seems to be using an old(ish) pre-PHP7 version of azure-storage-php which [has the same issue](https://github.com/Azure/azure-storage-php/issues/246) closed but the Member [comment in that thread](https://github.com/Azure/azure-storage-php/issues/246#issuecomment-662919488) says that the file in question no longer exists.

This plugin has [another Azure-related issue](https://github.com/W3EDGE/w3-total-cache/issues/282) that also suggests to update it.

**Comment by skip405** [comment]
Have done a couple of tests on a clean AMP stack with various PHP versions, and the test passes. Apparently it's not related to the PHP version.

**Comment by skip405** [comment]
After some more digging we found out that the issue is caused by the plugin conflict. One of our plugins has its own copy of azure-storage-php, so there is no issue with the plugin.

If anyone else faces this issue, investigate if you are not loading 2 versions of azure-storage-php at the same time.

**Comment by mavas84** [comment]
Hello @skip405 

Thank you for the information and I am glad that the issue is resolved. 
I would also like to thank you for the provided information regarding the conflict between the plugins.
Thanks!
