### ISSUE TITLE
Lazyload leaves images behind on my shop page

### ISSUE THREAD

**Issue by conandrum** [W3EDGE/w3-total-cache#347]
Check out my shop page here:
https://207.154.243.82/shop
(I do not want to use the domain name in public)
Images 22 to 30 are left blank for some weird reason.

If I disable W3TC lazyloading, the images are all displayed properly.
How do I fix this?

UPDATE:
I had to use another lazyload mechanism. If you want to see the problem in action, let me know and I will enable W3TC lazyload for your perusal.

**Comment by mavas84** [comment]
Hello @conandrum 

We already have an issue opened for this https://github.com/W3EDGE/w3-total-cache/issues/86
I'll close this as a duplicate. please level any comment.
Thanks!
