### ISSUE TITLE
Change Feature Policy to Permissions Policy

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#348]
The Feature-Policy standard & header is being renamed to Permissions-Policy.
https://www.w3.org/TR/permissions-policy-1/

**Comment by woodruffandtheschnibbleofazimuth** [comment]
Hello,
in addition to this I think it should be added the new control called: "interest-cohort=()" as said there: https://spreadprivacy.com/block-floc-with-duckduckgo/
