### ISSUE TITLE
Function Redis::delete() is deprecated

### ISSUE THREAD

**Issue by ILLeTiD** [W3EDGE/w3-total-cache#36]
Function Redis::delete() is deprecated
`
<div class="qm-toggled" style="display: block;"><li><code>do_action('admin_print_scripts-index.php')</code><br><span class="qm-info qm-supplemental">wp-admin/admin-header.php:125</span></li><li><code>wp_localize_community_events()</code><br><span class="qm-info qm-supplemental">wp-includes/class-wp-hook.php:286</span></li><li><code>update_user_option()</code><br><span class="qm-info qm-supplemental">wp-includes/script-loader.php:2264</span></li><li><code>update_user_meta()</code><br><span class="qm-info qm-supplemental">wp-includes/user.php:538</span></li><li><code>update_metadata()</code><br><span class="qm-info qm-supplemental">wp-includes/user.php:853</span></li><li><code>wp_cache_delete()</code><br><span class="qm-info qm-supplemental">wp-includes/meta.php:273</span></li><li><code>W3TC\ObjectCache_WpObjectCache-&gt;delete()</code><br><span class="qm-info qm-supplemental">wp-content/object-cache.php:80</span></li><li><code>W3TC\ObjectCache_WpObjectCache_Regular-&gt;delete()</code><br><span class="qm-info qm-supplemental">wp-content/plugins/w3-total-cache/ObjectCache_WpObjectCache.php:63</span></li><li><code>W3TC\Cache_Redis-&gt;delete()</code><br><span class="qm-info qm-supplemental">wp-content/plugins/w3-total-cache/ObjectCache_WpObjectCache_Regular.php:324</span></li></div>

`

**Comment by mavas84** [comment]
Hello,
Please follow the existing issue related to Function Redis::delete() deprecation.
https://github.com/W3EDGE/w3-total-cache/issues/29
