### ISSUE TITLE
Media llibrary images with custom directory structure will not upload to s3

### ISSUE THREAD

**Issue by unnamedfeeling** [W3EDGE/w3-total-cache#365]
Hello
I have:

- configured cloudfront s3 integration working - files from all directories will upload correctly
- modified url structure for uploaded images - wp-content/uploads/2021/04 -> app/uploads/2021/04/18/21/05/some-image.jpg (directory structure reflects Y/m/d/H/i/)

My images are uploading to media library and are correctly served from my backend and cloudfront is able to correctly fetch and serve images.

The problem comes up when images are uploaded to s3 - the local path and uri's are not generated correctly. The Unsuccessful file transfer queue will state this:

`
Local Path | Remote Path | Last Error | Date | Delete
/var/www/html/web/app/uploads/image.jpeg | app/uploads/image.jpeg | Source file not found. | 2021-04-19 05:19:28 | Delete
`

The code that alters directory is roughly as follows:

    add_filter('wp_handle_upload_prefilter', [self::class, 'handle_upload_prefilter']);
    add_filter('wp_handle_upload', [self::class, 'handle_upload']);

    public static function handle_upload_prefilter( $file )
    {
        add_filter('upload_dir', [self::class, 'set_custom_upload_dir']);
        return $file;
    }
    public static function handle_upload( $fileinfo )
    {
        remove_filter('upload_dir', [self::class, 'set_custom_upload_dir']);
        return $fileinfo;
    }
    public static function set_custom_upload_dir($path)
    {
        /*
         * Determines if uploading from inside a post/page/cpt - if not, default Upload folder is used
         */
        $uploadingFromPost = isset($_REQUEST['post_id'] ) && $_REQUEST['post_id'] == 0;

        if($uploadingFromPost){
            $the_post = get_post( $_REQUEST['post_id'] );
            $postTime =
                !is_wp_error($the_post) && isset($the_post->post_date) && !empty($the_post->post_date) ?
                    strtotime( $the_post->post_date ) : time();
        } else {
            $postTime = time();
        }

        $y = date( 'Y', $postTime );
        $m = date( 'm', $postTime );
        $d = date( 'd', $postTime );
        $h = date( 'H', $postTime );
        $i = date( 'i', $postTime );

        $customdir = '/' . $y . '/' . $m . '/' . $d . '/' . $h . '/' . $i;

        $path['path']    = str_replace($path['subdir'], '', $path['path']); //remove default subdir (year/month)
        $path['url']     = str_replace($path['subdir'], '', $path['url']);
        $path['subdir']  = $customdir;
        $path['path']   .= $customdir;
        $path['url']    .= $customdir;

        return $path;
    }

It will run in theme's functions.php in root.

Could someone please guide me what did I do wrong here?

**Comment by unnamedfeeling** [comment]
I have dig little bit deeper. So there are 2 places to be altered in plugin for my setup to work:

- Cdn_Core.php: 338 - alter regexp like this: '~(\d{4}/\d{2}/)?[^/]+$~' -> '~(\d{4}/\d{2}/\d{2}/\d{2}/\d{2}/)?[^/]+$~' (hey, maybe we add filter here for such situations?)
- Util_Environment.php: 352 - prepend with alternation method for altering uploads_dir: `add_filter('upload_dir', [Filters::class, 'set_custom_upload_dir'], 10, 1);` (I know - bad idea, maybe point me to a better way to do it...)

**Comment by mavas84** [comment]
Hello @unnamedfeeling 

Thank you for reaching out.
What you can do in this specific case is to use a filter.
`(\d{4}/\d{2}/)?[^/]+$` for `/var/www/html/web/app/uploads/image.jpeg` has match `image.jpeg`.
`(\d{4}/\d{2}/\d{2}/\d{2}/\d{2}/)?[^/]+$` has the same match if you check https://github.com/W3EDGE/w3-total-cache/blob/master/Cdn_Core.php#L338
So this may have something to do with https://github.com/W3EDGE/w3-total-cache/blob/master/Util_Environment.php#L351
You can  fix it with a filter that helps define the default/initial value that relies on https://developer.wordpress.org/reference/functions/wp_upload_dir/
Your  `WP_CONTENT_DIR` should be `/var/www/html/web/app` in that case.
As you can see:
>If the ‘UPLOADS’ constant is defined, then it will override the ‘upload_path’ option and ‘WP_CONTENT_DIR/uploads’ path.
So you can define UPLOADS to override.
I hope this helps!
Thanks!
