### ISSUE TITLE
Gracefully fallback if Redis is unavailable or intermittent.

### ISSUE THREAD

**Issue by cophaso** [W3EDGE/w3-total-cache#366]
The plugin is capable of handling if it can’t connect to redis initially, but If `get()` takes a long time, the page load will just hang and eventually give a 500 rather than gracefully failing and fetching the data from the database instead.
https://github.com/W3EDGE/w3-total-cache/blob/6669102996cbef3e5dd9ae453003206390477f03/Cache_Redis.php#L91

**Comment by mavas84** [comment]
Hello @cophaso 

Thank you for reaching out.
This is added to our Backlog and the devs will make sure to get on this as soon as possible.
Thanks!
