### ISSUE TITLE
Provide options for how to handle missing files

### ISSUE THREAD

**Issue by timreeves** [W3EDGE/w3-total-cache#367]
I use nginx (exclusively) and Plesk. I am working on the Nginx config to remove all success messages from the access logs, so that monitoring them with Fail2Ban is possible (otherwise they are too large and often written, the server freezes up with race conditions). In this context I noticed while testing that when I try to access a non-existent .php file, I get the expected 404. But when I try to access any non-existent file whose type is cached by W3TC, then it receives a 301 redirect to the home page. This is due to code exported by W3TC and included in my nginx config, looking like this:

```
location ~ \.(css|htc|less|js|js2|js3|js4)$ {
    expires 36000s;
    etag on;
    if_modified_since exact;
    add_header Pragma "public";
    add_header Cache-Control "public";
    add_header X-Powered-By "W3 Total Cache/2.1.2";
    add_header Referrer-Policy "no-referrer-when-downgrade";
    try_files $uri $uri/ /index.php?$args;
}

```
See the try_files at the end: If no such file or directory exists, then the request is passed to WordPress /index.php together with the request arguments. This is the WordPress mechanism mainly used for permalink slugs and special urls provided by plugins - so when no match is found WordPress returns a 301 redirect to the domain landingpage.

But 3xx codes do not signify errors, and anyway, how would I distinguish between a 301 resulting from a probing attack and one which is bona fide, e.g. for a page which has been moved? As mentioned above, I'm keeping the logs as short as possible by suppressing all 2xx and 3xx loglines, as [demonstrated here](https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#conditional). The bottom line is that we need a 403 or 404 error code at this point.

I've developed some config which I can put before the code block from W3TC is included:

```
# Catch attempts by nasty bots to access executables which are not used on the server
location ~ \.(js2|js3|js4|csh|exe|jar|pl|py|pyo|pyc|rb|sh)$ { deny all; return 444; }

# Handle JS ourselves, i.e. pre-empt W3TC on this one to get a 403 in the access log
# 403 if no file found because we come down hard on IPs causing 403's - and this is JS...

location ~ \.js$ {
    expires 36000s;
    etag on;
    if_modified_since exact;
    add_header Pragma "public";
    add_header Cache-Control "public";
    add_header Referrer-Policy "no-referrer-when-downgrade";
    try_files $uri $uri/ =403;
}
```
Re what happens in the browser when a page includes a missing image file: The code 301 is returned, as per W3TC's instruction. The browser does not perform any redirection nor open a new tab, it simply ignores the 301 and shows the alt-attribute at the point on the page. So I can't see it being particularly helpful - unless some plugin generates the image file, which I've yet to see happen - correct me if I'm wrong. It would be safer to return a 4xx code to the browser which then knows that there is no such resource available and can handle the situation better - the 301 implies it will (eventually) get somehting, but it does not.

Currently I have arrived at an interesting state whereby:

- A request for missing.php => 404 (I could change that to 403)
- A request for missing.js => 403
- A request for missing.css => 301 (from W3TC)

In view of the fact that re security attempts to access an executable which is missing is a much worse sin than looking for a missing image or video, my suggestion is to regroup the various file types and provide options for each of them:

- How to handle requests for missing executable files (403 / 404 / index.php)           (my preference 403)
- How to handle requests for missing non-executable files (403 / 404 / index.php)    (my preference 404)

Thanks for a great plugin, hope this helps to make it even greater by co-existing better with other concerns.

Tim Reeves

**Comment by mavas84** [comment]
Hello @timreeves 

Thank you for reaching out and taking the time to open this issue.
This is in our Backlog and we'll get back to you as soon as the devs investigate this.
Thanks!

**Comment by cssjoe** [comment]
@timreeves Thank you for asking us to look into this issue. We have decided that the potential enhancement could cause more issues than it may solve.  It is recommended to have a solution outside of the plugin.  A couple of options that may be useful here are "Do not process 404 errors for static objects with WordPress" and "404 error exception list".  Other avenues may include looking at the Nginx and Fail2Ban configurations.
