### ISSUE TITLE
Fatal Error: Cannot redeclare GuzzleHttp\\json_encode()

### ISSUE THREAD

**Issue by lorenzosfienti** [W3EDGE/w3-total-cache#369]
**Describe the issue**

I just try to activate the [AWS for WordPress](https://wordpress.org/plugins/amazon-polly/) meanwhile W3 Total Cache is already activated.

After the activation of AWS for WordPress the website stop to work and inside the error log I see this

`Got error 'PHP message: PHP Fatal error:  Cannot redeclare GuzzleHttp\\json_encode() (previously declared in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/amazon-polly/vendor/guzzlehttp/guzzle/src/functions.php:164) in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/w3-total-cache/lib/Aws/GuzzleHttp/functions.php on line 323'`

**Describe the solution you'd like**
If possible, W3TC should only load AWS libraries if they haven't already been loaded.

**Describe alternatives you've considered**
About add W3TC_SKIPLIB_AWS we need to deactivate for some minutes the plugin and all the caches already activated and it's not a good idea in a production envriroment.

**Comment by cssjoe** [comment]
We have updated the AWS library (to version 1.180.1) in our plugin in the upcoming patch version.  We will be loading the library using a composer autoloader, which should prevent loading libraries that are already loaded.  I tested our beta version with the AWS plugin (uses version 3.178.8) and I am not getting a fatal error.  Feel free to test the beta version https://github.com/W3EDGE/w3-total-cache/releases/download/2.1.3-beta.1/w3-total-cache-2.1.3-beta.1.zip or wait for the patch release to be published.  Please let us know if you find any issues.  Thank you.

**Comment by lorenzosfienti** [comment]
Hi, @cssjoe thanks for your response.

Attempt the new version will be release.

**Comment by philcook** [comment]
Just wanted to leave this comment here to potentially help others.
If you like me load the aws-sdk-php package via composer or like the original poster who is loading it via a plugin then you can skip W3 Total Cache loading its own AWS library and instead use your version. Simply add this to your wp-config.php file.
```
// Stop the conflict of using native library and w3 total version.
define('W3TC_SKIPLIB_AWS', true);
```
Hope that helps someone else out there.
