### ISSUE TITLE
dbcluster-config-sample.php  to wp-content/db-cluster-config.php not working

### ISSUE THREAD

**Issue by wobeng** [W3EDGE/w3-total-cache#370]
Hello,

I have the pro version of w3-total-cache. I modified wp-content/plugins/w3-total-cache/ini/dbcluster-config-sample.php to wp-content/db-cluster-config.php and its not working. 

Am I doing anything wrong?

```
<?php

global $w3tc_dbcluster_config;

$w3tc_dbcluster_config = array(
	'databases' => array(
		'master' => array(
			'host'     => DB_HOST,
			'user'     => DB_USER,
			'password' => DB_PASSWORD,
			'name'     => DB_NAME
		),
		'slave' => array(
			'host'     => DB_HOST2,
			'user'     => DB_USER,
			'password' => DB_PASSWORD,
			'name'     => DB_NAME,
			'write'    => false,
			'read'     => true
));

```

**Comment by mavas84** [comment]
Hello @wobeng 

Thank you for your inquiry.
We received your email via the support channel and we replied. Please continue the correspondence there so we can avoid duplicating the answers.
Thanks!

**Comment by jpSimkins** [comment]
Could you please update this ticket to show how this is resolved?
