### ISSUE TITLE
Page cache Memcached + Nginx memcached_pass is hardcoded to localhost

### ISSUE THREAD

**Issue by mo2menelzeiny** [W3EDGE/w3-total-cache#374]
https://github.com/W3EDGE/w3-total-cache/blob/6669102996cbef3e5dd9ae453003206390477f03/PgCache_Environment.php#L1217

I believe that this should get the hostname from the page cache config field

probably something like this would work 

` $rules .= '    memcached_pass' . array_values($config->get_array( 'pgcache.memcached.servers' ))[0]; . ':11211;' . "\n"; `

**Comment by mavas84** [comment]
Hello @mo2menelzeiny 

Thank you for reaching out and taking the time to suggest this.
I'll get back to you as soon as the test is done.
Thanks!

**Comment by mo2menelzeiny** [comment]
@mavas84 which test are you talking about?

**Comment by mavas84** [comment]
Hello @mo2menelzeiny 

Thanks for the info. It would be great if you could submit a PR on this.
Thanks!

**Comment by mo2menelzeiny** [comment]
Alright, work in progress

**Comment by mo2menelzeiny** [comment]
@mavas84 I think this is more of a bug rather than an enhancement, because it does not configure memcached correctly.

The Admin UI allows you to configure servers and choose Memcached + Nginx in page cache, which produces this behavior I outlined.
