### ISSUE TITLE
Block Cache on a page or Directory

### ISSUE THREAD

**Issue by ozoneprof** [W3EDGE/w3-total-cache#380]
I am using wpFORO and the instructions are to not use a cache on the forum pages, how do i block w3 total cache from caching those pages?

**Comment by mavas84** [comment]
Hello @ozoneprof 

Thank you for reaching out.
You can add the page you wish to exclude from caching in Performance>Page Cache>Never Cache following Pages field, for example:
/forum/
The regex is supported and you can check more on our FAQ page.
Alternatively, you can add `define('DONOTCACHEPAGE', true);` to the template which will prevent that template from being cached.
Please do not use GH for the support as this is intended for reporting bugs and suggesting improvements. You can do us a note directly via the plugin in Performance>Support, or in the [wp forum](https://wordpress.org/support/plugin/w3-total-cache/) as well as in the [Boldgrid forum ](https://www.boldgrid.com/support/ask-a-question/)for any support questions.
Thanks!
