### ISSUE TITLE
2 cache headers are created when enabling cache hearder from w3-total-cache

### ISSUE THREAD

**Issue by tkumark** [W3EDGE/w3-total-cache#381]
I installed the default bitnami wordpress. One done the cache-control header is like Cache-Control: max-age=0, no-cache, s-maxage=10. when I enable cache control header from w3-total-cache it creates an additional Cache-Control hearder. 

I would assume the plugin would override the exiting header

![image](https://user-images.githubusercontent.com/2689801/121139530-7c1dc300-c856-11eb-88a2-836f12b8d030.png)

**Comment by mavas84** [comment]
Hello @tkumark 

Thank you for reaching out.
W3 Total Cache does not override the existing header. W3 Total Cache rules are set according to your BC settings. You need to make sure that you do not have some custom settings in your .htaccess/nginx.conf and remove them if you want to avoid conflict with W3TC rules.
You should also reach out to your hosting provider and check if there are some rules at the root of the installation.
Please do not use GH for the support as this is intended for reporting bugs and suggesting improvements. You can do us a note directly via the plugin in Performance>Support, or in the [wp forum](https://wordpress.org/support/plugin/w3-total-cache/) as well as in the [Boldgrid forum](https://www.boldgrid.com/support/ask-a-question/) for any support questions.
Thanks!
