### ISSUE TITLE
S3 Compatible CDN not working with VULTR.com Object Storage.

### ISSUE THREAD

**Issue by theanteomnio** [W3EDGE/w3-total-cache#397]
I am unable to get this working. I get error.

`Error: Unable to put object (S3Compatible::putObject(): [411] Unexpected HTTP status).`

**Comment by mavas84** [comment]
Hello @theanteomnio 

Thank you for reaching out. 
The Issue you are referring to with S3 compatible option is a known issue and we already have a ticket opened for this and working on a solution. 
Please make sure to follow the progress in the existing ticket and make sure to add any comments that may help!
https://github.com/W3EDGE/w3-total-cache/issues/243
Thanks!
