### ISSUE TITLE
Nginx + Memcached configuration error

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#398]
When configuring page caching for Nginx + Memcached, the` /<web-root>/nginx.conf `gets written with an error.
` Note the "memcached_pass127..." is missing a space. `
Every re-write of this file results in this error and manuall edit is needed of the file to get nginx to restart properly.
```location ~ ".*(?<!php)$" {
set $memcached_key "$http_host$request_uri_noslash/$w3tc_ssl$w3tc_preview$w3tc_enc";
memcached_gzip_flag 65536;
default_type text/html;
if ($w3tc_rewrite = 1) {
memcached_pass127.0.0.1:11211;
}
error_page 404 502 504 = @fallback;
}

**Comment by mo2menelzeiny** [comment]
this should have been fixed here https://github.com/W3EDGE/w3-total-cache/issues/390

**Comment by mavas84** [comment]
@mo2menelzeiny  Thanks for the info
The issue was reported in the current 2.1.5 release.
I'll investigate more about this.
Thanks!
