### ISSUE TITLE
Allow setting AWS IAM permissions through an instance profile

### ISSUE THREAD

**Issue by jre21** [W3EDGE/w3-total-cache#399]
Please support the use of the AWS SDK's default credential provider, rather than requiring that S3 and CloudFront CDN users pass AWS credentials into the plugin's configuration.  I expect the most straightforward way to implement this change is to

1.  allow users to leave the fields for the AWS access and secret key blank (which may or may not require changes to input validation)

2.  in the files which set AWS credentials ([1][1], [2][2], [3][3], [4][4], [5][5], [6][6]), check whether the key and secret are both blank, and if so, instead set `$credentials = \Aws\Credentials\CredentialProvider::defaultProvider();` as described in mkostrikin's comment [here][comment].

[1]: https://github.com/W3EDGE/w3-total-cache/blob/73911133ca843de9c20086c73aa84b134f4f9bb4/CdnEngine_CloudFront.php#L33
[2]: https://github.com/W3EDGE/w3-total-cache/blob/73911133ca843de9c20086c73aa84b134f4f9bb4/CdnEngine_Mirror_CloudFront.php#L32
[3]: https://github.com/W3EDGE/w3-total-cache/blob/73911133ca843de9c20086c73aa84b134f4f9bb4/CdnEngine_S3.php#L103
[4]: https://github.com/W3EDGE/w3-total-cache/blob/73911133ca843de9c20086c73aa84b134f4f9bb4/Cdnfsd_CloudFront_Engine.php#L79
[5]: https://github.com/W3EDGE/w3-total-cache/blob/73911133ca843de9c20086c73aa84b134f4f9bb4/Cdnfsd_CloudFront_Popup.php#L409
[6]: https://github.com/W3EDGE/w3-total-cache/blob/73911133ca843de9c20086c73aa84b134f4f9bb4/Enterprise_SnsBase.php#L43
[comment]: https://wordpress.org/support/topic/iam-profile-support/#post-14588782

The primary use case for this request is when WordPress itself is running on an AWS ec2 instance or in a managed service like ECS.  In these cases the security best practice is to define AWS permissions through an [instance profile][profile] rather than require a long-lived API token to be present (`CredentialProvider::defaultProvider()` uses an instance profile when appropriate, as described [here][provider]).  Since I expect that the most common usecases for the S3 and CloudFront CDNs involve users running their entire WordPress site on AWS infrastructure, allowing users to easily opt in to using the default credential provider in this way would be a major usability win.

[profile]: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-ec2_instance-profiles.html
[provider]: https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials_provider.html#defaultprovider-provider

Normally when I make a request involving a relatively straightforward change like this one, I prefer to include a pull request.  However, as I haven't written PHP code in several years and am not aware of this project's standard conventions, I thought it would be simpler in this case to restrict myself to a description of the request rather than attempt to provide code that a project maintainer would likely need to substantially rewrite regardless.

**Comment by mavas84** [comment]
Hello @jre21 

Thank you for taking the time to submit the request.
This is now in the backlog and will be added to future releases.
Thanks!

**Comment by jre21** [comment]
Getting fully oriented on the code base turned out to be easier than I expected, so I went ahead and created a pull request after all.

**Comment by mavas84** [comment]
Hello @jre21 

Thank you once again for taking the time to report this and especially for the pull request. This is now fixed in the latest 2.1.6 release!
