### ISSUE TITLE
How to modify the connection address and port of redis database?

### ISSUE THREAD

**Issue by Hello-Linux** [W3EDGE/w3-total-cache#4]
How to change the address and port of wordpress to connect to redis database?

**Comment by maxicus** [comment]
See
https://github.com/W3EDGE/w3-total-cache/blob/master/README.md#support

> This repository is not suitable for support. Please don't use our issue tracker for support requests.Support can take place through the appropriate channels:
> 
> The support form can be found in Performance -> Support page of your wp-admin.
> Our community forum on wp.org.
> 
> Support requests in issues on this repository will be closed on sight.
