### ISSUE TITLE
Clicking "Empty all cache" doesn't clear everything

### ISSUE THREAD

**Issue by erikdemarco** [W3EDGE/w3-total-cache#401]
To replicate:
-) Enable page cache using disk basic, and browse some pages
-) Enable page cache using disk enhanced, and browse some pages
-) Enable page cache using redis, and browse some pages
-) Now click 'Empty all cache', It wont clear cache folder for "/wp-content/cache/page/" and "/wp-content/cache/page_enhanced/"

If we not gonna clear all previously used cache, just change the button to "Empty currently used cache". Its a bit confusing

**Comment by mavas84** [comment]
Hello @erikdemarco 
Thank you for reaching out.
Empty all cache or Purge all cache indeed does not remove the files/folders within the /wp-content/cache/page/ or /wp-content/cache/page_enhanced/.
When a page is cached, the file is saved without _old. When the choice to empty/purge cache the _old extension is added. This is actually done to prevent loading the cached page and force updating the page cache. Garbage collection option in Performance>Page Cache, Advanced sub-box is used to remove all the _old files from the cache directory in the time interval which is by default set to 3600s.
And this is how W3 Total Cache deals with the cached pages.
Once again thank you for your suggestion and this will be considered for future releases to avoid confusion.
Thanks!
