### ISSUE TITLE
Page cache should be compressed when using redis or memcache

### ISSUE THREAD

**Issue by erikdemarco** [W3EDGE/w3-total-cache#403]
As ram storage is costlier to scale on a web server, Redis or memcache is ideal for caching smaller files such as database query results and persistent sessions. Thus, Redis is typically used to enable object caching and not page caching because 'database query result' tends to be smaller in size than 'rendered page result'. For information memcache default max memory is just 64mb. When we compress text data it should save a lot of bandwith and storage space.

**Comment by mavas84** [comment]
Hello @erikdemarco 

Thank you for reaching out and your suggestion.
This would be counterproductive. As an optimization plugin, we are trying to improve the speed and this would cause a lot of server resources consumption because of the compression - caching -decompression. This would overload the server processor and it would slow things down instead of making it faster.
It's easier to expand and use more memory. This would only make sense if someone would want to save memory and be OK with a slow website.
Thanks!

**Comment by erikdemarco** [comment]
@mavas84 
> Hello @erikdemarco
> 
> Thank you for reaching out and your suggestion.
> This would be counterproductive. As an optimization plugin, we are trying to improve the speed and this would cause a lot of server resources consumption because of the compression - caching -decompression. This would overload the server processor and it would slow things down instead of making it faster.
> It's easier to expand and use more memory. This would only make sense if someone would want to save memory and be OK with a slow website.
> Thanks!

Here's the few argument to backup my point:

1. compressing and decompressing is very fast (done in cpu) compared to network latency. Especially true when use redis via remote (average ping for same datacenter is 1-2ms) is much more slower than processing gzip compression 50kb (average page size) of data in cpu.

2. for cache hit ratio. Its better to store more key-value. the more key we store the higher the cache hit ratio. To store more cache we need a compression.

Even redis themself recommend it:
=> https://docs.redislabs.com/latest/ri/memory-optimizations/#compress-values

I propose we let the user decide themself. By letting them toggle it via setting page. Of course with default value being turned off. I think its a win-win solution.

**Comment by mavas84** [comment]
Hello @mavas84 

I spoke with the devs, and yes it may be considered in the future to let the user decide.
Thank you again for the recommendation

**Comment by erikdemarco** [comment]
@mavas84 

Thank you for considering. For future documentation, here's the prove to deny "This would overload the server processor and it would slow things down instead of making it faster."

Testing using loader.io with 100users/sec, 10 seconds timeout

Plugin 1: 
Pressjitsu Redis Page Cache (with compression as default):
-) Installaion guide: https://github.com/pressjitsu/pj-page-cache-red/
-) with this settings:
define( 'WP_CACHE', true );
$redis_page_cache_config = array();
$redis_page_cache_config['redis_host'] = '127.0.0.1';
$redis_page_cache_config['redis_port'] = 6379;
$redis_page_cache_config['redis_persistent'] = true;
-) result: 
https://i.ibb.co/crWNGcr/redis-page-cache-pressjitsu.jpg

Plugin 2:
W3 Total Cache (without compression as default)
-) with this settings:
enable only page cache (with redis)
-) result: 
https://i.ibb.co/9ckGjLj/redis-page-cache-w3tc.jpg

For anyone please feel free to retest it yourself.
