### ISSUE TITLE
RackSpace CDN UI breaks CNAME - CNAME not saved

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#404]
Section “Replace site’s hostname with” shows the correct hostname that appears after click “Reload” but disappear after clicking “Save”
Reference topic: https://wordpress.org/support/topic/rackspace-cdn-is-not-working-with-cname/

**Comment by jfr** [comment]
is there any workaround for this issue? cname still isnt used..

**Comment by mavas84** [comment]
Hello @jfr 

Thank you for reaching out.
We've made the necessary changes, however, we are unable to test this thoroughly since no new Rackspace subscriptions are accepted.
I've attached the zip that contains changed files below. If convenient, please replace the existing files (make sure to make a backup) with the ones in the ZIP and test the CDN.

Please let me know if this helps!

Thanks!


[RackspaceCDN.zip](https://github.com/W3EDGE/w3-total-cache/files/7226204/RackspaceCDN.zip)

**Comment by cssjoe** [comment]
Closed due to no response since 9/24.
