### ISSUE TITLE
Object cache reporting showing 0/0

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#41]
When inspecting the element while object caching is enabled reporting shows the following:
Object Caching 0/0 objects using Memcached
Object Caching 0/0 objects using disk
When Object Cache Debug is enabled, the report is showing the following:
`Object Caching 39/60 objects using disk

Object Cache debug info:
Caching:            enabled
Total calls:        60
Cache hits:         39
Total time:         0.0077`
Reporting doesn't show under the non-debug mode, but actual caching works.

**Comment by maxicus** [comment]
fixed by https://github.com/W3EDGE/w3-total-cache/commit/c8f939d64c9480c064990f85ebc0f5b2472c6585
