### ISSUE TITLE
Googlebot can't crawl CSS

### ISSUE THREAD

**Issue by MartijnOud** [W3EDGE/w3-total-cache#419]
I noticed in 2.1.7. there is a change "Disallow crawling of cache directory" from  #147. Is there a way this could be made into a setting so I can turn it back on?

Googlebot needs to crawl the CSS of my website to be able to see the responsive website. This changes make it so Google can and starts throwing Search Conole warnings about the website failing the mobile friendly test.

https://developers.google.com/search/mobile-sites/mobile-seo/responsive-design

> Important: Be sure not to block the crawling of any page assets (CSS, JavaScript, and images) for any Googlebot using robots.txt or other methods. Being able to fully access these external files helps our algorithms detect your site's responsive web design configuration and treat it appropriately.

**Comment by mavas84** [comment]
Hello @MartijnOud 

Thank you for training the time to report this and open this ticket.
The problem with the recent update has been reported numerous times and we are working on a fix!
Thank you for your patience!
