### ISSUE TITLE
Installation for memcached is not up-to-date

### ISSUE THREAD

**Issue by simplenotezy** [W3EDGE/w3-total-cache#43]
I tried following the guide here: https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-Installation:-Memcached-Server

However it is not up-to-date. For instance I needed to be root to run the commands, `su` failed (as I have no password) so I had to manually add the files.

1. `/etc/init.d/memcached` the memcached line should be above `exit 0`, I believe the echo would add it to the bottom of the file
2. Running `/etc/init.d/memcached` has no effect. I had to run `/etc/init.d/memcached start`, however, it was already started.

I used the automatic install `apt-get -y install memcached`

**Comment by cssjoe** [comment]
The page has been updated.
