### ISSUE TITLE
Cloudfront Mirror purge - invalidators

### ISSUE THREAD

**Issue by kamyweb** [W3EDGE/w3-total-cache#446]
it seems two implementations of purge inside CdnEngine_CloudFront.php and CdnEngine_Mirror_CloudFront.php are different.
The second one use createInvalidationAsync that failed on my server without a wait() call to the guzzle promise object; another way is to use the implementation of other cloudfront php CdnEngine_CloudFront.php that use the synched version -> createInvalidation.

So I suggest to change line 83 of  CdnEngine_Mirror_CloudFront.php from createInvalidationAsync(...) to createInvalidation(...)
```
	function purge( $files, &$results ) {
                try {
                        $this->_init();
                        $dist = $this->_get_distribution();
                } catch ( \Exception $ex ) {
                        $results = $this->_get_results( $files, W3TC_CDN_RESULT_HALT, $ex->getMessage() );
                        return false;
                }

                $paths = array();

                foreach ( $files as $file ) {
                        $remote_file = $file['remote_path'];
                        $paths[] = '/' . $remote_file;
                }

                try {
                        $invalidation = $this->api->createInvalidation( array(
                                        'DistributionId' => $dist['Id'],
                                        'InvalidationBatch' => array(
                                                'CallerReference' => 'w3tc-' .  microtime(),
                                                'Paths' => array(
                                                        'Items' => $paths,
                                                        'Quantity' => count( $paths ),
                                                ),
                                        )
                                )
                        );
                } catch ( \Exception $ex ) {
                        $results = $this->_get_results( $files, W3TC_CDN_RESULT_HALT,
                                sprintf( 'Unable to create invalidation batch (%s).',
                                $ex->getMessage() ) );

                        return false;
                }

                $results = $this->_get_results( $files, W3TC_CDN_RESULT_OK, 'OK' );
                return true;
        }

```

**Comment by hanicker** [comment]
Hi, what error are you having with async? I added it here https://github.com/W3EDGE/w3-total-cache/pull/435/commits/f4664e3e42ff9c25cacab953e3a8dd751ed542cc as it improved a lot the administration, but I was able to track correct invalidations in aws, just checking if it may be due to some configuration. Thanks in advance

**Comment by kamyweb** [comment]
@hanicker the aync version doesn't complete correctly on my server without a guzzle wait() call - with this version you need to collect all async call and then wait all become completed, before quit the function/script - or rollback to the synched version createInvalidation(...) that is probably slow, but it works!

**Comment by hanicker** [comment]
@kamyweb thanks I was able to replicate the problem, even if non consistently. I'm thinking about adding the sync invalidation to the \W3TC\Cdn_Core_Admin::queue_process, I will work in these days on a pull request

**Comment by cssjoe** [comment]
Thank you @kamyweb and @hanicker for the info.  We have deployed patch version 2.2.1 including the merged pull request to revert the "async" changes.  Please update, test the changes, and let us know if there any further issue.
