### ISSUE TITLE
Issue with 'Cache SSL (HTTPS) requests'

### ISSUE THREAD

**Issue by fransverztec** [W3EDGE/w3-total-cache#449]
Hi there,

I realized that when i enabled 'Cache SSL (HTTPS) requests' option in the wordpress' page, the website speed is indeed faster, but there is an issue happening because of that.

Just to explain it a bit about the issue here that we have added a script to do user account validation (not login) from another website. The script is just to validate if this person is a valid user of that website. We are using API that was provided by that website. And whenever a successful validation happened, there will be a session created (namely ‘mmsname’) in our website (annals.edu.sg). The content of this session is to be displayed at the top portion of the website.

Now, if we enable 'Cache SSL (HTTPS) requests' option, let’s say I am now validated as John Doe, i would be seeing that name on top portion of the website. When a few moment later another person try to open annals.edu.sg from **another location**, he/she will also see 'John Doe' on top portion of the website.

So somehow, this ‘mmsname’ session is being cached and ‘shared’ to public.

Would you know how to fix this issue? Or is there anything that i missed out here?

Thanks,

Frans

**Comment by mavas84** [comment]
Hello @fransverztec  

I've replied to yoru email sent via the support channel and wp.org topic.
Please continue the correspondence there so we can avoid duplicating the answers.
Thanks!
