### ISSUE TITLE
MFUNC vs. MCLUDE - what to use?

### ISSUE THREAD

**Issue by CreativForm** [W3EDGE/w3-total-cache#45]
What is the difference?

I trying to include your MFUNC inside [WordPress Geo Plugin](https://wordpress.org/plugins/cf-geoplugin/) and I'm confused what to use. Geo data and dynamic content we have must NOT be cached and we now have a problems with that.

We now using something like:

```
if($cache)
{
	return '<!--mfunc ' . W3TC_DYNAMIC_SECURITY . ' -->' 
		. do_shortcode($content) 
	. '<!--/mfunc ' . W3TC_DYNAMIC_SECURITY . ' -->';
}
else
{
	return do_shortcode($content);
}

```
...or:
```
if($cache)
{
	if(isset($CFGEO[$return]))
	{
		return '<!--mfunc ' . W3TC_DYNAMIC_SECURITY . ' --><span class="cfgeo-replace" data-key="' . $return . '" data-nonce="' . $nonce . '">' 
			. $CFGEO[$return] 
		. '</span><!--/mfunc ' . W3TC_DYNAMIC_SECURITY . ' -->';
	}
	else
	{
		return '<!--mfunc ' . W3TC_DYNAMIC_SECURITY . ' -->' . $default . '<!--/mfunc ' . W3TC_DYNAMIC_SECURITY . ' -->';
	}
}
else
{
	if(isset($CFGEO[$return]))
	{
		return $CFGEO[$return];
	}
	else
	{
		return $default;
	}
}
```

And we must be sure this will work with your plugin.

Do we need to include something else or is this only thing what need to be done?

Note that users will place 2, 3, 10 shortcodes on the one page what contain various geo information. We must be sure that all was changed properly.

Thanks!

**Comment by gidomanders** [comment]
As the readme of this repository states:
> This repository is not suitable for support. Please don't use our issue tracker for support requests. Support can take place through the appropriate channels

Explanation of difference between mfunc and mclude can be found in the wiki
