### ISSUE TITLE
Use API Token for Cloudflare authorization

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#450]
If an account is managing several CF accounts with 100+ Domains  Authorizing Cloudflare with the Global API is may not be the best solution since all websites are listed when authorizing. 
Add ability to use token-based authentication API Token with the needed permissions.

Reference topic: https://wordpress.org/support/topic/cloudflare-can-we-use-api-token-and-with-which-permissions-kindly-thank-you/

**Comment by fritexvz** [comment]
Thank you for adding a note about this!

**Comment by fritexvz** [comment]
Kindly, may I ask, as far as the user chooses to use a Cloudflare API Token - which can be restricted by the needed/required permissions, may I ask will somewhere be stated which permissions does the user need to allow per the API token so W3TC plugin would continue working properly (at least in terms of Purge the Cache, purge the cache upon post modification of the current settings available)?

Could be I misread them if they are already stated for future release of W3TC plugin in some help/setup process while configuring/connecting Cloudflare extension from the W3TC interface.

Reference: 
https://api.cloudflare.com/#getting-started-endpoints

Image from Cloudflare Dashboard -> API Tokens:
![api_token](https://user-images.githubusercontent.com/4490792/144153124-59c5fdca-3926-4dc8-a685-f3ddb2e87e6b.png)

Nevertheless, we could limit the API token with required permissions per zone/domain, that way it wouldn't have permissions to view/edit others from the Cloudflare account.

Not to mention the fact that if the server got compromised, the E-mail and Global API Key is stored into the master.php file of the w3tc-config file, right?
