### ISSUE TITLE
Intelligently preload assets

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [W3EDGE/w3-total-cache#452]
When "HTTP/2 push" is activated on both CSS and JS, all of my javascript files start downloading before any CSS does. This causes a significant delay before the CSS finishes downloading and the HTML continues parsing (thus causing a FCP delay). There is no way for me to specify the preferred order of the header preloads; however I believe you can make this an automatic improvement.

Ideally this would be handled based on the load instructions for each script. i.e.:

1. CSS
2. javascript in the header without async/defer attributes
3. javascript with the defer attribute
4. javascript with the async attribute

Also I find the terminology "HTTP/2 push" to be a little misleading as it's really just preloading, not pushing.

**Comment by mavas84** [comment]
Hello @JakeTheSnake3p0 

Thank you for reaching out and I am sorry for the late reply as I was checking this.
I've replied to your email sent via the support channel so please continue the correspondence there so we can avoid duplicating the answer.
I've provided the explanation in the email.
Thanks!
