### ISSUE TITLE
Brotli compression is installed and working but displayed as "not installed"

### ISSUE THREAD

**Issue by simplenotezy** [W3EDGE/w3-total-cache#46]
I have successfully installed brotli compression on my nginx server, restarted the nginx server, and cleared any cache.

However, when I go to "Compatibility Test" it is displayed as `Not Installed`:
![image](https://user-images.githubusercontent.com/3786627/65138849-ec920a00-da0b-11e9-8d0a-b4ddf503d479.png)

When I `curl -IL https://staging.mysite.com -H "Accept-Encoding: br"` I successfully receive: `Content-Encoding: br`

What could be the cause of this?

**Comment by gidomanders** [comment]
As the readme of this repository suggests:
> This repository is not suitable for support. Please don't use our issue tracker for support requests. Support can take place through the appropriate channels

But you can find the answer here:
https://wordpress.org/support/topic/brotli-not-enabled-even-though-server-supports-it-2/
