### ISSUE TITLE
CloudFront CDN requires objects in bucket to have 'public-read' ACL

### ISSUE THREAD

**Issue by rvodden** [W3EDGE/w3-total-cache#461]
It is possible to have objects stored in an S3 bucket publically accessible over HTTPS, and this is the mechanism used by the S3 CDN; however, when serving objects from an S3 bucket via CloudFront there is no reason to have objects publically exposed. The current implementation of the CloudFront CDN reuses the S3 CDN engine and hard codes the 'public-read' ACL onto all uploads. If an S3 bucket which has had all public access disabled (which is to be encouraged when serving via CloudFront) then all uploads fail.

Also the `_get_origin` function on the CloudFront CDN Engine returns the incorrect URL if the bucket region is not us-east-1.

Steps to replicate:

1. Create an S3 bucket in eu-west-1
1. Disable all public access
1. Create a cloudfront distribution
1. Create an origin within that distribution which refers to the created bucket
1. Create an IAM role with the correct perms on the bucket
1. Setup w3-total-cache with a CF CDN, those perms and the bucket name, then hit the test button

 I have the makings of a PR to resolve this by adding a "Public Objects" option to the CloudFront CDN configuration.

**Comment by mavas84** [comment]
Hello @rvodden 

Thank you for taking the time to create a PR.
The devs will make sure to check and review the PR.
Thank you for your patience.
Reference topic: https://wordpress.org/support/topic/cannot-upload-to-s3-2/

**Comment by rvodden** [comment]
PR is here, obviously, comments are most welcome.

https://github.com/W3EDGE/w3-total-cache/pull/462
