### ISSUE TITLE
Image Service Page 404 on multisite.

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#464]
In a Multisite environment when the Image Service is activated,  the settings page can't be reached (throws a 404 error).

**Comment by Chaky74** [comment]
(I'm the original bug reporter)
There is a workaround I've eventually discovered: it can be reached via media->Total Cache Image Service on each site. Only the Network Admin->Performance->Extensions->Image Service Settings path throws a 404 error

**Comment by cssjoe** [comment]
The Image Service is meant to be used per site.  We'll remove the `Settings` and `Media Library` links in the extension card when in network admin.
