### ISSUE TITLE
WP 5.9 - not automatically redirected to Setup Guide

### ISSUE THREAD

**Issue by nicolepaschen** [W3EDGE/w3-total-cache#466]
In WP 5.8 when I click on Performance > Dashboard for the first time I am taken to the Setup Guide. 

In WP 5.9 I am not automatically redirected I just go to the dashboard.

**Comment by cssjoe** [comment]
Cannot replicate on a fresh 5.9.3 install.  The logic is a little complex -- https://github.com/W3EDGE/w3-total-cache/blob/master/Generic_Plugin_Admin.php#L274-L280
