### ISSUE TITLE
Add more query params to ignore for caching

### ISSUE THREAD

**Issue by Mte90** [W3EDGE/w3-total-cache#470]
List: https://github.com/mpchadwick/tracking-query-params-registry/blob/master/_data/params.csv

**Comment by mavas84** [comment]
Hello @Mte90 

Thank you for reaching out.
I see that you also commented on https://github.com/W3EDGE/w3-total-cache/issues/137 regarding a similar suggestion.
Thank you for your for sharing more information.

**Comment by Dobermann6** [comment]
It is a very good suggestion as currently Page Cache simply does not work at all for Google Ads and other advertising platforms as they always pass unique GET parameters such as gclid.

It would be super useful if there will be a way to ignore these parameters and use a cached version of the page for requests containing these parameters
Something like:
For url
https://website.com/page1/example2/?utm_source=cpc&utm_campaign=newcapaign&anotherparameter=justtestparameter&gclid=123456789

ignore gclid parameter and 
a.	use cached https://website.com/page1/example2/ for the URL above
or
b.	use cached  https://website.com/page1/example2/?utm_source=cpc&utm_campaign=newcapaign&anotherparameter=justtestparameter
