### ISSUE TITLE
DigitalOcean Spaces using DO generated ssl certificate not working

### ISSUE THREAD

**Issue by tiberiumihai** [W3EDGE/w3-total-cache#473]
Hello,

I'm trying to configure W3TC with DigitalOcean Spaces.

Selected Amazon S3 Bucket Compatible, added my configuration:
```
Api host: ams3.digitaloceanspaces.com
Access key: ****
Secret key: ****
Bucket: cdn.mydomain.com
SSL support: Always use SSL
Replace site's hostname with: cdn.mydomain.com
```

In DigitalOcean I've generated a ssl certificate for `cdn.mydomain.com` subdomain, and the name of the bucket in DO is `cdn.mydomain.com`.

And when I'm testing S3 cdn configuration I'm receiving this:
```
Error: Unable to put object (S3Compatible::putObject(): [60] SSL: no alternative certificate subject name matches target host name 'cdn.mydomain.com.ams3.digitaloceanspaces.com').
```

PS: On my domain server I'm using apache and I have generated ssl certificate available only for `mydomain.com` and `www.mydomain.com`.

And `cdn.mydomain.com` is a dns CNAME ALIAS for `cdn.mydomain.com.ams3.digitaloceanspaces.com`.

Is this a bug in W3TC?

Thanks!

**Comment by tiberiumihai** [comment]
Here are my findings:
- when using a name like `cdn.mydomain.com` this in DO for the bucket name, doesn't work -> receiving: `Error: Unable to put object (S3Compatible::putObject(): [60] SSL: no alternative certificate subject name matches target host name 'cdn.mydomain.com.ams3.digitaloceanspaces.com').`;
- when using a name like this `cdn-mydomain-com` in DO for bucket name, doesn't work -> receiving: `Error: Unable to put object (S3Compatible::putObject(): [411] Unexpected HTTP status).`

I think this bug is related to https://github.com/W3EDGE/w3-total-cache/issues/243

**Comment by mavas84** [comment]
Hello @tiberiumihai 

Thank you for reaching out and for taking the time to report this.
As you already know, we already have an issue open for this. Please add any comments there so we can avoid duplicating the tickets and keep all the information in one place.
Thanks!
