### ISSUE TITLE
CloudFront distribution not found if using regional s3 origins

### ISSUE THREAD

**Issue by fdobrovolny** [W3EDGE/w3-total-cache#475]
If I set up CloudFront manually from the console by default the regional AWS s3 address is used (`xxx.s3.eu-west-1.amazonaws.com`). However, with this address, the plugin does not find the distribution it looks only for the global address (`xxx.s3.amazonaws.com`).

**Comment by mavas84** [comment]
Hello @fdobrovolny 

Thank you for reaching out and I am sorry for the late reply.
Please make sure that the bucket permission is set to public. Also, you can try to create distribution via the plugin in Performance>CDN settings. 
I hope this helps.
