### ISSUE TITLE
[Bug] Minify library not adding semicolons

### ISSUE THREAD

**Issue by joe9663** [W3EDGE/w3-total-cache#48]
**Context**
When JS files are minified the new line characters at the end of a line are not being replaced with semicolons.  Problem was witnessed when used with WooCommerce.

**Example**
woocommerce-gateway-paypal-express-checkout/includes/settings/settings-ppec.php:127
`if ( button_size_option.prop( 'disabled' ) !== isVertical ) {
    button_size.removeClass( 'enhanced' )
    button_size_option.prop( 'disabled', isVertical );
    $( document.body ).trigger( 'wc-enhanced-select-init' );
    ! button_size.val() && button_size.val( 'responsive' ).change();
}`

Turns into:
`if(button_size_option.prop('disabled')!==isVertical){button_size.removeClass('enhanced')button_size_option.prop('disabled',isVertical);$(document.body).trigger('wc-enhanced-select-init');!button_size.val()&&button_size.val('responsive').change();}`

There is no semicolon separating `button_size.removeClass( 'enhanced' )` and `button_size_option.prop( 'disabled', isVertical );` in the minified version.

**Comment by thefool** [comment]
I suggested a quick fix [here](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/617) since it's just a semicolon, but the bug lies with the minifier W3TC uses, as newlines without semicolons are still valid JS...
