### ISSUE TITLE
Lazy Load Bug

### ISSUE THREAD

**Issue by serdarwork** [W3EDGE/w3-total-cache#483]
Hello,

If the lazy loading feature enabled and you change quantity of a product in the cart page, images always dissappear. These kind of Ajax requests are not compatible with lazy loading.

[![woocommerce-lazy-load-cart54b04e15544912a2.png](https://s3.imgbu.com/file/imgbucom-s/2022/02/06/woocommerce-lazy-load-cart54b04e15544912a2.png)](https://imgbu.com/i/YG53w)

Kind regards,
Serdar

**Comment by serdarwork** [comment]
Hi @mavas84 

I tried to exclude the button by adding a word called `"name="update_cart"` or `update_cart` in Performance>User Experience>Exclude Words field. Excluding buttons has no any affect on images on the cart page. So, it did not work.

Unfortunately, product images in the cart page has no a specific class name.

**Comment by serdarwork** [comment]
Browser fetches a new data from stratch when I update my cart by changing product quantity. However, as seen below the image link is not there after fetching a new data.

[![woo-update-cart2012849e901e3268.png](https://s3.imgbu.com/file/imgbucom-s/2022/02/10/woo-update-cart2012849e901e3268.png)](https://imgbu.com/i/YGz2R)

**Comment by mavas84** [comment]
Hello @serdarwork 

Thank you for the information.
Can you please try adding a class for those thumbnails to Performance>User Experience>Exclude words:
`attachment-woocommerce_thumbnail`
Save all settings and purge the cache and let me know if the problem persists.
Thanks!

**Comment by serdarwork** [comment]
@mavas84 It fixed the issue, thank you! It also disabled lazy loading for the thumbnails in product pages because the `attachment-woocommerce_thumbnail` class is also used by all WooCommerce thumbnails. I created this issue to notify you about a common bug for all WooCommerce websites that use AJAX. However, like you said if it's not a general issue, then we can say no bug here.

Once again thank you for your helps!

Regards,
Serdar

**Comment by mavas84** [comment]
Hello @serdarwork 

You are most welcome. As you can see the class also contains `size-woocommerce_thumbnail lazy`. 
Adding `lazy` to Performance>User Experience>Exclude words: may also help for those thumbnails as woo may be lazyloading those attachments. So most likely there is a conflict.
Thanks!
