### ISSUE TITLE
WooCommerce product Gallery ajax not working with CDN host attachments enabled.

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#485]
The problem occurs in that some images are rendered via an ajax request when the user makes a gallery selection. Those images are then rendered but not being served by the CDN.
Also, the Variation Image Gallery is not working as it should
https://www.dropbox.com/s/wxag9fecysinz1c/Screen%20Recording%202022-02-09%20at%2017.46.57.mov?dl=0
Reference links: https://wordpress.org/support/topic/woocommerce-variation-image-gallery-change/

**Comment by maxicus** [comment]
that can be an extension passing urls plugin generates through e.g. wp_prepare_attachment_for_js.
