### ISSUE TITLE
Jenkins / Bash trigger

### ISSUE THREAD

**Issue by HaziFlorinMarian** [W3EDGE/w3-total-cache#493]
Hello!
I would like to know if there is a possibility to run the cache cleanup from the command line.
I intend to clear the cache automatically each time I deploy it to the production server, without having to manually run the cleanup.
Thank you!

**Comment by mavas84** [comment]
Hello @HaziFlorinMarian 

Thank you for reaching out and I am happy to assist you with this.
You can youse WP_Cli for to purge the cache.
  ```
 usage: wp w3-total-cache cdn_purge
   or: wp w3-total-cache fix_environment [<server>]
   or: wp w3-total-cache flush <cache> [--post_id=<id>] [--permalink=<post-permalink>]
   or: wp w3-total-cache import <filename>
   or: wp w3-total-cache opcache_flush
   or: wp w3-total-cache option <operation> <name> [<value>] [--state] [--master] [--type=<type>] [--delimiter=<delimiter>]
   or: wp w3-total-cache pgcache_cleanup
   or: wp w3-total-cache pgcache_prime [--start=<start>] [--limit=<limit>]
   or: wp w3-total-cache querystring
```
I hope this helps!
