### ISSUE TITLE
PHP Warning related to outdated CSS Tidy Version

### ISSUE THREAD

**Issue by geraldurbas** [W3EDGE/w3-total-cache#495]
PHP Notice:  Uninitialized string offset: 0 in /wp-content/plugins/w3-total-cache/lib/CSSTidy/class.csstidy_print.php on line 240

Used version: 1.1.0
Latest Versions from https://github.com/Cerdic/CSSTidy
1.7.3 / 2.01 out too

Consider upgrade / this is a big gap...

**Comment by mavas84** [comment]
Hello @geraldurbas 

Thank you for reaching out and I am happy to assist you with this.
The CSSTidy library was updated to [1.7.3.](https://github.com/W3EDGE/w3-total-cache/commit/cf66cc591f0340cba12d929186287b73e738c738) last January (Jan 7th, 2021) as you can also see in the GH issue related. https://github.com/W3EDGE/w3-total-cache/issues/274
Can you please share which PHP version you are using?
We'll make sure to update the CSS Tidy to the latest v2.0.0

Thanks!
