### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: flock(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by mvazquez** [W3EDGE/w3-total-cache#499]
I'm receiving a fatal php error when file locking is enabled, on every cache clear or post/page modification. The error is this:
PHP Fatal error:  Uncaught TypeError: flock(): supplied resource is not a valid stream resource in /var/www/wp-content/plugins/w3-total-cache/Cache_File.php:246 [....]

This is happening to me with php 8.1, in the previous webserver whith the same settings (file locking on), but with php 7.4 it did not happened.

Could this be an error because the cache file is unlocked after it is closed? There are 3 places where locks are released on that file (Cache_File.php), in two of them the lock is released after the cache file is closed, and on the other it is unlocked before the fclose.

https://github.com/W3EDGE/w3-total-cache/blob/7af6d749297ce6265b6dc50d808fc773c66b1385/Cache_File.php#L246

**Comment by mavas84** [comment]
Hello @mvazquez 

Thank you for reaching out and I am happy to help!
`fclose()` releases the file lock.  Also, `flock( $fp, LOCK_UN ); `should be called before `fclose( $fp );`
The lock is released also by [fclose()](https://www.php.net/manual/en/function.fclose.php), or when stream is garbage collected.
This indicates that the garbage collection -  meaning that something may be performing garbage collection during that operation.
We've tested the locking in PHP 8.0.18 and 8.1.5; didn't see an issue.
What you may want to try is to lower the PHP version and see if the problem still persists.
Thanks!
