### ISSUE TITLE
[Feature] Add filters to modify header when using Disk: Enhanced

### ISSUE THREAD

**Issue by joe9663** [W3EDGE/w3-total-cache#50]
**Description**
Currently there are no filters users can utilize to include/exclude specific items getting added to the header when using Disk: Enhanced.

**Feature**
Allow users to make modifications in functions.php with filters that will alter header information.

**Comment by maxicus** [comment]
implemented by https://github.com/W3EDGE/w3-total-cache/commit/6c0204143e5c51e5b8b762c1aa3001ff26fb321d
