### ISSUE TITLE
`db-cluster-config.php` does not work for non network mode

### ISSUE THREAD

**Issue by jpSimkins** [W3EDGE/w3-total-cache#506]
I have a single "blog" website. I am NOT using "network mode". I was instructed when I bought this that this still works if I put the `db-cluster-config.php` in the `wp-content` location. I have done this and this does not work.

I have already set the `define('W3TC_PRO_DEV_MODE', true);` in my `wp-config.php` and set the license in the setting page.

I am testing on my local DEV since I am already using HyperDB to have a multi-node deployment of WordPress running in Fargate on PROD. I have a local DB cluster setup for DEV too. I need to verify this will work on DEV before I even consider putting this on PROD.

I have removed HyperDB and added the drop-in for W3TC `db.php` and placed the `db-cluster-config.php`. I can verify through debugging that I am hitting the `db.php` drop-in as expected. I am never hitting the `db-cluster-config.php` file in debug.

Support told me:
> As for the DB cluster, initially, this was intended to network mode, however, it can be used in the single-blog setups, but the mentioned check-box will not be visible, however, once the dbcluster-config-sample.php file is edited and  placed in /wp-content/db-cluster-config.php - it starts to work

But this seems to be missing that the `db.php` needs to be in place as well. Which is obvious but was not mentioned. The only way the `db-cluster-config.php` is loaded, is when the `db.php` file is present. If you remove it, it will not load `db-cluster-config.php`.

So I have the files in place. I added this to the `db-cluster-config.php`:
```php
if (defined('DB_READ_HOST')) {
    // Overrides the databases key above
    $w3tc_dbcluster_config['databases'] = array(
        'master' => array(
            'host'     => DB_HOST,
            'user'     => DB_USER,
            'password' => DB_PASSWORD,
            'name'     => DB_NAME,
            'write'    => true,
            'read'     => false,
        ),
        'slave' => array(
            'host'     => DB_READ_HOST,
            'user'     => DB_USER,
            'password' => DB_PASSWORD,
            'name'     => DB_NAME,
            'write'    => false,
            'read'     => true,
            'timeout'  => 0.3,
        ),
    );
}
```
I modified this since the commented out sections replaced `$w3tc_dbcluster_config` which would result in the other indexes being removed. e.g. `persistent`, `check_tcp_responsiveness`, ...

I tested with original uncommitted code and my changes but it's never worked as this file is never processed.

I do have `DB_READ_HOST` defined but this still isn't working. This is the same config I used with HyperDB so it should work but I get nothing.

Again, when debugging, I never get to the `db-cluster-config.php` file.

Any suggestions? Or at least an ETA to when this will be properly supported other than coming soon?

Thanks for your time.

---

**Note:** Support has reached out to me and the issues I had with email support was due to me mistyping my email in the contact form. Therefore I removed this section as it was user error on my part.

--- 

## UPDATE

I discovered that this isn't working due to `W3TC_PRO` not being defined. For now, I set this to `true` and I now get this to load the `db-cluster-config.php` file but it just errors out with: 

> PHP Fatal error:  Uncaught Error: Object of class W3TC\DbCache_WpdbNew could not be converted to string in /var/www/html/wp-content/plugins/w3-total-cache/Enterprise_Dbcache_WpdbInjection_Cluster.php:873

I removed my code wrapped with `DB_READ_HOST` and see that even with the default setting, this is causing the same error above.

 Still investigating.

---

## UPDATE 2

The error above is due to:

`Enterprise_Dbcache_WpdbInjection_Cluster.php` Line: 872:
```php
		if ( !empty( $this->wpdb_mixin->charset ) ) {
			$collation_query = "SET NAMES '$this->wpdb_mixin->charset'";
			if ( !empty( $this->wpdb_mixin->collate ) )
				$collation_query .= " COLLATE '$this->wpdb_mixin->collate'";
			mysqli_query( $this->wpdb_mixin->dbh, $collation_query );
		}
```
Should be using:
```php
		if ( !empty( $this->wpdb_mixin->charset ) ) {
			$collation_query = "SET NAMES '{$this->wpdb_mixin->charset}'";
			if ( !empty( $this->wpdb_mixin->collate ) )
				$collation_query .= " COLLATE '{$this->wpdb_mixin->collate}'";
			mysqli_query( $this->wpdb_mixin->dbh, $collation_query );
		}
```

Since it is using object variables in a string, you need to wrap them with `{}`. This is due to using `$this->wpdb_mixin->charset` as `$this->wpdb_mixin` would work as is (if it were a string, but it's an object so it won't here, just an example) but since you are using another varaible within `wpdb_mixin`, you need to add the `{}`. This shouldn't matter if this is in "network mode" or not, I wonder how many people actually use this feature? It's broken as is.

The site now partially loads... but it's still not working properly. Seems like pagination is not working.

I have also tried commenting out my `DB_READ_HOST` section and have it just using the default DB setup. This shows the same issues. If I switch my branch back to HyperDB, no issues. Still looking into this. The concern now is that there isn't any error logs being written so this will be a bit tricky to isolate.

I'll see if I can identify the latest issue.

---

## UPDATE 3

Seems like the cause of the issue in **UPDATE 2** is due to `$wpdb->found_posts` not returning the proper value. It returns `1` when it should be showing pretty much anything else. It returns `1` when it should be `0`, `6`, `11`, `1,200`, etc. It seems to always return `1`. It's funny since `$wpdb->post_count` is showing the value returned and `$wpdb->found_posts` is never changing from `1`. So when `$wpdb->post_count` shows `6`  `$wpdb->found_posts` still shows only `1`.

This is the reason all custom post types (seems Pages works and I don't use Posts) no longer have pagination in the WP-Admin section either. This is affecting almost all results, not just custom queries (something I originally thought). The reason Posts/Pages works could be due to the way WordPress is doing them internally.  Media pagination is broken too. Also, all taxonomies pagination is broken too in WP Admin.

Not sure why this is the case, again, this worked perfectly fine before. It's just the DB cluster of W3TC causing these issues (to be clear this isn't an issue with anything else). 

The queries are just returning bad data so WordPress doesn't know how to paginate. This is affecting me since my home page is a paginated result. 

Still looking around but it seems this is the reason for bad data. I'll see if I can figure out why this is happening. I'll pick up on this tomorrow. I'm surprised this isn't a known issue, this is completely broken.

---

## UPDATE 4

Still looking into the issue but I did want to make note that the `$w3tc_dbcluster_config['databases']` index is not used as expected.

For this example, I will just use the default setup and not have the slave added yet.

I changed my `DB_PASSWORD` constant to be the incorrect password and hard-coded it into the config: 
```php
	'databases' => array(
		'master' => array(
			'host'     => DB_HOST,     // If port is other than 3306, use host:port.
			'user'     => DB_USER,
			'password' => 'password',
			'name'     => DB_NAME
		)
	),
```
 I get the error:

 > We were unable to select the database.

This is not expected behavior and should be noted.

This is strange because I would expect a "Could not connect to the database" error but that is not the case here. Again, the only change is the `DB_PASSWORD`. 

It's possible the config is not really a config and `DB_PASSWORD` is still used in the code. Again, I would expect a different error.

**Comment by mavas84** [comment]
Hello @jpSimkins 

Thank you for taking the time to report this.
First, I've replied to the existing email chain and provided an explanation of how the support works for W3 Total Cache, and the fact that the last email you sent did not have the correct email address (since this is a public repository I will not share that info here as I've already shared it via email). I've also explained that the best way to reach out to the support is via the plugin in Performance>Support as you have multiple free options like "Submit a Bug Report (Free)".

As for the DB cluster issue you are experiencing, we'll make sure to run tests for this and make sure everything is covered. It would be great if you could share more details about the website and the environment as I've mentioned in the email so we can have proper insights into the use case.

I am sorry again for any inconvenience and thank you for your patience.

**Comment by jpSimkins** [comment]
Thank you @mavas84 

Although I was working on a vanilla website, I decided to try this again. As before, I just copied my files from my other project. 

This time, I installed a fresh version of WP and installed W3TC from the admin plugins management system. I activated W3TC, added the constants:

```php
define('W3TC_PRO_DEV_MODE', true);
define('W3TC_PRO', true);
```

I then saved my license key in W3TC settings.

As expected, the site shows:

> W3 Total Cache is currently running in Pro version Development mode.

I then added the `db-cluster-config.php` file but it doesn't work. Since I already figured out this requires the `db.php`, I added that next. 

Now the site is trying to get me to reinstall WP. It's like it isn't aware of my `wp-config.php` file existing.

This is another bug that needs to be reported. It seems it is only looking in the `wordpress` directory for the `wp-config.php` and not one level higher which is supported by WordPress.

If this helps, I am using a custom `wp-content` directory and my `wp-config.php` is outside the `wordpress` directory. 
This looks like:

```
├── .htaccess
├── index.php
├── wordpress
│   └── ...
├── wp-config.php
└── wp-content
    ├── advanced-cache.php
    ├── cache
    ├── db-cluster-config.php
    ├── db.php
    ├── plugins
    ├── themes
    ├── upgrade
    └── w3tc-config
```

I will continue to look into this and see if I can find where this is happening.

**Comment by jpSimkins** [comment]
It seems pagination is broken due to the way `SELECT FOUND_ROWS()` is being called. In `Enterprise_Dbcache_WpdbInjection_Cluster` in the `query` method, there is:

```php
$this->wpdb_mixin->_last_found_rows_result = mysqli_query( $this->wpdb_mixin->dbh, "SELECT FOUND_ROWS()" );
```

This is wrong. You need to fetch the num rows. This should be:

```php
$this->wpdb_mixin->_last_found_rows_result = mysqli_num_rows( $this->wpdb_mixin->dbh, "SELECT FOUND_ROWS()" );
```

Making this change now gets pagination working as expected.

I am very concerned over the state of this so I am skeptical to add this to our project. I am going to work through the rest of this to ensure there are no issues. Given my PRODuction site has very high traffic, I am not feeling too good about using this on it yet. I will need to test this a lot more before I feel safe using it.

**Comment by jpSimkins** [comment]
Submitted a PR to fix issues with this as this is definitely affecting anyone using this. This is currently broken in it's current state.

**Comment by jpSimkins** [comment]
This fix is only fixing the `db-cluster-config.php` to work. When you enable DB cache, the site crashes. I am looking into that now
