### ISSUE TITLE
Bad anchor link - #fragmentcache

### ISSUE THREAD

**Issue by bwmarkle** [W3EDGE/w3-total-cache#51]
I had someone report this issue to me. I don't recall exactly where it is, but there's a bad anchor link.

**Bad link**:
`/wp-admin/admin.php?page=w3tc_general&w3tc_message=12345#fragmentcache`

**Fix**:
`/wp-admin/admin.php?page=w3tc_general&w3tc_message=12345#fragment_cache`

Notice the `#fragmentcache` vs. `#fragment_cache`

**Comment by maxicus** [comment]
fixed by https://github.com/W3EDGE/w3-total-cache/commit/038dfe0c8f2da7b7b56892d5d1dbb2a2427e818e
