### ISSUE TITLE
BUG: When using WPML, W3TC is always in Spanish, no matter what language I am in

### ISSUE THREAD

**Issue by jpSimkins** [W3EDGE/w3-total-cache#510]
Hello,

I have WPML installed and W3TC. 

I have WPML configured for Spanish first and English second. The Admin user is always in English.

I have noticed that no matter what I do, I am only seeing W3TC as Spanish. I tested this on 2 sites. One with 20+ plugins and another with just WPML and W3TC. Both sites show W3TC in Spanish only (the site with 20+ plugins shows all other plugins as I expect in the correct language, just not W3TC). I have no way to see this in English.

I went ahead and created a vanilla site with just W3TC and WPML, when you set the primary language as Spanish, W3TC stays in Spanish no matter what I change my user language setting to. I have tried purging all caches. I even disabled W3TC caching and even tried deactivating (and deleting the cache directory) then reactivating the plugin. Still, I am stuck in Spanish.

I have found many posts online about this and the suggestions seem to be:
- Change the language in Settings->General
   - This is not ideal as this is changing the site's primary language. This has consequences and should not be recommended
     - With WPML installed, this has a link to WPML to change the language settings. There is nothing wrong with the language settings.
- Remove the .mo files in the plugin
   - This is a hack, not a fix. 

What I expect is that W3TC would obey the language setting in the WP Admin. WPML adds a language selector to easily switch between the languages in the admin. Also, each user has a language option in their profile that allows them to say, only show in English. This is not being obeyed either.

I don't think I can assist with this fix as I just don't have the time right now. Please look into this issue as this isn't very serious but currently makes managing W3TC very tedious and I need to use google translate to understand what is going on.

FYI: I also have this issue with not going to Spanish when English is the default language.

I hope this helps

**Comment by mavas84** [comment]
Hello @jpSimkins 

Thank you for reaching out and thank you for taking the time to create this ticket.
This is added to a backlog and the devs will look into this.
Thanks!
