### ISSUE TITLE
ErrorException: Trying to get property 'post_type' of non-object

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#515]
The problem occurs randomly when the ACF fields are edited.
Reference topic: https://wordpress.org/support/topic/trying-to-get-property-post_type-of-non-object-11/

**Comment by Striffly** [comment]
This occurs for ACf fields, but also with menu.
Steps to reproduce : 
- Bedrock + Sage installation, with W3 Total Cache composer install
- Use **only** page caching with Redis
- Add page to menu
- Error occured

![image](https://user-images.githubusercontent.com/13284087/175033019-6196b32e-9f99-413b-bfdc-1ff1c1aafdf8.png)
