### ISSUE TITLE
Add an exception to white list ip's of other plugins possible?

### ISSUE THREAD

**Issue by ghvick** [W3EDGE/w3-total-cache#516]
Hello - This W3TC plugin is intercepting a process of our other plugin called Codisto. When we deactivate W3TC our other plugin does the job of pushing orders through from Amazon to our Woo. Is there a way to include an exception or white list Codisto ip's?
---------------------------------------------------------------------------------------------------------------------------------------------
![unnamed](https://user-images.githubusercontent.com/107086733/172509342-fed5bef4-7704-4aba-a1d3-3fee882c8570.png)

<h1 style="margin-top: 0;">We're sorry, you are not allowed to proceed</h1>
                    <p>Your request looks suspiciously similar to automated requests from spam posting software or it has been denied by a security policy configured by the website administrator.</p>
                    <p>If you believe you should be able to perform this request, please let us know.</p>
                    <p style="margin-top: 2em;">
<!--
Performance optimized by W3 Total Cache. Learn more: https://www.boldgrid.com/w3-total-cache/

**Comment by mavas84** [comment]
Hello @ghvick 

Thank you for reaching out.
Can you please confirm this message you are getting is coming from [this security plugin](https://wordpress.org/plugins/wp-cerber/)?
Can you please disable the settings one by one in Performance>general settings, save the settings and purge the cache after each setting is disabled and see which one might be causing the issue?

Thanks!
