### ISSUE TITLE
Redis caching is having PHP warnings from anywhere on the site be escalated to a fatal server error

### ISSUE THREAD

**Issue by KZeni** [W3EDGE/w3-total-cache#523]
I had a stream of debugging & discovery at https://wordpress.org/support/topic/redis-object-db-cache-causes-fatal-error-with-redux-framework/.

There's also another person that appears to be encountering this at https://wordpress.org/support/topic/error-version-2-2-2-update-breaks-total-cache-admin-pages/

Basically, whatever changes were made to Cache_Redis.php from version 2.2.1 to 2.2.2 make it so any PHP warning site-wide becomes a fatal server error. For example, something like a function deprecation warning suddenly has that triggering a fatal error... same goes for a warning about an undefined index, a function not providing all arguments [even though the current PHP version, ex. pre-8.x, doesn't require that], REST API having a missing argument, etc... these were all previously PHP warnings/notices that were problem-free until W3TC v2.2.2 with Redis being used has those instances be escalated to force them to be fatal server errors so the page doesn't even load.

This is confirmed as happening on PHP 7.2, but it might be affecting other PHP versions (haven't confirmed with others.)

**Comment by KZeni** [comment]
I literally took the Cache_Redis.php file from 2.2.1 and overwrote the one in 2.2.2 with that. Gave the plugin a version number of 2.2.2.1 and used wp-cli to force-install that as the patched version. Resolved the issue for now (with that then able to be distributed in bulk across my 100+ sites with W3TC and Redis.)

**Comment by pietervanuhm** [comment]
> Same to me here.
> 
> Running on PHP 7.4.30
> 
> https://wordpress.org/support/topic/after-update-2-2-2-wordpress-breaks-totally/

For now downgraded to 2.2.1 untill patch update.

**Comment by mavas84** [comment]
Hello @KZeni @pietervanuhm 

Thank you for taking the time to report this and I am sorry about the issue you are experiencing. The devs will be looking into this ASAP.
Once again thank you for reporting the problem with so many details and thank you for your understanding and patience.

**Comment by KZeni** [comment]
@mavas84 Thanks for the update & jumping on the issue!

**Comment by MarcLob** [comment]
Ho ho...!
Same issue here.
I have to deactivate the extension.
Here is the error log.
I have removed some of the "Connection refused" to many.

[28-Jun-2022 14:11:47 UTC] Connection refused
[28-Jun-2022 14:11:49 UTC] Connection refused
[28-Jun-2022 14:11:49 UTC] Connection refused
......

[28-Jun-2022 14:11:52 UTC] PHP Fatal error:  Uncaught ErrorException: rmdir(/home/****/public_html/wp-content/cache/object/198/1dd): Directory not empty in /home/****/public_html/wp-content/plugins/w3-total-cache/Cache_File_Cleaner.php:85
Stack trace:
#0 [internal function]: W3TC\Cache_Redis->W3TC\{closure}()
#1 /home/****/public_html/wp-content/plugins/w3-total-cache/Cache_File_Cleaner.php(85): rmdir()
#2 /home/****/public_html/wp-content/plugins/w3-total-cache/Cache_File_Cleaner.php(76): W3TC\Cache_File_Cleaner->_clean()
#3 /home/****/public_html/wp-content/plugins/w3-total-cache/Cache_File_Cleaner.php(76): W3TC\Cache_File_Cleaner->_clean()
#4 /home/****/public_html/wp-content/plugins/w3-total-cache/Cache_File_Cleaner.php(48): W3TC\Cache_File_Cleaner->_clean()
#5 /home/****/public_html/wp-content/plugins/w3-total-cache/ObjectCache_Plugin.php(139): W3TC\Cache_File_Cleaner->clean()
#6 /home/****/public_html/wp-includes/class-wp-hook.php(307): W3TC\ObjectCache_Plugin->cleanup()
#7 /home/****/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#8 /home/****/public_html/wp-includes/plugin.php(524): WP_Hook->do_action()
#9 /home/****/public_html/wp-cron.php(138): do_action_ref_array()
#10 {main}
  thrown in /home/****/public_html/wp-content/plugins/w3-total-cache/Cache_File_Cleaner.php on line 85
[28-Jun-2022 14:11:52 UTC] Connection refused
[28-Jun-2022 14:11:52 UTC] Connection refused
[28-Jun-2022 14:11:52 UTC] Connection refused
.....

[28-Jun-2022 14:12:00 UTC] PHP Fatal error:  Uncaught ErrorException: file_get_contents(/home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/assets/css/wp-page_navi.css): Failed to open stream: No such file or directory in /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php:39
Stack trace:
#0 [internal function]: W3TC\Cache_Redis->W3TC\{closure}()
#1 /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php(39): file_get_contents()
#2 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(1112): WP_Filesystem_Direct->get_contents()
#3 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(1052): ET_Dynamic_Assets->get_assets_data()
#4 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(555): ET_Dynamic_Assets->generate_dynamic_assets()
#5 /home/****/public_html/wp-includes/class-wp-hook.php(307): ET_Dynamic_Assets->initial_setup()
#6 /home/****/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#7 /home/****/public_html/wp-includes/plugin.php(524): WP_Hook->do_action()
#8 /home/****/public_html/wp-includes/class-wp.php(787): do_action_ref_array()
#9 /home/****/public_html/wp-includes/functions.php(1330): WP->main()
#10 /home/****/public_html/wp-blog-header.php(16): wp()
#11 /home/****/public_html/index.php(17): require('/home/****/pub...')
#12 {main}
  thrown in /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 39
[28-Jun-2022 14:12:00 UTC] Connection refused
[28-Jun-2022 14:12:01 UTC] Connection refused
[28-Jun-2022 14:12:02 UTC] Connection refused
.....

[28-Jun-2022 14:12:02 UTC] PHP Fatal error:  Uncaught ErrorException: file_get_contents(/home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/assets/css/wp-page_navi.css): Failed to open stream: No such file or directory in /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php:39
Stack trace:
#0 [internal function]: W3TC\Cache_Redis->W3TC\{closure}()
#1 /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php(39): file_get_contents()
#2 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(1112): WP_Filesystem_Direct->get_contents()
#3 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(1052): ET_Dynamic_Assets->get_assets_data()
#4 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(555): ET_Dynamic_Assets->generate_dynamic_assets()
#5 /home/****/public_html/wp-includes/class-wp-hook.php(307): ET_Dynamic_Assets->initial_setup()
#6 /home/****/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#7 /home/****/public_html/wp-includes/plugin.php(524): WP_Hook->do_action()
#8 /home/****/public_html/wp-includes/class-wp.php(787): do_action_ref_array()
#9 /home/****/public_html/wp-includes/functions.php(1330): WP->main()
#10 /home/****/public_html/wp-blog-header.php(16): wp()
#11 /home/****/public_html/index.php(17): require('/home/****/pub...')
#12 {main}
  thrown in /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 39
[28-Jun-2022 14:12:02 UTC] Connection refused
[28-Jun-2022 14:12:02 UTC] Connection refused
[28-Jun-2022 14:12:02 UTC] Connection refused
....

[28-Jun-2022 14:12:04 UTC] PHP Fatal error:  Uncaught ErrorException: mkdir(): No such file or directory in /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php:545
Stack trace:
#0 [internal function]: W3TC\Cache_Redis->W3TC\{closure}()
#1 /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php(545): mkdir()
#2 /home/****/public_html/wp-content/themes/Divi/core/components/data/Utils.php(390): WP_Filesystem_Direct->mkdir()
#3 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(519): ET_Core_Data_Utils->ensure_directory_exists()
#4 /home/****/public_html/wp-includes/class-wp-hook.php(307): ET_Dynamic_Assets->initial_setup()
#5 /home/****/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /home/****/public_html/wp-includes/plugin.php(524): WP_Hook->do_action()
#7 /home/****/public_html/wp-includes/class-wp.php(787): do_action_ref_array()
#8 /home/****/public_html/wp-includes/functions.php(1330): WP->main()
#9 /home/****/public_html/wp-blog-header.php(16): wp()
#10 /home/****/public_html/index.php(17): require('/home/****/pub...')
#11 {main}
  thrown in /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 545
[28-Jun-2022 14:12:04 UTC] Connection refused
[28-Jun-2022 14:12:04 UTC] Connection refused
[28-Jun-2022 14:12:04 UTC] Connection refused
....

[28-Jun-2022 14:12:05 UTC] PHP Fatal error:  Uncaught ErrorException: file_get_contents(/home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/assets/css/wp-page_navi.css): Failed to open stream: No such file or directory in /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php:39
Stack trace:
#0 [internal function]: W3TC\Cache_Redis->W3TC\{closure}()
#1 /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php(39): file_get_contents()
#2 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(1112): WP_Filesystem_Direct->get_contents()
#3 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(1052): ET_Dynamic_Assets->get_assets_data()
#4 /home/****/public_html/wp-content/themes/Divi/includes/builder/feature/dynamic-assets/class-dynamic-assets.php(555): ET_Dynamic_Assets->generate_dynamic_assets()
#5 /home/****/public_html/wp-includes/class-wp-hook.php(307): ET_Dynamic_Assets->initial_setup()
#6 /home/****/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#7 /home/****/public_html/wp-includes/plugin.php(524): WP_Hook->do_action()
#8 /home/****/public_html/wp-includes/class-wp.php(787): do_action_ref_array()
#9 /home/****/public_html/wp-includes/functions.php(1330): WP->main()
#10 /home/****/public_html/wp-blog-header.php(16): wp()
#11 /home/****/public_html/index.php(17): require('/home/****/pub...')
#12 {main}
  thrown in /home/****/public_html/wp-admin/includes/class-wp-filesystem-direct.php on line 39
[28-Jun-2022 14:12:05 UTC] Connection refused
[28-Jun-2022 14:12:05 UTC] Connection refused
[28-Jun-2022 14:12:05 UTC] Connection refused
....

[28-Jun-2022 14:12:21 UTC] PHP Fatal error:  Uncaught ErrorException: unlink(/home/****/public_html/wp-content/et-cache/image_srcset_sizes.data): No such file or directory in /home/****/public_html/wp-content/themes/Divi/includes/builder/core.php:6949
Stack trace:
#0 [internal function]: W3TC\Cache_Redis->W3TC\{closure}()
#1 /home/****/public_html/wp-content/themes/Divi/includes/builder/core.php(6949): unlink()
#2 /home/****/public_html/wp-content/themes/Divi/includes/builder/functions.php(5050): et_fb_delete_builder_assets()
#3 /home/****/public_html/wp-includes/class-wp-hook.php(305): et_builder_theme_or_plugin_updated_cb()
#4 /home/****/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /home/****/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#6 /home/****/public_html/wp-admin/includes/plugin.php(828): do_action()
#7 /home/****/public_html/wp-admin/plugins.php(209): deactivate_plugins()
#8 {main}
  thrown in /home/****/public_html/wp-content/themes/Divi/includes/builder/core.php on line 6949
[28-Jun-2022 14:12:21 UTC] Connection refused
[28-Jun-2022 14:12:21 UTC] Connection refused
[28-Jun-2022 14:12:21 UTC] Connection refused
....

**Comment by cssjoe** [comment]
We'll have a patch released shortly.  For now, the lines can be removed or commented-out.  Here is the commit removing the lines -- https://github.com/W3EDGE/w3-total-cache/commit/13633db4d3753dcff8a69fabb5310c91f3963cb4
