### ISSUE TITLE
DbCache_WpdbInjection_QueryCaching Fatal error version 2.2.3

### ISSUE THREAD

**Issue by JCHDG** [W3EDGE/w3-total-cache#529]
Wordpress version 4.9.20

PHP 7.4.30

After I import setting I'm getting the following errors.

mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Call to undefined function W3TC\\wp_unslash() in[/wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php]:562

mod_fcgid: stderr: Stack trace:, referer: /wp-admin/plugins.php

mod_fcgid: stderr: #0[/wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php](507): W3TC\\DbCache_WpdbInjection_QueryCaching->_check_request_uri(),

mod_fcgid: stderr: #1[/httpdocs/wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php](424): W3TC\\DbCache_WpdbInjection_QueryCaching->_can_cache_once_per_request()

mod_fcgid: stderr: #2[/wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php](123): W3TC\\DbCache_WpdbInjection_QueryCaching->_can_cache()

mod_fcgid: stderr: #3[/httpdocs/wp-content/plugins/w3-total-cache/DbCache_WpdbLegacy.php](122): W3TC\\DbCache_WpdbInjection_QueryCaching->query()

mod_fcgid: stderr: #4[/httpdocs/wp-includes/wp-db.php](2488): W3TC\\DbCache_WpdbLegacy->query()

mod_fcgid: stderr: #5[/httpdocs/wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php]on line 562

**Comment by mavas84** [comment]
Hello @JCHDG 

I  am sorry for the issue you are experiencing and thank you for taking the time to report this.
Can you please change to following lines in wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php

Line 218
from
`esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) ) : '',`
to
`esc_url_raw( stripslashes( $_SERVER['REQUEST_URI'] ) ) : '',`

and also line 562
from
`filter_var( wp_unslash( $_SERVER['REQUEST_URI'] ), FILTER_SANITIZE_URL ) : '';`
 to:
`filter_var( stripslashes( $_SERVER['REQUEST_URI'] ), FILTER_SANITIZE_URL ) : '';`

Let me know if the issue persists after this.

Thanks!

**Comment by JCHDG** [comment]
Thank you. I've replace all instances of wp_unslash with stripslashes and now the site doesn't crash.

Found it on lines 218, 449 and 562.

Is this something that is going to be patched in the future?

**Comment by cssjoe** [comment]
@JCHDG Thank you for testing our fix.  The updated file https://github.com/W3EDGE/w3-total-cache/blob/60f3a217f6ff9f547be7c1c225dac967e2f5f3bd/DbCache_WpdbInjection_QueryCaching.php includes changes to lines 218 and 562.  Line 449 is run in an Ajax call, so a change there should not be needed.
@mavas84 Thank you for coordinating and submitting the pull request.
These changes will be included in the next patch release 2.2.4.

**Comment by cssjoe** [comment]
@JCHDG Thank you.  We'll update that line as well.
