### ISSUE TITLE
PHP warning about pconnect() expecting at most 5 parameters with 6 given on some setups

### ISSUE THREAD

**Issue by KZeni** [W3EDGE/w3-total-cache#533]
I'm currently getting:
```
PHP Warning:  Redis::pconnect() expects at most 5 parameters, 6 given
```
on a server running PHP 7.2 with phpredis 3.1.1 (via php72-pecl-redis).

This resulted in ~50 GB of error_log entries each day (on a server with multiple sites that are affected) which the previous W3TC version didn't have (pre-2.2.2).

I have provided additional details, gone through troubleshooting, and have come up with a PR to ideally resolve the issue here: https://github.com/W3EDGE/w3-total-cache/pull/532 (this should hopefully allow the logs to take place & instead look to prevent the issue that the warning's for [check phpredis version & then provide more parameters to pconnect if it's new enough to support it while then falling back to a lesser set, if not.])

I've also posted this on the WP.org support forums here: https://wordpress.org/support/topic/php-warning-about-pconnect-expecting-at-most-5-parameters-with-6-given/ (just keeping things tied together.)

**Comment by mavas84** [comment]
Hello @KZeni 

Again, thank you for taking the time to create PR and to report this.
The PR review is pending.
Thanks!

**Comment by KZeni** [comment]
FYI, I can report that this update does have my server back to normal log usage rather than 10s of GB per day due to phpredis' pconnect being given more attributes than expected (with the front-end page source comments showing Redis is still utilizing caches).

@mavas84 Thanks for following up!
