### ISSUE TITLE
mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Call to undefined function W3TC\\esc_url_raw()

### ISSUE THREAD

**Issue by JCHDG** [W3EDGE/w3-total-cache#547]
2,2,4 Error

mod_fcgid: stderr: PHP Fatal error: Uncaught Error: Call to undefined function W3TC\\esc_url_raw() in /httpdocs/wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php:600

Looks like esc_url_raw()  was placed in a spot it wasn't in before. Previously it was filter_var().

On line 600 I changed esc_url_raw to filter_var and it fixed the fatal error.

**Comment by mavas84** [comment]
Hello @JCHDG 

Thank you for reaching out and for taking the time to report this.
We'll make sure to check the changes thoroughly.
Thank you once again for reporting this.

**Comment by mavas84** [comment]
Hello @JCHDG 

Thank you for your patience
We've tested this on  VPS and it's working exactly as it should
PHP 7.4.30
WP 6.0.1
W3TC 2.2.4
In this case, we need more environment information including installed WP/themes/plugins with version numbers.  Additionally, it'd be great to know specifically what action or series of actions were taken to produce the error,
Thanks!

**Comment by JCHDG** [comment]
Here is the website specs
PHP 7.4.30
WP 4.9.20 - Theme is custom
W3TC 2.2.4 - With changes applied to DbCache_WpdbInjection_QueryCaching.php:600 - Page Cache: Disk: Enhanced - Minify: Mode:Auto Method:Disk HTML:Minify JS:JSMin CSS: Minify - Opcode Cache: Zend - Database Cache: Disk - Browser Cache: Enabled - Extension: AMP, Cloudflare, Fragment Cache, New Relic, Swarmify, Yoast SEO.

Sorry I didn't include this to the original post.

**Comment by dozn** [comment]
Your patch resolved this issue for me as well—appreciate it!
