### ISSUE TITLE
wp_parse_url()

### ISSUE THREAD

**Issue by Ch3maa** [W3EDGE/w3-total-cache#561]
when the URL has [], W3 puglin has this issue:

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/20695844/192633412-7f1027b2-e23e-4c12-ac3e-4affb98890ac.png">

**Comment by mavas84** [comment]
Hello @Ch3maa 

Thank you for reaching out and I am sorry about the issue you are experiencing.
There is a pull request for this that will be included in the next release. Please check [this PR](https://github.com/W3EDGE/w3-total-cache/pull/549/commits/4ba2b5932f35c89354e7ab139f37d9482edf23a2) and make the changes to wp-content/plugins/w3-total-cache/DbCache_WpdbInjection_QueryCaching.php accordingly.
Let me know if this helps!

Thanks!
