### ISSUE TITLE
Don't cache front page option does not work in specific scenario

### ISSUE THREAD

**Issue by kontur** [W3EDGE/w3-total-cache#562]
Hello,

I'm using a randomizing logic to server one of several possible homepages. The page ID to serve is decided on first page load and saved to the session/cookie for that user. The actual logic happens in the `pre_get_posts` action hook, where we're overwriting the `page_id` of the query (should certain conditions be met).

Whenever caching is activated from your plugin, this fails to work, even when the "Don't cache front page" option is active. I have also tried adding a specific `front-page.php` template with the `define('DONOTCACHEPAGE', true);` constant. Both to no avail. I clear the cache, visit the front page, a random front page gets picked as per our custom logic, but that front page gets served to all users (as is expected when it is cached).

Can you advise how to debug this further or get that particular URL excluded from caching? I tried in the `Never cache the following pages:` settings, but how would I target the URL root there? Any other ideas?

**Comment by mavas84** [comment]
Hello @kontur 

Thank you for reaching out and I am happy to assist you with this.
`define('DONOTCACHEPAGE', true);` works when added to a specific template. However, in your case, this may be just one of the home pages.
In Performance>Page Cache, there is an option "Cache front page" so if you can confirm if this option is enabled the problem still persists.
As for the `Never cache the following pages: `, you can simply add / and this will make sure that the homepage of the visiting URL is not cached.
You can check this by inspecting the source:
`Page Caching using disk: enhanced (Requested URI is rejected) `

I hope this helps!

Thanks!

**Comment by kontur** [comment]
I am having "Don't cache frontpage" checked and `/` added to "Never cache the following pages". Still seeing `Page Caching using disk: enhanced (Requested URI is rejected)` in the source after cleaning the cache.

**Comment by maxicus** [comment]
>  The actual logic happens in the pre_get_posts action hook, where we're overwriting the page_id of the query (should certain conditions be met).

@kontur it depends on how you implemented it, but guess you end up rendering regular page (`single*.php` in a theme), and

> tried adding a specific front-page.php template with the define('DONOTCACHEPAGE', true); constant.

is not called at all.
if that's the case, you need to define('DONOTCACHEPAGE', true); in that page rendering code when its in homepage-mode, or better - right in your `pre_get_posts action hook`
