### ISSUE TITLE
'WP_SITEURL' prevent JS minify from working

### ISSUE THREAD

**Issue by moralonhub** [W3EDGE/w3-total-cache#568]
After define 'WP_SITEURL' 

define( 'WP_SITEURL', 'http://example.com/fo/' );

JS minify stop working

"wp-content/cache/log/000000/minify.log"

[Thu, 06 Oct 2022 12:08:58 +0000] [/fo/] [-] processing tag .script type='text/javascript' src='http://example.com/wp-content/themes/xxx/js/yyy.js?ver=5.9.4' id='yyy-js'../script.
[Thu, 06 Oct 2022 12:08:58 +0000] [/fo/] [-] is_file_for_minification: external not whitelisted url http://example.com/wp-content/themes/xxx/js/yyy.js?ver=5.9.4
[Thu, 06 Oct 2022 12:08:58 +0000] [/fo/] [-] file  didnt pass minification check: file_for_min: false ignore_js_files: false

**Comment by mavas84** [comment]
Hello @moralonhub 

Thank you for reaching out. As per our conversation in the wp.org topic related to this, we've confirmed the issue.
Just a small correction, as you mentioned in the forum post, the problem occurs when `‘WP_HOME’` is defined and not `'WP_SITEURL'`
As I mentioned before, we've confirmed this and this is added to the backlog to be in future releases.
Please make sure to track the progress of the ticket.

Reference topic: https://wordpress.org/support/topic/wp_siteurl-prevent-js-minify-from-working/

Thanks!

**Comment by mavas84** [comment]
Hello @moralonhub 
Thank you for your patience. 
WP_HOME is where WP thinks site's root URL is (a base URL for links)
Example: If you had to integrate a WP blog into your rails site, and configured nginx/apache to route all requests to /blog to WordPress, while all other requests went to your rails app. So you can set WP_HOME to mydomain.com for WP links to work correctly, but and have to set WP_SITEURL to mydomain.com/blog for WP static assets to be found inside WP directory.
This being said, if you define ‘WP_HOME’ without any subdirectory you will experience the problem.  Also, once we tried to replicate the problem, there were no issues with minify. 
It seems that you have not set up this properly and you are doing it the other way around.
Please make sure to check this [support article.](https://wordpress.org/support/article/giving-wordpress-its-own-directory/)

Thanks!
