### ISSUE TITLE
PHP deprecation notice 

### ISSUE THREAD

**Issue by superpoincare** [W3EDGE/w3-total-cache#575]
I see these notices while using the plugin Query Monitor. 

![image](https://user-images.githubusercontent.com/13736892/199497165-2be1894a-d0d4-432e-b5c9-b158a73113c1.png)

**Comment by mavas84** [comment]
Hello @superpoincare 

Thank you for reaching out!
Can you please share which PHP version you are using at the moment so we can try and replicate this?
Thanks!
