### ISSUE TITLE
JS error when emptying Cache in Dashboard>Home

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#593]
After updating the media query string in the top admin bar using Performance>Purge Modules>Browser Cache: Update Media query string, the W3TC is showing the message on the page /wp-admin/index.php?w3tc_note=flush_browser_cache
The Media Query string has been successfully updated.
The setting change(s) made either invalidate the cached data or modify the behavior of the site.  Empty the Cache now to provide a consistent user experience. 
![image](https://user-images.githubusercontent.com/40050744/205978135-201896af-a223-40cf-8184-6873608b9e9e.png)

If the "Empty the page cache" button in any page other than W3TC Dashboard, no action will be taken and the console  error appears:
e
```
Uncaught ReferenceError: w3tc_beforeupload_unbind is not defined
    at HTMLInputElement.on click (w3tc_note=flush_browser_cache:855:492)
```
Reference topic: https://wordpress.org/support/topic/javascript-error-when-clicking-empty-page-cache-hide-this-message-on-dashboard/

**Comment by jamieburchell** [comment]
@cssjoe I just experienced this again but this time from the message about needing to clear the cache due to plugins being disabled/enabled. The message was shown on the WP dashboard again. Is this the same issue?

**Comment by cssjoe** [comment]
@jamieburchell When I try to replicate your reported issue, I see the message "Page cache successfully emptied." and no console errors.  I activated a plugin and then clicked the button on the message to empty the page cache.  It was successful.  If you can still replicate the issue while on the latest version of our plugin, then please provide the exact steps to replicate and any other information to help us replicate the issue.  Thank you.

**Comment by jamieburchell** [comment]
I'm not seeing this either when manually disabling and then enabling a plugin. Interestingly, I don't think I had manually disabled or enabled a plugin when the message appeared, so I'm not sure what triggered the prompt with the button that didn't work. I'll keep an eye on it.

**Comment by jamieburchell** [comment]
@cssjoe I've noticed this happening again with the latest version of the plugin:

https://watch.screencastify.com/v/ubI4rzBxR6Yr6Tk0cxtO
