### ISSUE TITLE
Archive page not purged for scheduled CPT

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#595]
When the CPT is scheduled for publish, once published, the CPT is not purged from the cache.

Reference topic: https://wordpress.org/support/topic/archive-page-not-purged-for-scheduled-cpt/

**Comment by jamieburchell** [comment]
It's the CPT archive page which is not purged from the cache.

**Comment by jamieburchell** [comment]
Just tested this in 2.2.12 and unfortunately my CPT archive page cache still did not clear when a scheduled CPT post was published.
