### ISSUE TITLE
memcache plugin instructions don't match debian php config

### ISSUE THREAD

**Issue by markolbert** [W3EDGE/w3-total-cache#600]
There's an ini file that needs to be copied to the php environment in the installation instructions:

cp /path/to/your/website/wp-content/plugins/w3-total-cache/ini/memcache.ini /etc/php.d/

However, my system (debian 10) has no /etc/php.d/ directory. Instead, it has a series of subdirectories under /etc/php, one for each version of php installed (e.g., /etc/php/7.4, /etc/php/8.1)

Where do I copy that ini file?

**Comment by mavas84** [comment]
Answered on https://wordpress.org/support/topic/cant-get-object-cache-recognized/
