### ISSUE TITLE
Enabled Minify doesn't show the contents of the website

### ISSUE THREAD

**Issue by bishalbarua** [W3EDGE/w3-total-cache#608]
Hi. I have an issue with W3 Cache Plugin. When I enable the minify option my website loads faster but the contents don't show up. What should I do?

**Comment by mavas84** [comment]
Hey @bishalbarua 
Thank you for reaching out.
I've replied to all your messages.
Please make sure to submit your request via the proper support channel. Facebook and Twitter should not be used as the support platform. 
Please use the wp.org forum or contact us directly via the Plugin in Performance>Support>Submit a bug report, or via our website contact form https://www.w3-edge.com/contact/ Please make sure that Minify option is enabled in the General settings and disable the settings in Performance>minify one by one (HTML minify, JS minify, CSS  minify) and see which one might be causing the issue. 
Make sure to save all settings and purge the cache after each option is disabled.
Once again, please reach out to us via any of the mentioned support channels.
Thanks!
