### ISSUE TITLE
Link to extension are broken

### ISSUE THREAD

**Issue by KnusperAdmin** [W3EDGE/w3-total-cache#609]
https://github.com/W3EDGE/w3-total-cache/blob/6669102996cbef3e5dd9ae453003206390477f03/Extension_WordPressSeo_Plugin_Admin.php#L88

When you install and enable "W3 total cache" with a already existing yoast Plugin, you got the message to enable the extension in W3TC (without any hyperlink).

**Comment by isrgrajan** [comment]
Greetings! @KnusperAdmin, have you tried **[Health Check & Troubleshooting](https://wordpress.org/plugins/health-check/)** plugin to check comparability or conflict issues?

**Comment by mavas84** [comment]
Hello @KnusperAdmin 

Thank you for reaching out and for taking the time to bring this to our attention. We'll make sure to check and fix this, and in the meantime, you can enable the extension in the W3 Total Cache settings Performance>Extensions:
![image](https://user-images.githubusercontent.com/40050744/209572732-62f1f25a-daaa-42f1-b26f-99c652692899.png)

Thanks!

**Comment by KnusperAdmin** [comment]
Thanks for your fast feedback!
I get the "workaround way" already, but it think the link would be very helpful for some other users.
