### ISSUE TITLE
Uncaught Error: Call to undefined function W3TC\get_filesystem_method()

### ISSUE THREAD

**Issue by isrgrajan** [W3EDGE/w3-total-cache#610]
**It seems there's some bug that need to be fixed.**

An error of type E_ERROR was caused in line 22 of the file `/public_html/wp-content/plugins/w3-total-cache/Util_WpFile.php`. Error message: Uncaught Error: Call to undefined function `W3TC\get_filesystem_method()` in `/public_html/wp-content/plugins/w3-total-cache/Util_WpFile.php:22`
Stack trace:
`#0 /public_html/wp-content/plugins/w3-total-cache/Extension_ImageService_Plugin_Admin.php(952): W3TC\Util_WpFile::ajax_check_credentials('`

Please test `Extension ImageService Plugin` against various file types like `.webp`, '.svg' etc.

**Comment by mavas84** [comment]
Hello @isrgrajan 
Thank you for reaching out.

We already have the ticket for this. Please refer to ticket 591 and make sure to track the progress.
https://github.com/W3EDGE/w3-total-cache/issues/591
Thanks!
