### ISSUE TITLE
MAX CDN Shutdown many WordPress Sites are Down

### ISSUE THREAD

**Issue by HasaanCh** [W3EDGE/w3-total-cache#620]
MAXCDN is not working anymore and most of the WordPress sites too, that were using the CDN feature using W3 Plugin.

https://twitter.com/search?q=maxcdn&src=typed_query

**Comment by mavas84** [comment]
Hello @HasaanCh 

Thank you for reaching out. 
As I've mentioned via the support channel, we will address this and please make sure to migrate your CDN.
Please check more about this on [this link](https://www.stackpath.com/blog/maxcdn-and-securecdn-are-retiring-heres-what-it-means-for-you)
