### ISSUE TITLE
Cannot accept comment

### ISSUE THREAD

**Issue by andrewlakomski** [W3EDGE/w3-total-cache#632]
I've encountered error while accepting comment:

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class W3TC\\Util_AttachToActions does not have a method "on_comment_status" in /home/{dir}/public_html/wp-includes/class-wp-hook.php:308\nStack trace:\n#0 /home/{dir}/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()\n#1 /home/{dir}/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()\n#2 /home/{dir}/public_html/wp-includes/comment.php(2452): do_action()\n#3 /home/{dir}/public_html/wp-includes/comment.php(1643): wp_set_comment_status()\n#4 /home/{dir}/public_html/wp-admin/comment.php(317): wp_spam_comment()\n#5 {main}\n  thrown in /home/{dir}/public_html/wp-includes/class-wp-hook.php on line 308', referer: https://website.com/wp-admin/comment.php?action=spam&c=52458

**Comment by cssjoe** [comment]
We do apologize for the issue.  We have a fix ready to deploy in the next release 2.2.12.  In the meantime, you can comment out [line 33 in Util_AttachToActions.php](https://github.com/W3EDGE/w3-total-cache/blob/master/Util_AttachToActions.php#L33) or add the [lines in our pull request](https://github.com/W3EDGE/w3-total-cache/pull/630/files#diff-5ee42fa2e95f8d210587e861837c0ea5ec60696f905e53e7b229b4a91a9d2bcbR134-R143), which is the actual fix.
