### ISSUE TITLE
Add TLS support for Redis

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#67]
Reference topic: https://wordpress.org/support/topic/add-tls-support-for-redis/

**Comment by maxicus** [comment]
implemented by https://github.com/W3EDGE/w3-total-cache/commit/b31235f81d5ff7875e55a8939ba015014bafd26c

**Comment by MuffintopSpeedos** [comment]
Was this feature removed? 

I'm getting log spam of "[php7:notice] [pid 302932] [client <my IP>:56640] read error on connection to <redis host>:25061"
