### ISSUE TITLE
Notice in Util_Environment.php

### ISSUE THREAD

**Issue by sigismund** [W3EDGE/w3-total-cache#68]
W3 Total Cache version: 0.10.1
WordPress version: 5.2.4

There is a missing check when trying to access post ID.

Problematic code:
```
//...
elseif ( ( is_single() || is_page() ) && is_array( $posts ) ) {
			return $posts[0]->ID;
//...
```
Problem:
$posts can be an empty array

**Comment by maxicus** [comment]
Makes sense.
Fixed by https://github.com/W3EDGE/w3-total-cache/commit/1c6e7cd87f5bbd3cc8c7b80d0b97b6d29480661d
