### ISSUE TITLE
AMP pages send HTTP2 preloading headers of parent page when Disk:Enhanced is used

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#70]
AMP pages also pick up the preloading. Because of this, they are loading resources that are not being used in AMP pages.
Reference topic: https://wordpress.org/support/topic/how-to-disable-http2-preloading-for-amp-pages/

**Comment by maxicus** [comment]
fixed by https://github.com/W3EDGE/w3-total-cache/commit/6c0204143e5c51e5b8b762c1aa3001ff26fb321d
