### ISSUE TITLE
W3TC security headers not working on Nginx with Disk:Enhanced page cache

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#78]
Reference topic: https://wordpress.org/support/topic/w3tc-security-header-not-working-on-nginx/

**Comment by maxicus** [comment]
documentation about this behavior here:
http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header

There could be several add_header directives. These directives are inherited from the previous level if and only if there are no add_header directives defined on the current level.

**Comment by maxicus** [comment]
fixed by https://github.com/W3EDGE/w3-total-cache/commit/7912180384592f394fba8ec8ef12cfc3dd300d50
