### ISSUE TITLE
W3TC - W3 Total Cache v10.0.1 - error after upgrade to WordPress v5.3

### ISSUE THREAD

**Issue by Fabio-Perri** [W3EDGE/w3-total-cache#79]
Hi, dear W3 Total Cache Team, i use:

WordPress v5.3

W3TC - W3 Total Cache v10.0.1

After upgrade to new WordPress v5.3 i have this error:

Warning: Declaration of W3TC\DbCache_Wpdb::prepare($query, $args) should be compatible with wpdb::prepare($query, …$args) in /home/xxxxxx/public_html/wp-content/plugins/w3-total-cache/DbCache_Wpdb.php on line 8

This error, also is opened and reported by many different users on the official support forum of  W3TC - W3 Total Cache on WordPress.org over 4 hours ago at this link:

https://wordpress.org/support/topic/plugin-not-compatible-with-new-wordpress-update-5-3/

Please help me and thanks in advance for the support.

**Comment by amgmbs** [comment]
The problem occurs on php 7.4 and 7.3
With 7.2 the plugins is ok

I wonder what the WP core team did this time

**Comment by wixaw** [comment]
> With 7.2 the plugins is ok

Hello
I have PHP 7.2.22 and the same problem

**Comment by metrony** [comment]
I have the same error on my site.
[https://askcybersecurity.com/] (https://askcybersecurity.com/)

 I could always access the WP Dashboard unlike some others reported
**Per advice here:**
[https://wordpress.org/support/topic/plugin-not-compatible-with-new-wordpress-update-5-3/page/2/#post-12125313 ](https://wordpress.org/support/topic/plugin-not-compatible-with-new-wordpress-update-5-3/page/2/#post-12125313)

I disbaled the database cache (until there is a fix) worked to get rid of the error. In the dashboard go to Performance (W3C) - > Settings General and scroll down to disbale

**Comment by bwmarkle** [comment]
Hi everyone. We're very sorry about the issues after the WordPress 5.3 upgrade. We've got a fix, and we're waiting for all of our automated tests to complete before pushing it live. We will have a patch available today, it should be shortly.

**Comment by bwmarkle** [comment]
Hi again everyone. We just released **W3 Total Cache 0.10.2**, which is a patch version to address the WordPress 5.3 issues.

Testing shows the issue is resolved. If anyone would be willing to upgrade and let us know how it goes, it would be much appreciated!

Thanks,
\- Brad

**Comment by metrony** [comment]
Took the uodated plugin and it works! Thanks for the quick fix :)

**Comment by bwmarkle** [comment]
Thanks for the feedback @metrony!

**Comment by br3bel** [comment]
I have Php 7.2.24 and no such error/warning

**Comment by STAYHEALTHYBD** [comment]
hi I am facing same problem with my website. I can not enter into wordpress dashboard. In that case how can i upgrade this plugins? please let me know.

**Comment by br3bel** [comment]
Disable all plugins, then you may login to wordpress dashboard.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by STAYHEALTHYBD** [comment]
br3bel , thanks for your suggestion, however , i tried to disable plugins but i can not access my plugin option

**Comment by br3bel** [comment]
Rename the plugin folder via ftp and all plugins will be disabled.
________________________________

**Comment by amgmbs** [comment]
why all plugins?

just rename the plugin folder, for the plugin that you suspect causes trouble

**Comment by benjamindejong** [comment]
Hi, We're running WP 5.3.1 with W3TC 0.12.0 on PHP 7.0 and still getting this warning. Should it be fixed?

**Comment by maxicus** [comment]
W3TC 0.12.0 doesnt have `W3TC\DbCache_Wpdb::prepare` method at all, so if you see the warning noted -  you don't use that W3TC version.

**Comment by benjamindejong** [comment]
The instance of `DbCache_Wpdb` is based on `DbCache_WpdbNew` or `DbCache_WpdbLegacy` and they does have a method `prepare`

**Comment by maxicus** [comment]
> The instance of DbCache_Wpdb is based on DbCache_WpdbNew or DbCache_WpdbLegacy

@benjamindejong it doesn't.
But if you need some help with your warning - please copy-paste it here.
