### ISSUE TITLE
svg cache-control max-age header is wrong

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [W3EDGE/w3-total-cache#8]
svg files should have a cache-control like image files like png. 

Instead it is set to that of html. 

The issue is this line

https://github.com/W3EDGE/w3-total-cache/blob/f50a4711789bbd7206432391d2a3dd9cd40bffa4/inc/mime/html.php#L9

which needs to be removed.

**Comment by maxicus** [comment]
Makes sense. Fixed by https://github.com/W3EDGE/w3-total-cache/commit/aa197750affe78a468db120ebde12eb5c72d212e
