### ISSUE TITLE
Can't get rid of footer

### ISSUE THREAD

**Issue by AMDphreak** [W3EDGE/w3-total-cache#81]
How do I get rid of the footer? It doesn't match my theme's style. It's the wrong font and size and color.

It doesn't show up in the site's theme files or in the footer-specific files. Following instructions found online did not help find the file to remove this.

**Comment by mavas84** [comment]
Hello @AMDphreak 
This repository is not suitable for support. Please don't use our issue tracker for support requests. Support can take place through the appropriate channels:

The support form can be found in the Performance>Support page of your wp-admin.
Our community forum on [wp.org](https://wordpress.org/support/plugin/w3-total-cache/)
Support requests in issues on this repository will be closed on sight.

**Comment by AMDphreak** [comment]
> 
> 
> Hello @AMDphreak
> This repository is not suitable for support. Please don't use our issue tracker for support requests. Support can take place through the appropriate channels:
> 
> The support form can be found in the Performance>Support page of your wp-admin.
> Our community forum on [wp.org](https://wordpress.org/support/plugin/w3-total-cache/)
> Support requests in issues on this repository will be closed on sight.

Not a support request. This is a UI enhancement and documentation bug. Consider rephrasing :|

**Comment by harryjackson1221** [comment]
Hey @AMDphreak - We are revisiting the interface option that allows you to add the footer link, and really appreciate you bringing it to our attention. We did already have plans to address it in the near future, but seeing that other people are having the same problem will help us prioritize it accordingly. 

I am reopening this ticket, so we can get that setting removed in an upcoming release. Sorry for any confusion in the matter!

In the meantime, you can correct this by editing /wp-content/w3tc-config/master.php
Change: “common.support”: “footer”,
To: “common.support”: “”,

**Comment by AMDphreak** [comment]
> 
> 
> Hey @AMDphreak - We are revisiting the interface option that allows you to add the footer link, and really appreciate you bringing it to our attention. We did already have plans to address it in the near future, but seeing that other people are having the same problem will help us prioritize it accordingly.
> 
> I am reopening this ticket, so we can get that setting removed in an upcoming release. Sorry for any confusion in the matter!
> 
> In the meantime, you can correct this by editing /wp-content/w3tc-config/master.php
> Change: “common.support”: “footer”,
> To: “common.support”: “”,

1. Thank you.
2. I don't mind repping you guys on my site. You've done a bang-up job programming in an awful language like PHP. I just want it to look like part of the site not like it was slapped on after the fact. Not sure what this would entail but something like sticking it at the end of the theme file...or maybe in the footer seection for the theme file?
