### ISSUE TITLE
Plugin offers to download a .gz archive instead of website.

### ISSUE THREAD

**Issue by monosux** [W3EDGE/w3-total-cache#82]
Hi, 

At first, thank you for your plugin, great job!

I was facing a bug: sometimes plugin offers users to download a .gz archive instead of showing website:

![gz archive](https://i.imgur.com/6meeaoA.png)

Cache cleaning temporary helps, but then it happens again.

It happened twice in the last month and I had to deactivate the plugin. 

I found several references to this problem, but could not find a solution:
https://wordpress.org/support/topic/download-gz-downloads-when-viewing-the-site-sometimes/

Plugin version was 0.10.1

Any idea how to prevent this bug?

**Comment by mavas84** [comment]
Hello @monosux 
Thank you for posting this issue and I am sorry about the issue you are experiencing with download.gz
The problem with downloading gzip files is probably that there already is a configuration in the setup that handles gzip files. If you enable gzip in Performance => Browser Cache => HTML & XML, the configuration gets messed up and the browser will download a gzip file in situations like yours. Disabling the gzip option in Performance => Browser Cache => HTML & XML will probably solve this issue.
You can also define `W3TC_PAGECACHE_STORE_COMPRESSION_OFF` constant that allows not to generate _gzip and similar files. It helps in the cases when the server configuration
doesn’t allow mime type overwrites so cached content ends up with browser
download action.
It’s located in /wp-content/plugins/w3-total-cache/PgCache_ContentGrabber.php line 1191


```
if ( defined( 'W3TC_PAGECACHE_STORE_COMPRESSION_OFF' ) ) {
			return $compressions;

		}
```
You just need to add `define('W3TC_PAGECACHE_STORE_COMPRESSION_OFF', true);`

to the wp-config.php file.
Please let us know if this helps!
