### ISSUE TITLE
HTML displayed in rss feeds on dashboard

### ISSUE THREAD

**Issue by bwmarkle** [W3EDGE/w3-total-cache#83]
![image](https://user-images.githubusercontent.com/5925563/69180463-4fbb1e00-0adb-11ea-96bc-403f09239fc9.png)

**Comment by maxicus** [comment]
it's feedburner problem. see http://feeds.feedburner.com/W3TOTALCACHE

better to fix there - i'm not aware about that integration. never set it up or touched.
if you fail - let me know, i'll have to add a hack to plugin's code. But it will also block something like 
"I'm failing to add <hello> value to bla-bla" topics.

**Comment by maxicus** [comment]
fixed by https://github.com/W3EDGE/w3-total-cache-private/commit/36ec203f3c318c91d4f7473683d01e063342471c
