### ISSUE TITLE
Lazy Load - Add ability to change Lazy Load Threshold

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#86]
Ability to change the lazy load threshold to control how soon upon scroll images are loaded
Reference topic: https://wordpress.org/support/topic/lazy-load-question-answer/

**Comment by jonasm82** [comment]
+1 For this. Being able to fine tune the lazy loading threshold for a site can make a massive UX difference.

**Comment by cssjoe** [comment]
Also came up in https://wordpress.org/support/topic/w3tc-creating-a-blank-image-slide-in-image-slider-lazy-loading/

**Comment by deewinc** [comment]
> Also came up in https://wordpress.org/support/topic/w3tc-creating-a-blank-image-slide-in-image-slider-lazy-loading/

Thanks for including the issue. I do hope that the issue will be fixed soon. The Lazy load feature on W3TC is so powerful than any other plugin I have seen out there. 

The issue in this case is the placeholder that remains in place even after downloading the images. Something should be done to force-swap the placeholder once the images are downloaded.

**Comment by djavet** [comment]
Came up also here: https://www.boldgrid.com/support/question/lazy-load-failed-on-ajax-blog-module/

**Comment by conandrum** [comment]
W3TC is the most efficient lazyload I have used.
Unfortunately some of my products are left without an image on my /shop page.
Please fix.

**Comment by deewinc** [comment]
Any progress about this issue? It just went cold like that?

**Comment by deewinc** [comment]
> W3TC is the most efficient lazyload I have used.
> Unfortunately some of my products are left without an image on my /shop page.
> Please fix.

That it true. I shared how it affects slides and product tables months ago.

**Comment by deewinc** [comment]
@maxicus ~ please please please I beg you to take up this issue. 🥺🥺🥺🥺

**Comment by deewinc** [comment]
@maxicus thank you so much. **Fingers crossed!**

**Comment by lucasdemoraesc** [comment]
@deewinc, did this fix your problem?

I have the same problem as you reported here https://wordpress.org/support/topic/w3tc-creating-a-blank-image-slide-in-image-slider-lazy-loading/ ...

However, still no solution

**Comment by deewinc** [comment]
@lucasdemoraesc ~ Sadly, it never fixed the issue. 

I switched to a different cache plugin.
