### ISSUE TITLE
Lazy Load - Lazy Loading should not be enabled in RSS feeds

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#88]
he lazy loading feature is currently applied to images in RSS feeds, which breaks the img src URLs. is_feed() should be added to the array of conditions that return false in the can_process method in w3-total-cache\LazyLoad_Plugin.php.
Reference topic: https://wordpress.org/support/topic/lazy-loading-should-not-be-enabled-in-rss-feeds/

**Comment by maxicus** [comment]
fixed by https://github.com/W3EDGE/w3-total-cache/commit/3659f05a33927dd05c72e8a9dbe9a5900f03e7f2
