### ISSUE TITLE
Lazy load breaks Javascript

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#91]
When the lazy load is enabled (General Setting=> User Experience=> Lazy Loading) any image tag that is inside a javascript variable would be broken/not valid. Cause: the regex string-replacement, perform by LazyLoad_Plugin.php put class=”lazy” and placeholder src=”data: …” into the img tag without escaping the quote.
For example, put the following simple script to the page:

```
<script>
var mydef ={"myimage":"<img src=\"https:\/\/www.example.com/myimage.jpg\" alt=\"image desc\">"}
</script>
```
If the lazyload is active, the javascript will breaks into:

```
<script>
var mydef ={"myimage":"<img class="lazy" src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%201%201'%3E%3C/svg%3E" data-src=\"https:\/\/www.example.com/myimage.jpg\" alt=\"image desc\">"}
</script>
```
The search and replace should be done in two separate ways diferrentiating javascript block and html block.
Reference topic: https://wordpress.org/support/topic/bug-lazyloading-breaks-javascript/

**Comment by maxicus** [comment]
fixed by https://github.com/W3EDGE/w3-total-cache/commit/72378c5a51d29a48924282bad176009dd51af3e2
