### ISSUE TITLE
PHP 7.4 PHP Deprecated: Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#92]
Reference topic: https://wordpress.org/support/topic/php-deprecated-function-get_magic_quotes_gpc-is-deprecated/

**Comment by viktorgino** [comment]
From the documentation : 

> Returns 0 if magic_quotes_gpc is off, 1 otherwise. Or always returns FALSE as of PHP 5.4.0. 

Source: https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

So the get_magic_quotes_gpc() can be removed altogether. Quick search show that it can be found here:
https://github.com/W3EDGE/w3-total-cache/blob/master/Util_Request.php#L25
https://github.com/W3EDGE/w3-total-cache/blob/master/lib/Minify/HTTP/ConditionalGet.php#L367
https://github.com/W3EDGE/w3-total-cache/blob/master/PgCache_ContentGrabber.php#L1742
https://github.com/W3EDGE/w3-total-cache/blob/master/lib/Db/mssql.php#L522

**Comment by bwmarkle** [comment]
Just a heads up, issues https://github.com/W3EDGE/w3-total-cache/issues/92 and https://github.com/W3EDGE/w3-total-cache/pull/95 are being discussed internally as they cause problems with PHP 5.3, and a decision needs to be made whether we still need to support php 5.3
