### ISSUE TITLE
HTML Minify breaks the featured image by sharing on whats app

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#96]
When HTML minify is active, it breaks the featured image when sharing on WhatsApp. The image does not appear.
Reference topic: https://wordpress.org/support/topic/minifying-the-html-breaks-the-featured-image-by-sharing-on-whatsapp/

**Comment by djixas** [comment]
Latest minify for us broke amp plugin and made all pages invalid as it made framborder value blank, rolling back to w3-total-cache.0.10.2

**Comment by kazazor** [comment]
Please note that this is happening only on Android. iOS & Whatsapp for web are fine.

Also, HTML minify breaks the description of the sharing as well and not just the image.
In general, some og tags are not working when W3 total cache HTML minify is on.

Please note: The image does NOT work at all even when HTML minify is disabled but Autoptimize is installed together with W3TC

**Comment by maxicus** [comment]
dup of #292 or #187
